spack:
  packages:
    all:
      providers:
        target: [x86_64]
        blas:
        - openblas
        mpi:
        - openmpi
      compiler:
      - gcc@9.4.0
  specs:
  - cmake %gcc@9.4.0 arch=x86_64
  - hypre~int64~internal-superlu %gcc@9.4.0 arch=x86_64
  - petsc+double~int64~superlu-dist %gcc@9.4.0 arch=x86_64
  - openmpi %gcc@9.4.0 arch=x86_64
  - openblas~ilp64 %gcc@9.4.0 arch=x86_64
  - suite-sparse %gcc@9.4.0 arch=x86_64
  - superlu-mt~int64~blas %gcc@9.4.0 arch=x86_64
  - superlu-dist~int64 ^parmetis~int64 %gcc@9.4.0 arch=x86_64
  - trilinos+tpetra gotype=int %gcc@9.4.0 arch=x86_64
  - xbraid %gcc@9.4.0 arch=x86_64
  config:
    install_tree: /opt/software
  mirrors:
    local: /var/cache/spack-mirror
    spack: https://binaries.spack.io/develop
  repos: []
  upstreams: {}
  concretizer:
    unify: true
  view:
    default:
      root: /opt/view
      projections:
        superlu-mt: '{name}'
        superlu-dist: '{name}'
