# action.yml
name: 'SUNDIALS CI Docker'
description: 'SUNDIALS CI environment in a Docker containers'

inputs:
  branchname:  # id of input
    description: 'branchname'
    required: true
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --branchname ${{ inputs.branchname }}