! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! ---------------------------------------------------------------
! Programmer(s): Auto-generated by swig.
! ---------------------------------------------------------------
! SUNDIALS Copyright Start
! Copyright (c) 2025-2026, Lawrence Livermore National Security,
! University of Maryland Baltimore County, and the SUNDIALS contributors.
! Copyright (c) 2013-2025, Lawrence Livermore National Security
! and Southern Methodist University.
! Copyright (c) 2002-2013, Lawrence Livermore National Security.
! All rights reserved.
!
! See the top-level LICENSE and NOTICE files for details.
!
! SPDX-License-Identifier: BSD-3-Clause
! SUNDIALS Copyright End
! ---------------------------------------------------------------

module fsunlinsol_spfgmr_mod
 use, intrinsic :: ISO_C_BINDING
 use fsundials_core_mod
 implicit none
 private

 ! DECLARATION CONSTRUCTS
 integer(C_INT), parameter, public :: SUNSPFGMR_MAXL_DEFAULT = 5_C_INT
 integer(C_INT), parameter, public :: SUNSPFGMR_MAXRS_DEFAULT = 0_C_INT

 integer, parameter :: swig_cmem_own_bit = 0
 integer, parameter :: swig_cmem_rvalue_bit = 1
 integer, parameter :: swig_cmem_const_bit = 2
 type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: cptr = C_NULL_PTR
  integer(C_INT), public :: cmemflags = 0
 end type
 ! struct struct SUNLinearSolverContent_SPFGMR_
 type, public :: SUNLinearSolverContent_SPFGMR_
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_maxl => swigf_SUNLinearSolverContent_SPFGMR__maxl_set
  procedure :: get_maxl => swigf_SUNLinearSolverContent_SPFGMR__maxl_get
  procedure :: set_pretype => swigf_SUNLinearSolverContent_SPFGMR__pretype_set
  procedure :: get_pretype => swigf_SUNLinearSolverContent_SPFGMR__pretype_get
  procedure :: set_gstype => swigf_SUNLinearSolverContent_SPFGMR__gstype_set
  procedure :: get_gstype => swigf_SUNLinearSolverContent_SPFGMR__gstype_get
  procedure :: set_max_restarts => swigf_SUNLinearSolverContent_SPFGMR__max_restarts_set
  procedure :: get_max_restarts => swigf_SUNLinearSolverContent_SPFGMR__max_restarts_get
  procedure :: set_zeroguess => swigf_SUNLinearSolverContent_SPFGMR__zeroguess_set
  procedure :: get_zeroguess => swigf_SUNLinearSolverContent_SPFGMR__zeroguess_get
  procedure :: set_numiters => swigf_SUNLinearSolverContent_SPFGMR__numiters_set
  procedure :: get_numiters => swigf_SUNLinearSolverContent_SPFGMR__numiters_get
  procedure :: set_resnorm => swigf_SUNLinearSolverContent_SPFGMR__resnorm_set
  procedure :: get_resnorm => swigf_SUNLinearSolverContent_SPFGMR__resnorm_get
  procedure :: set_last_flag => swigf_SUNLinearSolverContent_SPFGMR__last_flag_set
  procedure :: get_last_flag => swigf_SUNLinearSolverContent_SPFGMR__last_flag_get
  procedure :: set_ATimes => swigf_SUNLinearSolverContent_SPFGMR__ATimes_set
  procedure :: get_ATimes => swigf_SUNLinearSolverContent_SPFGMR__ATimes_get
  procedure :: set_ATData => swigf_SUNLinearSolverContent_SPFGMR__ATData_set
  procedure :: get_ATData => swigf_SUNLinearSolverContent_SPFGMR__ATData_get
  procedure :: set_Psetup => swigf_SUNLinearSolverContent_SPFGMR__Psetup_set
  procedure :: get_Psetup => swigf_SUNLinearSolverContent_SPFGMR__Psetup_get
  procedure :: set_Psolve => swigf_SUNLinearSolverContent_SPFGMR__Psolve_set
  procedure :: get_Psolve => swigf_SUNLinearSolverContent_SPFGMR__Psolve_get
  procedure :: set_PData => swigf_SUNLinearSolverContent_SPFGMR__PData_set
  procedure :: get_PData => swigf_SUNLinearSolverContent_SPFGMR__PData_get
  procedure :: set_s1 => swigf_SUNLinearSolverContent_SPFGMR__s1_set
  procedure :: get_s1 => swigf_SUNLinearSolverContent_SPFGMR__s1_get
  procedure :: set_s2 => swigf_SUNLinearSolverContent_SPFGMR__s2_set
  procedure :: get_s2 => swigf_SUNLinearSolverContent_SPFGMR__s2_get
  procedure :: set_V => swigf_SUNLinearSolverContent_SPFGMR__V_set
  procedure :: get_V => swigf_SUNLinearSolverContent_SPFGMR__V_get
  procedure :: set_Z => swigf_SUNLinearSolverContent_SPFGMR__Z_set
  procedure :: get_Z => swigf_SUNLinearSolverContent_SPFGMR__Z_get
  procedure :: set_Hes => swigf_SUNLinearSolverContent_SPFGMR__Hes_set
  procedure :: get_Hes => swigf_SUNLinearSolverContent_SPFGMR__Hes_get
  procedure :: set_givens => swigf_SUNLinearSolverContent_SPFGMR__givens_set
  procedure :: get_givens => swigf_SUNLinearSolverContent_SPFGMR__givens_get
  procedure :: set_xcor => swigf_SUNLinearSolverContent_SPFGMR__xcor_set
  procedure :: get_xcor => swigf_SUNLinearSolverContent_SPFGMR__xcor_get
  procedure :: set_yg => swigf_SUNLinearSolverContent_SPFGMR__yg_set
  procedure :: get_yg => swigf_SUNLinearSolverContent_SPFGMR__yg_get
  procedure :: set_vtemp => swigf_SUNLinearSolverContent_SPFGMR__vtemp_set
  procedure :: get_vtemp => swigf_SUNLinearSolverContent_SPFGMR__vtemp_get
  procedure :: set_cv => swigf_SUNLinearSolverContent_SPFGMR__cv_set
  procedure :: get_cv => swigf_SUNLinearSolverContent_SPFGMR__cv_get
  procedure :: set_Xv => swigf_SUNLinearSolverContent_SPFGMR__Xv_set
  procedure :: get_Xv => swigf_SUNLinearSolverContent_SPFGMR__Xv_get
  procedure :: release => swigf_release_SUNLinearSolverContent_SPFGMR_
  procedure, private :: swigf_SUNLinearSolverContent_SPFGMR__op_assign__
  generic :: assignment(=) => swigf_SUNLinearSolverContent_SPFGMR__op_assign__
 end type SUNLinearSolverContent_SPFGMR_
 interface SUNLinearSolverContent_SPFGMR_
  module procedure swigf_create_SUNLinearSolverContent_SPFGMR_
 end interface
 public :: FSUNLinSol_SPFGMR
 public :: FSUNLinSol_SPFGMRSetPrecType
 public :: FSUNLinSol_SPFGMRSetGSType
 public :: FSUNLinSol_SPFGMRSetMaxRestarts

! WRAPPER DECLARATIONS
interface
subroutine swigc_SUNLinearSolverContent_SPFGMR__maxl_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__maxl_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__maxl_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__maxl_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__pretype_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__pretype_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__pretype_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__pretype_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__gstype_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__gstype_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__gstype_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__gstype_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__max_restarts_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__max_restarts_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__max_restarts_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__max_restarts_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__zeroguess_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__zeroguess_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__zeroguess_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__zeroguess_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__numiters_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__numiters_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__numiters_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__numiters_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__resnorm_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__resnorm_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
real(C_DOUBLE), intent(in) :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__resnorm_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__resnorm_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
real(C_DOUBLE) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__last_flag_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__last_flag_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__last_flag_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__last_flag_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__ATimes_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__ATimes_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_FUNPTR), value :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__ATimes_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__ATimes_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_FUNPTR) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__ATData_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__ATData_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR), value :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__ATData_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__ATData_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__Psetup_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__Psetup_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_FUNPTR), value :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__Psetup_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__Psetup_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_FUNPTR) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__Psolve_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__Psolve_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_FUNPTR), value :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__Psolve_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__Psolve_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_FUNPTR) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__PData_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__PData_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR), value :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__PData_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__PData_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__s1_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__s1_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__s1_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__s1_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__s2_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__s2_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__s2_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__s2_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__V_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__V_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR), value :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__V_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__V_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__Z_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__Z_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR), value :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__Z_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__Z_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__Hes_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__Hes_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR), value :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__Hes_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__Hes_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__givens_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__givens_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR), value :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__givens_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__givens_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__xcor_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__xcor_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__xcor_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__xcor_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__yg_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__yg_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR), value :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__yg_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__yg_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__vtemp_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__vtemp_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__vtemp_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__vtemp_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__cv_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__cv_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR), value :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__cv_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__cv_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_SPFGMR__Xv_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__Xv_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR), value :: farg2
end subroutine

function swigc_SUNLinearSolverContent_SPFGMR__Xv_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__Xv_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR) :: fresult
end function

function swigc_new_SUNLinearSolverContent_SPFGMR_() &
bind(C, name="_wrap_new_SUNLinearSolverContent_SPFGMR_") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_SUNLinearSolverContent_SPFGMR_(farg1) &
bind(C, name="_wrap_delete_SUNLinearSolverContent_SPFGMR_")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_SUNLinearSolverContent_SPFGMR__op_assign__(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_SPFGMR__op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

function swigc_FSUNLinSol_SPFGMR(farg1, farg2, farg3, farg4) &
bind(C, name="_wrap_FSUNLinSol_SPFGMR") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT), intent(in) :: farg3
type(C_PTR), value :: farg4
type(SwigClassWrapper) :: fresult
end function

function swigc_FSUNLinSol_SPFGMRSetPrecType(farg1, farg2) &
bind(C, name="_wrap_FSUNLinSol_SPFGMRSetPrecType") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNLinSol_SPFGMRSetGSType(farg1, farg2) &
bind(C, name="_wrap_FSUNLinSol_SPFGMRSetGSType") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNLinSol_SPFGMRSetMaxRestarts(farg1, farg2) &
bind(C, name="_wrap_FSUNLinSol_SPFGMRSetMaxRestarts") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

end interface


contains
 ! MODULE SUBPROGRAMS
subroutine swigf_SUNLinearSolverContent_SPFGMR__maxl_set(self, maxl)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
integer(C_INT), intent(in) :: maxl
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = maxl
call swigc_SUNLinearSolverContent_SPFGMR__maxl_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__maxl_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__maxl_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__pretype_set(self, pretype)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
integer(C_INT), intent(in) :: pretype
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = pretype
call swigc_SUNLinearSolverContent_SPFGMR__pretype_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__pretype_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__pretype_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__gstype_set(self, gstype)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
integer(C_INT), intent(in) :: gstype
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = gstype
call swigc_SUNLinearSolverContent_SPFGMR__gstype_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__gstype_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__gstype_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__max_restarts_set(self, max_restarts)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
integer(C_INT), intent(in) :: max_restarts
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = max_restarts
call swigc_SUNLinearSolverContent_SPFGMR__max_restarts_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__max_restarts_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__max_restarts_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__zeroguess_set(self, zeroguess)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
integer(C_INT), intent(in) :: zeroguess
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = zeroguess
call swigc_SUNLinearSolverContent_SPFGMR__zeroguess_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__zeroguess_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__zeroguess_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__numiters_set(self, numiters)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
integer(C_INT), intent(in) :: numiters
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = numiters
call swigc_SUNLinearSolverContent_SPFGMR__numiters_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__numiters_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__numiters_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__resnorm_set(self, resnorm)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
real(C_DOUBLE), intent(in) :: resnorm
type(SwigClassWrapper) :: farg1 
real(C_DOUBLE) :: farg2 

farg1 = self%swigdata
farg2 = resnorm
call swigc_SUNLinearSolverContent_SPFGMR__resnorm_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__resnorm_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
real(C_DOUBLE) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__resnorm_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__last_flag_set(self, last_flag)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
integer(C_INT), intent(in) :: last_flag
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = last_flag
call swigc_SUNLinearSolverContent_SPFGMR__last_flag_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__last_flag_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__last_flag_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__ATimes_set(self, atimes)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(C_FUNPTR), intent(in), value :: atimes
type(SwigClassWrapper) :: farg1 
type(C_FUNPTR) :: farg2 

farg1 = self%swigdata
farg2 = atimes
call swigc_SUNLinearSolverContent_SPFGMR__ATimes_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__ATimes_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(C_FUNPTR) :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(C_FUNPTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__ATimes_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__ATData_set(self, atdata)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(C_PTR) :: atdata
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = self%swigdata
farg2 = atdata
call swigc_SUNLinearSolverContent_SPFGMR__ATData_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__ATData_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__ATData_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__Psetup_set(self, psetup)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(C_FUNPTR), intent(in), value :: psetup
type(SwigClassWrapper) :: farg1 
type(C_FUNPTR) :: farg2 

farg1 = self%swigdata
farg2 = psetup
call swigc_SUNLinearSolverContent_SPFGMR__Psetup_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__Psetup_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(C_FUNPTR) :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(C_FUNPTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__Psetup_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__Psolve_set(self, psolve)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(C_FUNPTR), intent(in), value :: psolve
type(SwigClassWrapper) :: farg1 
type(C_FUNPTR) :: farg2 

farg1 = self%swigdata
farg2 = psolve
call swigc_SUNLinearSolverContent_SPFGMR__Psolve_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__Psolve_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(C_FUNPTR) :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(C_FUNPTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__Psolve_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__PData_set(self, pdata)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(C_PTR) :: pdata
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = self%swigdata
farg2 = pdata
call swigc_SUNLinearSolverContent_SPFGMR__PData_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__PData_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__PData_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__s1_set(self, s1)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
class(N_Vector_), intent(in) :: s1
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = s1%swigdata
call swigc_SUNLinearSolverContent_SPFGMR__s1_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__s1_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(N_Vector_) :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__s1_get(farg1)
swig_result%swigdata = fresult
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__s2_set(self, s2)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
class(N_Vector_), intent(in) :: s2
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = s2%swigdata
call swigc_SUNLinearSolverContent_SPFGMR__s2_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__s2_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(N_Vector_) :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__s2_get(farg1)
swig_result%swigdata = fresult
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__V_set(self, v)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(C_PTR) :: v
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = self%swigdata
farg2 = v
call swigc_SUNLinearSolverContent_SPFGMR__V_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__V_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__V_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__Z_set(self, z)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(C_PTR) :: z
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = self%swigdata
farg2 = z
call swigc_SUNLinearSolverContent_SPFGMR__Z_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__Z_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__Z_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__Hes_set(self, hes)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(C_PTR), target, intent(inout) :: hes
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = self%swigdata
farg2 = c_loc(hes)
call swigc_SUNLinearSolverContent_SPFGMR__Hes_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__Hes_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), pointer :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__Hes_get(farg1)
call c_f_pointer(fresult, swig_result)
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__givens_set(self, givens)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
real(C_DOUBLE), dimension(*), target, intent(inout) :: givens
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = self%swigdata
farg2 = c_loc(givens(1))
call swigc_SUNLinearSolverContent_SPFGMR__givens_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__givens_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(:), pointer :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__givens_get(farg1)
call c_f_pointer(fresult, swig_result, [1])
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__xcor_set(self, xcor)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
class(N_Vector_), intent(in) :: xcor
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = xcor%swigdata
call swigc_SUNLinearSolverContent_SPFGMR__xcor_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__xcor_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(N_Vector_) :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__xcor_get(farg1)
swig_result%swigdata = fresult
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__yg_set(self, yg)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
real(C_DOUBLE), dimension(*), target, intent(inout) :: yg
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = self%swigdata
farg2 = c_loc(yg(1))
call swigc_SUNLinearSolverContent_SPFGMR__yg_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__yg_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(:), pointer :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__yg_get(farg1)
call c_f_pointer(fresult, swig_result, [1])
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__vtemp_set(self, vtemp)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
class(N_Vector_), intent(in) :: vtemp
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = vtemp%swigdata
call swigc_SUNLinearSolverContent_SPFGMR__vtemp_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__vtemp_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(N_Vector_) :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__vtemp_get(farg1)
swig_result%swigdata = fresult
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__cv_set(self, cv)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
real(C_DOUBLE), dimension(*), target, intent(inout) :: cv
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = self%swigdata
farg2 = c_loc(cv(1))
call swigc_SUNLinearSolverContent_SPFGMR__cv_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__cv_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(:), pointer :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__cv_get(farg1)
call c_f_pointer(fresult, swig_result, [1])
end function

subroutine swigf_SUNLinearSolverContent_SPFGMR__Xv_set(self, xv)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(C_PTR) :: xv
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = self%swigdata
farg2 = xv
call swigc_SUNLinearSolverContent_SPFGMR__Xv_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_SPFGMR__Xv_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: swig_result
class(SUNLinearSolverContent_SPFGMR_), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_SPFGMR__Xv_get(farg1)
swig_result = fresult
end function

function swigf_create_SUNLinearSolverContent_SPFGMR_() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(SUNLinearSolverContent_SPFGMR_) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_SUNLinearSolverContent_SPFGMR_()
self%swigdata = fresult
end function

subroutine swigf_release_SUNLinearSolverContent_SPFGMR_(self)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_SUNLinearSolverContent_SPFGMR_(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_SUNLinearSolverContent_SPFGMR__op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_SPFGMR_), intent(inout) :: self
type(SUNLinearSolverContent_SPFGMR_), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_SUNLinearSolverContent_SPFGMR__op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

function FSUNLinSol_SPFGMR(y, pretype, maxl, sunctx) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SUNLinearSolver_) :: swig_result
class(N_Vector_), intent(in) :: y
integer(C_INT), intent(in) :: pretype
integer(C_INT), intent(in) :: maxl
type(C_PTR) :: sunctx
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 
integer(C_INT) :: farg3 
type(C_PTR) :: farg4 

farg1 = y%swigdata
farg2 = pretype
farg3 = maxl
farg4 = sunctx
fresult = swigc_FSUNLinSol_SPFGMR(farg1, farg2, farg3, farg4)
swig_result%swigdata = fresult
end function

function FSUNLinSol_SPFGMRSetPrecType(s, pretype) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(SUNLinearSolver_), intent(in) :: s
integer(C_INT), intent(in) :: pretype
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = s%swigdata
farg2 = pretype
fresult = swigc_FSUNLinSol_SPFGMRSetPrecType(farg1, farg2)
swig_result = fresult
end function

function FSUNLinSol_SPFGMRSetGSType(s, gstype) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(SUNLinearSolver_), intent(in) :: s
integer(C_INT), intent(in) :: gstype
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = s%swigdata
farg2 = gstype
fresult = swigc_FSUNLinSol_SPFGMRSetGSType(farg1, farg2)
swig_result = fresult
end function

function FSUNLinSol_SPFGMRSetMaxRestarts(s, maxrs) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(SUNLinearSolver_), intent(in) :: s
integer(C_INT), intent(in) :: maxrs
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = s%swigdata
farg2 = maxrs
fresult = swigc_FSUNLinSol_SPFGMRSetMaxRestarts(farg1, farg2)
swig_result = fresult
end function


end module
