! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! ---------------------------------------------------------------
! Programmer(s): Auto-generated by swig.
! ---------------------------------------------------------------
! SUNDIALS Copyright Start
! Copyright (c) 2025-2026, Lawrence Livermore National Security,
! University of Maryland Baltimore County, and the SUNDIALS contributors.
! Copyright (c) 2013-2025, Lawrence Livermore National Security
! and Southern Methodist University.
! Copyright (c) 2002-2013, Lawrence Livermore National Security.
! All rights reserved.
!
! See the top-level LICENSE and NOTICE files for details.
!
! SPDX-License-Identifier: BSD-3-Clause
! SUNDIALS Copyright End
! ---------------------------------------------------------------

module fnvector_mpimanyvector_mod
 use, intrinsic :: ISO_C_BINDING
 use fsundials_core_mod
 implicit none
 private

 ! DECLARATION CONSTRUCTS
 public :: FN_VMake_MPIManyVector
 public :: FN_VNew_MPIManyVector
 public :: FN_VGetSubvector_MPIManyVector
 public :: FN_VSetSubvectorArrayPointer_MPIManyVector
 public :: FN_VGetNumSubvectors_MPIManyVector
 public :: FN_VGetSubvectorLocalLength_MPIManyVector
 public :: FN_VEnableFusedOps_MPIManyVector
 public :: FN_VEnableLinearCombination_MPIManyVector
 public :: FN_VEnableScaleAddMulti_MPIManyVector
 public :: FN_VEnableDotProdMulti_MPIManyVector
 public :: FN_VEnableLinearSumVectorArray_MPIManyVector
 public :: FN_VEnableScaleVectorArray_MPIManyVector
 public :: FN_VEnableConstVectorArray_MPIManyVector
 public :: FN_VEnableWrmsNormVectorArray_MPIManyVector
 public :: FN_VEnableWrmsNormMaskVectorArray_MPIManyVector
 public :: FN_VEnableDotProdMultiLocal_MPIManyVector

 public :: FN_VGetSubvectorArrayPointer_MPIManyVector


! WRAPPER DECLARATIONS
interface
function swigc_FN_VMake_MPIManyVector(farg1, farg2, farg3, farg4) &
bind(C, name="_wrap_FN_VMake_MPIManyVector") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: farg1
integer(C_INT64_T), intent(in) :: farg2
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
type(C_PTR) :: fresult
end function

function swigc_FN_VNew_MPIManyVector(farg1, farg2, farg3) &
bind(C, name="_wrap_FN_VNew_MPIManyVector") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T), intent(in) :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
type(C_PTR) :: fresult
end function

function swigc_FN_VGetSubvector_MPIManyVector(farg1, farg2) &
bind(C, name="_wrap_FN_VGetSubvector_MPIManyVector") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT64_T), intent(in) :: farg2
type(C_PTR) :: fresult
end function

function swigc_FN_VSetSubvectorArrayPointer_MPIManyVector(farg1, farg2, farg3) &
bind(C, name="_wrap_FN_VSetSubvectorArrayPointer_MPIManyVector") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
integer(C_INT64_T), intent(in) :: farg3
integer(C_INT) :: fresult
end function

function swigc_FN_VGetNumSubvectors_MPIManyVector(farg1) &
bind(C, name="_wrap_FN_VGetNumSubvectors_MPIManyVector") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT64_T) :: fresult
end function

function swigc_FN_VGetSubvectorLocalLength_MPIManyVector(farg1, farg2) &
bind(C, name="_wrap_FN_VGetSubvectorLocalLength_MPIManyVector") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT64_T), intent(in) :: farg2
integer(C_INT64_T) :: fresult
end function

function swigc_FN_VEnableFusedOps_MPIManyVector(farg1, farg2) &
bind(C, name="_wrap_FN_VEnableFusedOps_MPIManyVector") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FN_VEnableLinearCombination_MPIManyVector(farg1, farg2) &
bind(C, name="_wrap_FN_VEnableLinearCombination_MPIManyVector") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FN_VEnableScaleAddMulti_MPIManyVector(farg1, farg2) &
bind(C, name="_wrap_FN_VEnableScaleAddMulti_MPIManyVector") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FN_VEnableDotProdMulti_MPIManyVector(farg1, farg2) &
bind(C, name="_wrap_FN_VEnableDotProdMulti_MPIManyVector") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FN_VEnableLinearSumVectorArray_MPIManyVector(farg1, farg2) &
bind(C, name="_wrap_FN_VEnableLinearSumVectorArray_MPIManyVector") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FN_VEnableScaleVectorArray_MPIManyVector(farg1, farg2) &
bind(C, name="_wrap_FN_VEnableScaleVectorArray_MPIManyVector") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FN_VEnableConstVectorArray_MPIManyVector(farg1, farg2) &
bind(C, name="_wrap_FN_VEnableConstVectorArray_MPIManyVector") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FN_VEnableWrmsNormVectorArray_MPIManyVector(farg1, farg2) &
bind(C, name="_wrap_FN_VEnableWrmsNormVectorArray_MPIManyVector") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FN_VEnableWrmsNormMaskVectorArray_MPIManyVector(farg1, farg2) &
bind(C, name="_wrap_FN_VEnableWrmsNormMaskVectorArray_MPIManyVector") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FN_VEnableDotProdMultiLocal_MPIManyVector(farg1, farg2) &
bind(C, name="_wrap_FN_VEnableDotProdMultiLocal_MPIManyVector") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function


function swigc_FN_VGetSubvectorArrayPointer_MPIManyVector(farg1, farg2) &
bind(C, name="_wrap_FN_VGetSubvectorArrayPointer_MPIManyVector") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
#ifdef SUNDIALS_INT32_T
integer(C_INT32_T), intent(in) :: farg2
#else
integer(C_INT64_T), intent(in) :: farg2
#endif
type(C_PTR) :: fresult
end function

end interface


contains
 ! MODULE SUBPROGRAMS
function FN_VMake_MPIManyVector(comm, num_subvectors, vec_array_1d, sunctx) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(N_Vector), pointer :: swig_result
integer :: comm
integer(C_INT64_T), intent(in) :: num_subvectors
type(C_PTR) :: vec_array_1d
type(C_PTR) :: sunctx
type(C_PTR) :: fresult 
integer(C_INT) :: farg1 
integer(C_INT64_T) :: farg2 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 

farg1 = int(comm, C_INT)
farg2 = num_subvectors
farg3 = vec_array_1d
farg4 = sunctx
fresult = swigc_FN_VMake_MPIManyVector(farg1, farg2, farg3, farg4)
call c_f_pointer(fresult, swig_result)
end function

function FN_VNew_MPIManyVector(num_subvectors, vec_array_1d, sunctx) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(N_Vector), pointer :: swig_result
integer(C_INT64_T), intent(in) :: num_subvectors
type(C_PTR) :: vec_array_1d
type(C_PTR) :: sunctx
type(C_PTR) :: fresult 
integer(C_INT64_T) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = num_subvectors
farg2 = vec_array_1d
farg3 = sunctx
fresult = swigc_FN_VNew_MPIManyVector(farg1, farg2, farg3)
call c_f_pointer(fresult, swig_result)
end function

function FN_VGetSubvector_MPIManyVector(v, vec_num) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(N_Vector), pointer :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT64_T), intent(in) :: vec_num
type(C_PTR) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT64_T) :: farg2 

farg1 = c_loc(v)
farg2 = vec_num
fresult = swigc_FN_VGetSubvector_MPIManyVector(farg1, farg2)
call c_f_pointer(fresult, swig_result)
end function

function FN_VSetSubvectorArrayPointer_MPIManyVector(v_data_1d, v, vec_num) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
real(C_DOUBLE), dimension(*), target, intent(inout) :: v_data_1d
type(N_Vector), target, intent(inout) :: v
integer(C_INT64_T), intent(in) :: vec_num
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
integer(C_INT64_T) :: farg3 

farg1 = c_loc(v_data_1d(1))
farg2 = c_loc(v)
farg3 = vec_num
fresult = swigc_FN_VSetSubvectorArrayPointer_MPIManyVector(farg1, farg2, farg3)
swig_result = fresult
end function

function FN_VGetNumSubvectors_MPIManyVector(v) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT64_T) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(v)
fresult = swigc_FN_VGetNumSubvectors_MPIManyVector(farg1)
swig_result = fresult
end function

function FN_VGetSubvectorLocalLength_MPIManyVector(v, vec_num) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT64_T), intent(in) :: vec_num
integer(C_INT64_T) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT64_T) :: farg2 

farg1 = c_loc(v)
farg2 = vec_num
fresult = swigc_FN_VGetSubvectorLocalLength_MPIManyVector(farg1, farg2)
swig_result = fresult
end function

function FN_VEnableFusedOps_MPIManyVector(v, tf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT), intent(in) :: tf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(v)
farg2 = tf
fresult = swigc_FN_VEnableFusedOps_MPIManyVector(farg1, farg2)
swig_result = fresult
end function

function FN_VEnableLinearCombination_MPIManyVector(v, tf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT), intent(in) :: tf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(v)
farg2 = tf
fresult = swigc_FN_VEnableLinearCombination_MPIManyVector(farg1, farg2)
swig_result = fresult
end function

function FN_VEnableScaleAddMulti_MPIManyVector(v, tf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT), intent(in) :: tf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(v)
farg2 = tf
fresult = swigc_FN_VEnableScaleAddMulti_MPIManyVector(farg1, farg2)
swig_result = fresult
end function

function FN_VEnableDotProdMulti_MPIManyVector(v, tf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT), intent(in) :: tf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(v)
farg2 = tf
fresult = swigc_FN_VEnableDotProdMulti_MPIManyVector(farg1, farg2)
swig_result = fresult
end function

function FN_VEnableLinearSumVectorArray_MPIManyVector(v, tf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT), intent(in) :: tf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(v)
farg2 = tf
fresult = swigc_FN_VEnableLinearSumVectorArray_MPIManyVector(farg1, farg2)
swig_result = fresult
end function

function FN_VEnableScaleVectorArray_MPIManyVector(v, tf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT), intent(in) :: tf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(v)
farg2 = tf
fresult = swigc_FN_VEnableScaleVectorArray_MPIManyVector(farg1, farg2)
swig_result = fresult
end function

function FN_VEnableConstVectorArray_MPIManyVector(v, tf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT), intent(in) :: tf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(v)
farg2 = tf
fresult = swigc_FN_VEnableConstVectorArray_MPIManyVector(farg1, farg2)
swig_result = fresult
end function

function FN_VEnableWrmsNormVectorArray_MPIManyVector(v, tf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT), intent(in) :: tf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(v)
farg2 = tf
fresult = swigc_FN_VEnableWrmsNormVectorArray_MPIManyVector(farg1, farg2)
swig_result = fresult
end function

function FN_VEnableWrmsNormMaskVectorArray_MPIManyVector(v, tf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT), intent(in) :: tf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(v)
farg2 = tf
fresult = swigc_FN_VEnableWrmsNormMaskVectorArray_MPIManyVector(farg1, farg2)
swig_result = fresult
end function

function FN_VEnableDotProdMultiLocal_MPIManyVector(v, tf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT), intent(in) :: tf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(v)
farg2 = tf
fresult = swigc_FN_VEnableDotProdMultiLocal_MPIManyVector(farg1, farg2)
swig_result = fresult
end function


function FN_VGetSubvectorArrayPointer_MPIManyVector(v, vec_num) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(:), pointer :: swig_result
type(N_Vector), target, intent(inout) :: v
#ifdef SUNDIALS_INT32_T
integer(C_INT32_T), intent(in) :: vec_num
#else
integer(C_INT64_T), intent(in) :: vec_num
#endif
type(C_PTR) :: fresult
type(C_PTR) :: farg1
#ifdef SUNDIALS_INT32_T
integer(C_INT32_T) :: farg2
#else
integer(C_INT64_T) :: farg2
#endif

farg1 = c_loc(v)
farg2 = vec_num
fresult = swigc_FN_VGetSubvectorArrayPointer_MPIManyVector(farg1, farg2)
call c_f_pointer(fresult, swig_result, [FN_VGetSubvectorLocalLength_MPIManyVector(v, vec_num)])
end function


end module
