#!/bin/bash

methods=(
  ARKODE_SYMPLECTIC_EULER_1_1
  ARKODE_SYMPLECTIC_LEAPFROG_2_2
  ARKODE_SYMPLECTIC_PSEUDO_LEAPFROG_2_2
  ARKODE_SYMPLECTIC_MCLACHLAN_2_2
  ARKODE_SYMPLECTIC_RUTH_3_3
  ARKODE_SYMPLECTIC_MCLACHLAN_3_3
  ARKODE_SYMPLECTIC_CANDY_ROZMUS_4_4
  ARKODE_SYMPLECTIC_MCLACHLAN_4_4
  ARKODE_SYMPLECTIC_MCLACHLAN_5_6
  ARKODE_SYMPLECTIC_YOSHIDA_6_8
  ARKODE_SYMPLECTIC_MCLACHLAN_8_16
  ARKODE_SYMPLECTIC_SOFRONIOU_10_36
)
for method in ${methods[@]}; 
do 
  ./ark_kepler --stepper SPRK --step-mode fixed --method $method --tf 50 --check-order --nout 1
done
