/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/* ---------------------------------------------------------------
 * Programmer(s): Auto-generated by swig.
 * ---------------------------------------------------------------
 * SUNDIALS Copyright Start
 * Copyright (c) 2025, Lawrence Livermore National Security,
 * University of Maryland Baltimore County, and the SUNDIALS contributors.
 * Copyright (c) 2013-2025, Lawrence Livermore National Security
 * and Southern Methodist University.
 * Copyright (c) 2002-2013, Lawrence Livermore National Security.
 * All rights reserved.
 *
 * See the top-level LICENSE and NOTICE files for details.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 * SUNDIALS Copyright End
 * -------------------------------------------------------------*/

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* qualifier for exported *const* global data variables*/
#ifndef SWIGEXTERN
# ifdef __cplusplus
#   define SWIGEXTERN extern
# else
#   define SWIGEXTERN
# endif
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

/*  Errors in SWIG */
#define  SWIG_UnknownError    	   -1
#define  SWIG_IOError        	   -2
#define  SWIG_RuntimeError   	   -3
#define  SWIG_IndexError     	   -4
#define  SWIG_TypeError      	   -5
#define  SWIG_DivisionByZero 	   -6
#define  SWIG_OverflowError  	   -7
#define  SWIG_SyntaxError    	   -8
#define  SWIG_ValueError     	   -9
#define  SWIG_SystemError    	   -10
#define  SWIG_AttributeError 	   -11
#define  SWIG_MemoryError    	   -12
#define  SWIG_NullReferenceError   -13




#include <assert.h>
#define SWIG_exception_impl(DECL, CODE, MSG, RETURNNULL) \
 { printf("In " DECL ": " MSG); assert(0); RETURNNULL; }


enum {
    SWIG_MEM_OWN = 0x01,
    SWIG_MEM_RVALUE = 0x02,
    SWIG_MEM_CONST = 0x04
};


#define SWIG_check_mutable(SWIG_CLASS_WRAPPER, TYPENAME, FNAME, FUNCNAME, RETURNNULL) \
    if ((SWIG_CLASS_WRAPPER).cmemflags & SWIG_MEM_CONST) { \
        SWIG_exception_impl(FUNCNAME, SWIG_TypeError, \
            "Cannot pass const " TYPENAME " (class " FNAME ") " \
            "as a mutable reference", \
            RETURNNULL); \
    }


#define SWIG_check_nonnull(SWIG_CLASS_WRAPPER, TYPENAME, FNAME, FUNCNAME, RETURNNULL) \
  if (!(SWIG_CLASS_WRAPPER).cptr) { \
    SWIG_exception_impl(FUNCNAME, SWIG_TypeError, \
                        "Cannot pass null " TYPENAME " (class " FNAME ") " \
                        "as a reference", RETURNNULL); \
  }


#define SWIG_check_mutable_nonnull(SWIG_CLASS_WRAPPER, TYPENAME, FNAME, FUNCNAME, RETURNNULL) \
    SWIG_check_nonnull(SWIG_CLASS_WRAPPER, TYPENAME, FNAME, FUNCNAME, RETURNNULL); \
    SWIG_check_mutable(SWIG_CLASS_WRAPPER, TYPENAME, FNAME, FUNCNAME, RETURNNULL);


#include <stdio.h>
#if defined(_MSC_VER) || defined(__BORLANDC__) || defined(_WATCOM)
# ifndef snprintf
#  define snprintf _snprintf
# endif
#endif


/* Support for the `contract` feature.
 *
 * Note that RETURNNULL is first because it's inserted via a 'Replaceall' in
 * the fortran.cxx file.
 */
#define SWIG_contract_assert(RETURNNULL, EXPR, MSG) \
 if (!(EXPR)) { SWIG_exception_impl("$decl", SWIG_ValueError, MSG, RETURNNULL); } 


#define SWIGVERSION 0x040000 
#define SWIG_VERSION SWIGVERSION


#define SWIG_as_voidptr(a) (void *)((const void *)(a)) 
#define SWIG_as_voidptrptr(a) ((void)SWIG_as_voidptr(*a),(void**)(a)) 


#include "sundials/sundials_domeigestimator.h"


#include "sundomeigest/sundomeigest_arnoldi.h"


typedef struct {
    void* cptr;
    int cmemflags;
} SwigClassWrapper;


SWIGINTERN SwigClassWrapper SwigClassWrapper_uninitialized() {
    SwigClassWrapper result;
    result.cptr = NULL;
    result.cmemflags = 0;
    return result;
}


#include <stdlib.h>
#ifdef _MSC_VER
# ifndef strtoull
#  define strtoull _strtoui64
# endif
# ifndef strtoll
#  define strtoll _strtoi64
# endif
#endif


#include <string.h>


SWIGINTERN void SWIG_assign(SwigClassWrapper* self, SwigClassWrapper other) {
  if (self->cptr == NULL) {
    /* LHS is unassigned */
    if (other.cmemflags & SWIG_MEM_RVALUE) {
      /* Capture pointer from RHS, clear 'moving' flag */
      self->cptr = other.cptr;
      self->cmemflags = other.cmemflags & (~SWIG_MEM_RVALUE);
    } else {
      /* Become a reference to the other object */
      self->cptr = other.cptr;
      self->cmemflags = other.cmemflags & (~SWIG_MEM_OWN);
    }
  } else if (other.cptr == NULL) {
    /* Replace LHS with a null pointer */
    free(self->cptr);
    *self = SwigClassWrapper_uninitialized();
  } else {
    if (self->cmemflags & SWIG_MEM_OWN) {
      free(self->cptr);
    }
    self->cptr = other.cptr;
    if (other.cmemflags & SWIG_MEM_RVALUE) {
      /* Capture RHS */
      self->cmemflags = other.cmemflags & ~SWIG_MEM_RVALUE;
    } else {
      /* Point to RHS */
      self->cmemflags = other.cmemflags & ~SWIG_MEM_OWN;
    }
  }
}

SWIGEXPORT void _wrap_SUNDomEigEstimatorContent_Arnoldi__ATimes_set(SwigClassWrapper const *farg1, SUNATimesFn farg2) {
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  SUNATimesFn arg2 = (SUNATimesFn) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::ATimes", return );
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  arg2 = (SUNATimesFn)(farg2);
  if (arg1) (arg1)->ATimes = arg2;
}


SWIGEXPORT SUNATimesFn _wrap_SUNDomEigEstimatorContent_Arnoldi__ATimes_get(SwigClassWrapper const *farg1) {
  SUNATimesFn fresult ;
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  SUNATimesFn result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::ATimes", return 0);
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  result = (SUNATimesFn) ((arg1)->ATimes);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap_SUNDomEigEstimatorContent_Arnoldi__ATdata_set(SwigClassWrapper const *farg1, void *farg2) {
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  void *arg2 = (void *) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::ATdata", return );
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  arg2 = (void *)(farg2);
  if (arg1) (arg1)->ATdata = arg2;
}


SWIGEXPORT void * _wrap_SUNDomEigEstimatorContent_Arnoldi__ATdata_get(SwigClassWrapper const *farg1) {
  void * fresult ;
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  void *result = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::ATdata", return 0);
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  result = (void *) ((arg1)->ATdata);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap_SUNDomEigEstimatorContent_Arnoldi__V_set(SwigClassWrapper const *farg1, void *farg2) {
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  N_Vector *arg2 = (N_Vector *) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::V", return );
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  arg2 = (N_Vector *)(farg2);
  if (arg1) (arg1)->V = arg2;
}


SWIGEXPORT void * _wrap_SUNDomEigEstimatorContent_Arnoldi__V_get(SwigClassWrapper const *farg1) {
  void * fresult ;
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  N_Vector *result = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::V", return 0);
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  result = (N_Vector *) ((arg1)->V);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap_SUNDomEigEstimatorContent_Arnoldi__q_set(SwigClassWrapper const *farg1, N_Vector farg2) {
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  N_Vector arg2 = (N_Vector) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::q", return );
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  arg2 = (N_Vector)(farg2);
  if (arg1) (arg1)->q = arg2;
}


SWIGEXPORT N_Vector _wrap_SUNDomEigEstimatorContent_Arnoldi__q_get(SwigClassWrapper const *farg1) {
  N_Vector fresult ;
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  N_Vector result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::q", return 0);
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  result = (N_Vector) ((arg1)->q);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap_SUNDomEigEstimatorContent_Arnoldi__kry_dim_set(SwigClassWrapper const *farg1, int const *farg2) {
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  int arg2 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::kry_dim", return );
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  arg2 = (int)(*farg2);
  if (arg1) (arg1)->kry_dim = arg2;
}


SWIGEXPORT int _wrap_SUNDomEigEstimatorContent_Arnoldi__kry_dim_get(SwigClassWrapper const *farg1) {
  int fresult ;
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  int result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::kry_dim", return 0);
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  result = (int) ((arg1)->kry_dim);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SUNDomEigEstimatorContent_Arnoldi__num_warmups_set(SwigClassWrapper const *farg1, int const *farg2) {
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  int arg2 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::num_warmups", return );
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  arg2 = (int)(*farg2);
  if (arg1) (arg1)->num_warmups = arg2;
}


SWIGEXPORT int _wrap_SUNDomEigEstimatorContent_Arnoldi__num_warmups_get(SwigClassWrapper const *farg1) {
  int fresult ;
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  int result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::num_warmups", return 0);
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  result = (int) ((arg1)->num_warmups);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SUNDomEigEstimatorContent_Arnoldi__num_iters_set(SwigClassWrapper const *farg1, long const *farg2) {
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  long arg2 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::num_iters", return );
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  arg2 = (long)(*farg2);
  if (arg1) (arg1)->num_iters = arg2;
}


SWIGEXPORT long _wrap_SUNDomEigEstimatorContent_Arnoldi__num_iters_get(SwigClassWrapper const *farg1) {
  long fresult ;
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  long result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::num_iters", return 0);
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  result = (long) ((arg1)->num_iters);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SUNDomEigEstimatorContent_Arnoldi__num_ATimes_set(SwigClassWrapper const *farg1, long const *farg2) {
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  long arg2 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::num_ATimes", return );
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  arg2 = (long)(*farg2);
  if (arg1) (arg1)->num_ATimes = arg2;
}


SWIGEXPORT long _wrap_SUNDomEigEstimatorContent_Arnoldi__num_ATimes_get(SwigClassWrapper const *farg1) {
  long fresult ;
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  long result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::num_ATimes", return 0);
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  result = (long) ((arg1)->num_ATimes);
  fresult = (long)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SUNDomEigEstimatorContent_Arnoldi__LAPACK_A_set(SwigClassWrapper const *farg1, double *farg2) {
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  sunrealtype *arg2 = (sunrealtype *) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::LAPACK_A", return );
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  arg2 = (sunrealtype *)(farg2);
  if (arg1) (arg1)->LAPACK_A = arg2;
}


SWIGEXPORT double * _wrap_SUNDomEigEstimatorContent_Arnoldi__LAPACK_A_get(SwigClassWrapper const *farg1) {
  double * fresult ;
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  sunrealtype *result = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::LAPACK_A", return 0);
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  result = (sunrealtype *) ((arg1)->LAPACK_A);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap_SUNDomEigEstimatorContent_Arnoldi__LAPACK_wr_set(SwigClassWrapper const *farg1, double *farg2) {
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  sunrealtype *arg2 = (sunrealtype *) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::LAPACK_wr", return );
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  arg2 = (sunrealtype *)(farg2);
  if (arg1) (arg1)->LAPACK_wr = arg2;
}


SWIGEXPORT double * _wrap_SUNDomEigEstimatorContent_Arnoldi__LAPACK_wr_get(SwigClassWrapper const *farg1) {
  double * fresult ;
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  sunrealtype *result = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::LAPACK_wr", return 0);
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  result = (sunrealtype *) ((arg1)->LAPACK_wr);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap_SUNDomEigEstimatorContent_Arnoldi__LAPACK_wi_set(SwigClassWrapper const *farg1, double *farg2) {
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  sunrealtype *arg2 = (sunrealtype *) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::LAPACK_wi", return );
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  arg2 = (sunrealtype *)(farg2);
  if (arg1) (arg1)->LAPACK_wi = arg2;
}


SWIGEXPORT double * _wrap_SUNDomEigEstimatorContent_Arnoldi__LAPACK_wi_get(SwigClassWrapper const *farg1) {
  double * fresult ;
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  sunrealtype *result = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::LAPACK_wi", return 0);
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  result = (sunrealtype *) ((arg1)->LAPACK_wi);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap_SUNDomEigEstimatorContent_Arnoldi__LAPACK_work_set(SwigClassWrapper const *farg1, double *farg2) {
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  sunrealtype *arg2 = (sunrealtype *) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::LAPACK_work", return );
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  arg2 = (sunrealtype *)(farg2);
  if (arg1) (arg1)->LAPACK_work = arg2;
}


SWIGEXPORT double * _wrap_SUNDomEigEstimatorContent_Arnoldi__LAPACK_work_get(SwigClassWrapper const *farg1) {
  double * fresult ;
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  sunrealtype *result = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::LAPACK_work", return 0);
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  result = (sunrealtype *) ((arg1)->LAPACK_work);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap_SUNDomEigEstimatorContent_Arnoldi__LAPACK_lwork_set(SwigClassWrapper const *farg1, int64_t const *farg2) {
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  sunindextype arg2 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::LAPACK_lwork", return );
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  arg2 = (sunindextype)(*farg2);
  if (arg1) (arg1)->LAPACK_lwork = arg2;
}


SWIGEXPORT int64_t _wrap_SUNDomEigEstimatorContent_Arnoldi__LAPACK_lwork_get(SwigClassWrapper const *farg1) {
  int64_t fresult ;
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  sunindextype result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::LAPACK_lwork", return 0);
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  result =  ((arg1)->LAPACK_lwork);
  fresult = (sunindextype)(result);
  return fresult;
}


SWIGEXPORT void _wrap_SUNDomEigEstimatorContent_Arnoldi__LAPACK_arr_set(SwigClassWrapper const *farg1, void *farg2) {
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  sunrealtype **arg2 = (sunrealtype **) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::LAPACK_arr", return );
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  arg2 = (sunrealtype **)(farg2);
  if (arg1) (arg1)->LAPACK_arr = arg2;
}


SWIGEXPORT void * _wrap_SUNDomEigEstimatorContent_Arnoldi__LAPACK_arr_get(SwigClassWrapper const *farg1) {
  void * fresult ;
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  sunrealtype **result = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::LAPACK_arr", return 0);
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  result = (sunrealtype **) ((arg1)->LAPACK_arr);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap_SUNDomEigEstimatorContent_Arnoldi__Hes_set(SwigClassWrapper const *farg1, void *farg2) {
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  sunrealtype **arg2 = (sunrealtype **) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::Hes", return );
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  arg2 = (sunrealtype **)(farg2);
  if (arg1) (arg1)->Hes = arg2;
}


SWIGEXPORT void * _wrap_SUNDomEigEstimatorContent_Arnoldi__Hes_get(SwigClassWrapper const *farg1) {
  void * fresult ;
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  sunrealtype **result = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::Hes", return 0);
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  result = (sunrealtype **) ((arg1)->Hes);
  fresult = result;
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new_SUNDomEigEstimatorContent_Arnoldi_() {
  SwigClassWrapper fresult ;
  struct SUNDomEigEstimatorContent_Arnoldi_ *result = 0 ;
  
  result = (struct SUNDomEigEstimatorContent_Arnoldi_ *)calloc(1, sizeof(struct SUNDomEigEstimatorContent_Arnoldi_));
  fresult.cptr = result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete_SUNDomEigEstimatorContent_Arnoldi_(SwigClassWrapper *farg1) {
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  
  SWIG_check_mutable(*farg1, "struct SUNDomEigEstimatorContent_Arnoldi_ *", "SUNDomEigEstimatorContent_Arnoldi_", "SUNDomEigEstimatorContent_Arnoldi_::~SUNDomEigEstimatorContent_Arnoldi_()", return );
  arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *)(farg1->cptr);
  free((char *) arg1);
}


SWIGEXPORT void _wrap_SUNDomEigEstimatorContent_Arnoldi__op_assign__(SwigClassWrapper *farg1, SwigClassWrapper const *farg2) {
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg1 = (struct SUNDomEigEstimatorContent_Arnoldi_ *) 0 ;
  struct SUNDomEigEstimatorContent_Arnoldi_ *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}


SWIGEXPORT SUNDomEigEstimator _wrap_FSUNDomEigEstimator_Arnoldi(N_Vector farg1, int const *farg2, void *farg3) {
  SUNDomEigEstimator fresult ;
  N_Vector arg1 = (N_Vector) 0 ;
  int arg2 ;
  SUNContext arg3 = (SUNContext) 0 ;
  SUNDomEigEstimator result;
  
  arg1 = (N_Vector)(farg1);
  arg2 = (int)(*farg2);
  arg3 = (SUNContext)(farg3);
  result = (SUNDomEigEstimator)SUNDomEigEstimator_Arnoldi(arg1,arg2,arg3);
  fresult = result;
  return fresult;
}


SWIGEXPORT int _wrap_FSUNDomEigEstimator_SetATimes_Arnoldi(SUNDomEigEstimator farg1, void *farg2, SUNATimesFn farg3) {
  int fresult ;
  SUNDomEigEstimator arg1 = (SUNDomEigEstimator) 0 ;
  void *arg2 = (void *) 0 ;
  SUNATimesFn arg3 = (SUNATimesFn) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNDomEigEstimator)(farg1);
  arg2 = (void *)(farg2);
  arg3 = (SUNATimesFn)(farg3);
  result = (SUNErrCode)SUNDomEigEstimator_SetATimes_Arnoldi(arg1,arg2,arg3);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNDomEigEstimator_SetNumPreprocessIters_Arnoldi(SUNDomEigEstimator farg1, int const *farg2) {
  int fresult ;
  SUNDomEigEstimator arg1 = (SUNDomEigEstimator) 0 ;
  int arg2 ;
  SUNErrCode result;
  
  arg1 = (SUNDomEigEstimator)(farg1);
  arg2 = (int)(*farg2);
  result = (SUNErrCode)SUNDomEigEstimator_SetNumPreprocessIters_Arnoldi(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNDomEigEstimator_SetInitialGuess_Arnoldi(SUNDomEigEstimator farg1, N_Vector farg2) {
  int fresult ;
  SUNDomEigEstimator arg1 = (SUNDomEigEstimator) 0 ;
  N_Vector arg2 = (N_Vector) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNDomEigEstimator)(farg1);
  arg2 = (N_Vector)(farg2);
  result = (SUNErrCode)SUNDomEigEstimator_SetInitialGuess_Arnoldi(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNDomEigEstimator_Initialize_Arnoldi(SUNDomEigEstimator farg1) {
  int fresult ;
  SUNDomEigEstimator arg1 = (SUNDomEigEstimator) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNDomEigEstimator)(farg1);
  result = (SUNErrCode)SUNDomEigEstimator_Initialize_Arnoldi(arg1);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNDomEigEstimator_Estimate_Arnoldi(SUNDomEigEstimator farg1, double *farg2, double *farg3) {
  int fresult ;
  SUNDomEigEstimator arg1 = (SUNDomEigEstimator) 0 ;
  sunrealtype *arg2 = (sunrealtype *) 0 ;
  sunrealtype *arg3 = (sunrealtype *) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNDomEigEstimator)(farg1);
  arg2 = (sunrealtype *)(farg2);
  arg3 = (sunrealtype *)(farg3);
  result = (SUNErrCode)SUNDomEigEstimator_Estimate_Arnoldi(arg1,arg2,arg3);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNDomEigEstimator_GetNumIters_Arnoldi(SUNDomEigEstimator farg1, long *farg2) {
  int fresult ;
  SUNDomEigEstimator arg1 = (SUNDomEigEstimator) 0 ;
  long *arg2 = (long *) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNDomEigEstimator)(farg1);
  arg2 = (long *)(farg2);
  result = (SUNErrCode)SUNDomEigEstimator_GetNumIters_Arnoldi(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNDomEigEstimator_GetNumATimesCalls_Arnoldi(SUNDomEigEstimator farg1, long *farg2) {
  int fresult ;
  SUNDomEigEstimator arg1 = (SUNDomEigEstimator) 0 ;
  long *arg2 = (long *) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNDomEigEstimator)(farg1);
  arg2 = (long *)(farg2);
  result = (SUNErrCode)SUNDomEigEstimator_GetNumATimesCalls_Arnoldi(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNDomEigEstimator_Write_Arnoldi(SUNDomEigEstimator farg1, void *farg2) {
  int fresult ;
  SUNDomEigEstimator arg1 = (SUNDomEigEstimator) 0 ;
  FILE *arg2 = (FILE *) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNDomEigEstimator)(farg1);
  arg2 = (FILE *)(farg2);
  result = (SUNErrCode)SUNDomEigEstimator_Write_Arnoldi(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNDomEigEstimator_Destroy_Arnoldi(void *farg1) {
  int fresult ;
  SUNDomEigEstimator *arg1 = (SUNDomEigEstimator *) 0 ;
  SUNErrCode result;
  
  arg1 = (SUNDomEigEstimator *)(farg1);
  result = (SUNErrCode)SUNDomEigEstimator_Destroy_Arnoldi(arg1);
  fresult = (SUNErrCode)(result);
  return fresult;
}



