! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! ---------------------------------------------------------------
! Programmer(s): Auto-generated by swig.
! ---------------------------------------------------------------
! SUNDIALS Copyright Start
! Copyright (c) 2025-2026, Lawrence Livermore National Security,
! University of Maryland Baltimore County, and the SUNDIALS contributors.
! Copyright (c) 2013-2025, Lawrence Livermore National Security
! and Southern Methodist University.
! Copyright (c) 2002-2013, Lawrence Livermore National Security.
! All rights reserved.
!
! See the top-level LICENSE and NOTICE files for details.
!
! SPDX-License-Identifier: BSD-3-Clause
! SUNDIALS Copyright End
! ---------------------------------------------------------------

module fsunlinsol_dense_mod
 use, intrinsic :: ISO_C_BINDING
 use fsundials_core_mod
 implicit none
 private

 ! DECLARATION CONSTRUCTS

 integer, parameter :: swig_cmem_own_bit = 0
 integer, parameter :: swig_cmem_rvalue_bit = 1
 integer, parameter :: swig_cmem_const_bit = 2
 type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: cptr = C_NULL_PTR
  integer(C_INT), public :: cmemflags = 0
 end type
 ! struct struct SUNLinearSolverContent_Dense_
 type, public :: SUNLinearSolverContent_Dense_
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_N => swigf_SUNLinearSolverContent_Dense__N_set
  procedure :: get_N => swigf_SUNLinearSolverContent_Dense__N_get
  procedure :: set_pivots => swigf_SUNLinearSolverContent_Dense__pivots_set
  procedure :: get_pivots => swigf_SUNLinearSolverContent_Dense__pivots_get
  procedure :: set_last_flag => swigf_SUNLinearSolverContent_Dense__last_flag_set
  procedure :: get_last_flag => swigf_SUNLinearSolverContent_Dense__last_flag_get
  procedure :: release => swigf_release_SUNLinearSolverContent_Dense_
  procedure, private :: swigf_SUNLinearSolverContent_Dense__op_assign__
  generic :: assignment(=) => swigf_SUNLinearSolverContent_Dense__op_assign__
 end type SUNLinearSolverContent_Dense_
 interface SUNLinearSolverContent_Dense_
  module procedure swigf_create_SUNLinearSolverContent_Dense_
 end interface
 public :: FSUNLinSol_Dense

! WRAPPER DECLARATIONS
interface
subroutine swigc_SUNLinearSolverContent_Dense__N_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_Dense__N_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT32_T), intent(in) :: farg2
end subroutine

function swigc_SUNLinearSolverContent_Dense__N_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_Dense__N_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT32_T) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_Dense__pivots_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_Dense__pivots_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR), value :: farg2
end subroutine

function swigc_SUNLinearSolverContent_Dense__pivots_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_Dense__pivots_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR) :: fresult
end function

subroutine swigc_SUNLinearSolverContent_Dense__last_flag_set(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_Dense__last_flag_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT32_T), intent(in) :: farg2
end subroutine

function swigc_SUNLinearSolverContent_Dense__last_flag_get(farg1) &
bind(C, name="_wrap_SUNLinearSolverContent_Dense__last_flag_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT32_T) :: fresult
end function

function swigc_new_SUNLinearSolverContent_Dense_() &
bind(C, name="_wrap_new_SUNLinearSolverContent_Dense_") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_SUNLinearSolverContent_Dense_(farg1) &
bind(C, name="_wrap_delete_SUNLinearSolverContent_Dense_")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_SUNLinearSolverContent_Dense__op_assign__(farg1, farg2) &
bind(C, name="_wrap_SUNLinearSolverContent_Dense__op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

function swigc_FSUNLinSol_Dense(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNLinSol_Dense") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
type(C_PTR), value :: farg3
type(SwigClassWrapper) :: fresult
end function

end interface


contains
 ! MODULE SUBPROGRAMS
subroutine swigf_SUNLinearSolverContent_Dense__N_set(self, n)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_Dense_), intent(in) :: self
integer(C_INT32_T), intent(in) :: n
type(SwigClassWrapper) :: farg1 
integer(C_INT32_T) :: farg2 

farg1 = self%swigdata
farg2 = n
call swigc_SUNLinearSolverContent_Dense__N_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_Dense__N_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T) :: swig_result
class(SUNLinearSolverContent_Dense_), intent(in) :: self
integer(C_INT32_T) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_Dense__N_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNLinearSolverContent_Dense__pivots_set(self, pivots)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_Dense_), intent(in) :: self
integer(C_INT32_T), dimension(*), target, intent(inout) :: pivots
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = self%swigdata
farg2 = c_loc(pivots(1))
call swigc_SUNLinearSolverContent_Dense__pivots_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_Dense__pivots_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T), dimension(:), pointer :: swig_result
class(SUNLinearSolverContent_Dense_), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_Dense__pivots_get(farg1)
call c_f_pointer(fresult, swig_result, [1])
end function

subroutine swigf_SUNLinearSolverContent_Dense__last_flag_set(self, last_flag)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_Dense_), intent(in) :: self
integer(C_INT32_T), intent(in) :: last_flag
type(SwigClassWrapper) :: farg1 
integer(C_INT32_T) :: farg2 

farg1 = self%swigdata
farg2 = last_flag
call swigc_SUNLinearSolverContent_Dense__last_flag_set(farg1, farg2)
end subroutine

function swigf_SUNLinearSolverContent_Dense__last_flag_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT32_T) :: swig_result
class(SUNLinearSolverContent_Dense_), intent(in) :: self
integer(C_INT32_T) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNLinearSolverContent_Dense__last_flag_get(farg1)
swig_result = fresult
end function

function swigf_create_SUNLinearSolverContent_Dense_() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(SUNLinearSolverContent_Dense_) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_SUNLinearSolverContent_Dense_()
self%swigdata = fresult
end function

subroutine swigf_release_SUNLinearSolverContent_Dense_(self)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_Dense_), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_SUNLinearSolverContent_Dense_(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_SUNLinearSolverContent_Dense__op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(SUNLinearSolverContent_Dense_), intent(inout) :: self
type(SUNLinearSolverContent_Dense_), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_SUNLinearSolverContent_Dense__op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

function FSUNLinSol_Dense(y, a, sunctx) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SUNLinearSolver_) :: swig_result
class(N_Vector_), intent(in) :: y
class(SUNMatrix_), intent(in) :: a
type(C_PTR) :: sunctx
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 
type(C_PTR) :: farg3 

farg1 = y%swigdata
farg2 = a%swigdata
farg3 = sunctx
fresult = swigc_FSUNLinSol_Dense(farg1, farg2, farg3)
swig_result%swigdata = fresult
end function


end module
