! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! ---------------------------------------------------------------
! Programmer(s): Auto-generated by swig.
! ---------------------------------------------------------------
! SUNDIALS Copyright Start
! Copyright (c) 2002-2023, Lawrence Livermore National Security
! and Southern Methodist University.
! All rights reserved.
!
! See the top-level LICENSE and NOTICE files for details.
!
! SPDX-License-Identifier: BSD-3-Clause
! SUNDIALS Copyright End
! ---------------------------------------------------------------

module fsuncontrol_expgus_mod
 use, intrinsic :: ISO_C_BINDING
 implicit none
 private

 ! DECLARATION CONSTRUCTS

 integer, parameter :: swig_cmem_own_bit = 0
 integer, parameter :: swig_cmem_rvalue_bit = 1
 integer, parameter :: swig_cmem_const_bit = 2
 type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: cptr = C_NULL_PTR
  integer(C_INT), public :: cmemflags = 0
 end type
 type, public :: SWIGTYPE_p_SUNContext
  type(SwigClassWrapper), public :: swigdata
 end type
 type, public :: SWIGTYPE_p_SUNControl
  type(SwigClassWrapper), public :: swigdata
 end type
 public :: FSUNControlExpGus
 type, public :: SWIGTYPE_p_sunbooleantype
  type(SwigClassWrapper), public :: swigdata
 end type
 type, public :: SWIGTYPE_p_realtype
  type(SwigClassWrapper), public :: swigdata
 end type
 public :: FSUNControlExpGus_SetParams
 type, public :: SWIGTYPE_p_SUNControl_ID
  type(SwigClassWrapper), public :: swigdata
 end type
 public :: FSUNControlGetID_ExpGus
 public :: FSUNControlEstimateStep_ExpGus
 public :: FSUNControlReset_ExpGus
 public :: FSUNControlSetDefaults_ExpGus
 public :: FSUNControlWrite_ExpGus
 public :: FSUNControlSetMethodOrder_ExpGus
 public :: FSUNControlSetEmbeddingOrder_ExpGus
 public :: FSUNControlSetErrorBias_ExpGus
 public :: FSUNControlUpdate_ExpGus
 public :: FSUNControlSpace_ExpGus

! WRAPPER DECLARATIONS
interface
function swigc_FSUNControlExpGus(farg1) &
bind(C, name="_wrap_FSUNControlExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_FSUNControlExpGus_SetParams(farg1, farg2, farg3, farg4) &
bind(C, name="_wrap_FSUNControlExpGus_SetParams") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
type(SwigClassWrapper) :: farg3
type(SwigClassWrapper) :: farg4
integer(C_INT) :: fresult
end function

function swigc_FSUNControlGetID_ExpGus(farg1) &
bind(C, name="_wrap_FSUNControlGetID_ExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_FSUNControlEstimateStep_ExpGus(farg1, farg2, farg3, farg4) &
bind(C, name="_wrap_FSUNControlEstimateStep_ExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
type(SwigClassWrapper) :: farg3
type(C_PTR), value :: farg4
integer(C_INT) :: fresult
end function

function swigc_FSUNControlReset_ExpGus(farg1) &
bind(C, name="_wrap_FSUNControlReset_ExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

function swigc_FSUNControlSetDefaults_ExpGus(farg1) &
bind(C, name="_wrap_FSUNControlSetDefaults_ExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

function swigc_FSUNControlWrite_ExpGus(farg1, farg2) &
bind(C, name="_wrap_FSUNControlWrite_ExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR), value :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNControlSetMethodOrder_ExpGus(farg1, farg2) &
bind(C, name="_wrap_FSUNControlSetMethodOrder_ExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNControlSetEmbeddingOrder_ExpGus(farg1, farg2) &
bind(C, name="_wrap_FSUNControlSetEmbeddingOrder_ExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNControlSetErrorBias_ExpGus(farg1, farg2) &
bind(C, name="_wrap_FSUNControlSetErrorBias_ExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNControlUpdate_ExpGus(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNControlUpdate_ExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
type(SwigClassWrapper) :: farg3
integer(C_INT) :: fresult
end function

function swigc_FSUNControlSpace_ExpGus(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNControlSpace_ExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
integer(C_INT) :: fresult
end function

end interface


contains
 ! MODULE SUBPROGRAMS
function FSUNControlExpGus(sunctx) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_SUNControl) :: swig_result
type(SWIGTYPE_p_SUNContext), intent(in) :: sunctx
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = sunctx%swigdata
fresult = swigc_FSUNControlExpGus(farg1)
swig_result%swigdata = fresult
end function

function FSUNControlExpGus_SetParams(c, pq, k1, k2) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SWIGTYPE_p_SUNControl), intent(in) :: c
type(SWIGTYPE_p_sunbooleantype), intent(in) :: pq
type(SWIGTYPE_p_realtype), intent(in) :: k1
type(SWIGTYPE_p_realtype), intent(in) :: k2
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 
type(SwigClassWrapper) :: farg3 
type(SwigClassWrapper) :: farg4 

farg1 = c%swigdata
farg2 = pq%swigdata
farg3 = k1%swigdata
farg4 = k2%swigdata
fresult = swigc_FSUNControlExpGus_SetParams(farg1, farg2, farg3, farg4)
swig_result = fresult
end function

function FSUNControlGetID_ExpGus(c) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_SUNControl_ID) :: swig_result
type(SWIGTYPE_p_SUNControl), intent(in) :: c
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = c%swigdata
fresult = swigc_FSUNControlGetID_ExpGus(farg1)
swig_result%swigdata = fresult
end function

function FSUNControlEstimateStep_ExpGus(c, h, dsm, hnew) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SWIGTYPE_p_SUNControl), intent(in) :: c
type(SWIGTYPE_p_realtype), intent(in) :: h
type(SWIGTYPE_p_realtype), intent(in) :: dsm
type(SWIGTYPE_p_realtype), dimension(*), target, intent(inout) :: hnew
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 
type(SwigClassWrapper) :: farg3 
type(C_PTR) :: farg4 

farg1 = c%swigdata
farg2 = h%swigdata
farg3 = dsm%swigdata
farg4 = c_loc(hnew(1))
fresult = swigc_FSUNControlEstimateStep_ExpGus(farg1, farg2, farg3, farg4)
swig_result = fresult
end function

function FSUNControlReset_ExpGus(c) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SWIGTYPE_p_SUNControl), intent(in) :: c
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = c%swigdata
fresult = swigc_FSUNControlReset_ExpGus(farg1)
swig_result = fresult
end function

function FSUNControlSetDefaults_ExpGus(c) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SWIGTYPE_p_SUNControl), intent(in) :: c
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = c%swigdata
fresult = swigc_FSUNControlSetDefaults_ExpGus(farg1)
swig_result = fresult
end function

function FSUNControlWrite_ExpGus(c, fptr) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SWIGTYPE_p_SUNControl), intent(in) :: c
type(C_PTR) :: fptr
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = c%swigdata
farg2 = fptr
fresult = swigc_FSUNControlWrite_ExpGus(farg1, farg2)
swig_result = fresult
end function

function FSUNControlSetMethodOrder_ExpGus(c, q) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SWIGTYPE_p_SUNControl), intent(in) :: c
integer(C_INT), intent(in) :: q
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = c%swigdata
farg2 = q
fresult = swigc_FSUNControlSetMethodOrder_ExpGus(farg1, farg2)
swig_result = fresult
end function

function FSUNControlSetEmbeddingOrder_ExpGus(c, p) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SWIGTYPE_p_SUNControl), intent(in) :: c
integer(C_INT), intent(in) :: p
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = c%swigdata
farg2 = p
fresult = swigc_FSUNControlSetEmbeddingOrder_ExpGus(farg1, farg2)
swig_result = fresult
end function

function FSUNControlSetErrorBias_ExpGus(c, bias) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SWIGTYPE_p_SUNControl), intent(in) :: c
type(SWIGTYPE_p_realtype), intent(in) :: bias
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = c%swigdata
farg2 = bias%swigdata
fresult = swigc_FSUNControlSetErrorBias_ExpGus(farg1, farg2)
swig_result = fresult
end function

function FSUNControlUpdate_ExpGus(c, h, dsm) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SWIGTYPE_p_SUNControl), intent(in) :: c
type(SWIGTYPE_p_realtype), intent(in) :: h
type(SWIGTYPE_p_realtype), intent(in) :: dsm
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 
type(SwigClassWrapper) :: farg3 

farg1 = c%swigdata
farg2 = h%swigdata
farg3 = dsm%swigdata
fresult = swigc_FSUNControlUpdate_ExpGus(farg1, farg2, farg3)
swig_result = fresult
end function

function FSUNControlSpace_ExpGus(c, lenrw, leniw) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SWIGTYPE_p_SUNControl), intent(in) :: c
integer(C_LONG), dimension(*), target, intent(inout) :: lenrw
integer(C_LONG), dimension(*), target, intent(inout) :: leniw
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = c%swigdata
farg2 = c_loc(lenrw(1))
farg3 = c_loc(leniw(1))
fresult = swigc_FSUNControlSpace_ExpGus(farg1, farg2, farg3)
swig_result = fresult
end function


end module
