spack:
  packages:
    all:
      target: [x86_64]
      providers:
        blas:
        - openblas
        mpi:
        - openmpi
  specs:
  - adiak
  - caliper +adiak
  - cmake
  - ginkgo
  - hypre ~int64 precision=single
  - kokkos +serial +openmp
  - kokkos-kernels +serial +openmp
  - openblas ~ilp64
  - openmpi
  - petsc ~double ~int64 ~superlu-dist ~hypre
  - suite-sparse ^openblas ~ilp64 ^metis ~int64
  - superlu-dist ~int64 ^parmetis ~int64 ^metis ~int64
  - superlu-mt ~int64 ~blas
  - trilinos +float +tpetra gotype=int
  - xbraid
  concretizer:
    reuse: false
    compiler_mixing: false
    unify: true
  config:
    install_tree:
      root: /opt/software
  mirrors:
    local: /var/cache/spack-mirror
  repos: []
  upstreams: {}
  view:
    default:
      root: /opt/view
      projections:
        superlu-mt: '{name}'
        superlu-dist: '{name}'
