/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/* ---------------------------------------------------------------
 * Programmer(s): Auto-generated by swig.
 * ---------------------------------------------------------------
 * SUNDIALS Copyright Start
 * Copyright (c) 2025-2026, Lawrence Livermore National Security,
 * University of Maryland Baltimore County, and the SUNDIALS contributors.
 * Copyright (c) 2013-2025, Lawrence Livermore National Security
 * and Southern Methodist University.
 * Copyright (c) 2002-2013, Lawrence Livermore National Security.
 * All rights reserved.
 *
 * See the top-level LICENSE and NOTICE files for details.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 * SUNDIALS Copyright End
 * -------------------------------------------------------------*/

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* qualifier for exported *const* global data variables*/
#ifndef SWIGEXTERN
# ifdef __cplusplus
#   define SWIGEXTERN extern
# else
#   define SWIGEXTERN
# endif
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

/*  Errors in SWIG */
#define  SWIG_UnknownError    	   -1
#define  SWIG_IOError        	   -2
#define  SWIG_RuntimeError   	   -3
#define  SWIG_IndexError     	   -4
#define  SWIG_TypeError      	   -5
#define  SWIG_DivisionByZero 	   -6
#define  SWIG_OverflowError  	   -7
#define  SWIG_SyntaxError    	   -8
#define  SWIG_ValueError     	   -9
#define  SWIG_SystemError    	   -10
#define  SWIG_AttributeError 	   -11
#define  SWIG_MemoryError    	   -12
#define  SWIG_NullReferenceError   -13




#include <assert.h>
#define SWIG_exception_impl(DECL, CODE, MSG, RETURNNULL) \
 { printf("In " DECL ": " MSG); assert(0); RETURNNULL; }


enum {
    SWIG_MEM_OWN = 0x01,
    SWIG_MEM_RVALUE = 0x02,
    SWIG_MEM_CONST = 0x04
};


#define SWIG_check_mutable(SWIG_CLASS_WRAPPER, TYPENAME, FNAME, FUNCNAME, RETURNNULL) \
    if ((SWIG_CLASS_WRAPPER).cmemflags & SWIG_MEM_CONST) { \
        SWIG_exception_impl(FUNCNAME, SWIG_TypeError, \
            "Cannot pass const " TYPENAME " (class " FNAME ") " \
            "as a mutable reference", \
            RETURNNULL); \
    }


#define SWIG_check_nonnull(SWIG_CLASS_WRAPPER, TYPENAME, FNAME, FUNCNAME, RETURNNULL) \
  if (!(SWIG_CLASS_WRAPPER).cptr) { \
    SWIG_exception_impl(FUNCNAME, SWIG_TypeError, \
                        "Cannot pass null " TYPENAME " (class " FNAME ") " \
                        "as a reference", RETURNNULL); \
  }


#define SWIG_check_mutable_nonnull(SWIG_CLASS_WRAPPER, TYPENAME, FNAME, FUNCNAME, RETURNNULL) \
    SWIG_check_nonnull(SWIG_CLASS_WRAPPER, TYPENAME, FNAME, FUNCNAME, RETURNNULL); \
    SWIG_check_mutable(SWIG_CLASS_WRAPPER, TYPENAME, FNAME, FUNCNAME, RETURNNULL);


#include <stdio.h>
#if defined(_MSC_VER) || defined(__BORLANDC__) || defined(_WATCOM)
# ifndef snprintf
#  define snprintf _snprintf
# endif
#endif


/* Support for the `contract` feature.
 *
 * Note that RETURNNULL is first because it's inserted via a 'Replaceall' in
 * the fortran.cxx file.
 */
#define SWIG_contract_assert(RETURNNULL, EXPR, MSG) \
 if (!(EXPR)) { SWIG_exception_impl("$decl", SWIG_ValueError, MSG, RETURNNULL); } 


#define SWIGVERSION 0x040000 
#define SWIG_VERSION SWIGVERSION


#define SWIG_as_voidptr(a) (void *)((const void *)(a)) 
#define SWIG_as_voidptrptr(a) ((void)SWIG_as_voidptr(*a),(void**)(a)) 


#include "sundials/sundials_nvector.h"


#include "nvector/nvector_manyvector.h"


typedef struct {
    void* cptr;
    int cmemflags;
} SwigClassWrapper;


SWIGINTERN SwigClassWrapper SwigClassWrapper_uninitialized() {
    SwigClassWrapper result;
    result.cptr = NULL;
    result.cmemflags = 0;
    return result;
}


#include <stdlib.h>
#ifdef _MSC_VER
# ifndef strtoull
#  define strtoull _strtoui64
# endif
# ifndef strtoll
#  define strtoll _strtoi64
# endif
#endif


#include <string.h>


SWIGINTERN void SWIG_assign(SwigClassWrapper* self, SwigClassWrapper other) {
  if (self->cptr == NULL) {
    /* LHS is unassigned */
    if (other.cmemflags & SWIG_MEM_RVALUE) {
      /* Capture pointer from RHS, clear 'moving' flag */
      self->cptr = other.cptr;
      self->cmemflags = other.cmemflags & (~SWIG_MEM_RVALUE);
    } else {
      /* Become a reference to the other object */
      self->cptr = other.cptr;
      self->cmemflags = other.cmemflags & (~SWIG_MEM_OWN);
    }
  } else if (other.cptr == NULL) {
    /* Replace LHS with a null pointer */
    free(self->cptr);
    *self = SwigClassWrapper_uninitialized();
  } else {
    if (self->cmemflags & SWIG_MEM_OWN) {
      free(self->cptr);
    }
    self->cptr = other.cptr;
    if (other.cmemflags & SWIG_MEM_RVALUE) {
      /* Capture RHS */
      self->cmemflags = other.cmemflags & ~SWIG_MEM_RVALUE;
    } else {
      /* Point to RHS */
      self->cmemflags = other.cmemflags & ~SWIG_MEM_OWN;
    }
  }
}

SWIGEXPORT void _wrap_N_VectorContent_ManyVector__num_subvectors_set(SwigClassWrapper const *farg1, int32_t const *farg2) {
  struct N_VectorContent_ManyVector_ *arg1 = (struct N_VectorContent_ManyVector_ *) 0 ;
  sunindextype arg2 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct N_VectorContent_ManyVector_ *", "N_VectorContent_ManyVector_", "N_VectorContent_ManyVector_::num_subvectors", return );
  arg1 = (struct N_VectorContent_ManyVector_ *)(farg1->cptr);
  arg2 = (sunindextype)(*farg2);
  if (arg1) (arg1)->num_subvectors = arg2;
}


SWIGEXPORT int32_t _wrap_N_VectorContent_ManyVector__num_subvectors_get(SwigClassWrapper const *farg1) {
  int32_t fresult ;
  struct N_VectorContent_ManyVector_ *arg1 = (struct N_VectorContent_ManyVector_ *) 0 ;
  sunindextype result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct N_VectorContent_ManyVector_ *", "N_VectorContent_ManyVector_", "N_VectorContent_ManyVector_::num_subvectors", return 0);
  arg1 = (struct N_VectorContent_ManyVector_ *)(farg1->cptr);
  result =  ((arg1)->num_subvectors);
  fresult = (sunindextype)(result);
  return fresult;
}


SWIGEXPORT void _wrap_N_VectorContent_ManyVector__global_length_set(SwigClassWrapper const *farg1, int32_t const *farg2) {
  struct N_VectorContent_ManyVector_ *arg1 = (struct N_VectorContent_ManyVector_ *) 0 ;
  sunindextype arg2 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct N_VectorContent_ManyVector_ *", "N_VectorContent_ManyVector_", "N_VectorContent_ManyVector_::global_length", return );
  arg1 = (struct N_VectorContent_ManyVector_ *)(farg1->cptr);
  arg2 = (sunindextype)(*farg2);
  if (arg1) (arg1)->global_length = arg2;
}


SWIGEXPORT int32_t _wrap_N_VectorContent_ManyVector__global_length_get(SwigClassWrapper const *farg1) {
  int32_t fresult ;
  struct N_VectorContent_ManyVector_ *arg1 = (struct N_VectorContent_ManyVector_ *) 0 ;
  sunindextype result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct N_VectorContent_ManyVector_ *", "N_VectorContent_ManyVector_", "N_VectorContent_ManyVector_::global_length", return 0);
  arg1 = (struct N_VectorContent_ManyVector_ *)(farg1->cptr);
  result =  ((arg1)->global_length);
  fresult = (sunindextype)(result);
  return fresult;
}


SWIGEXPORT void _wrap_N_VectorContent_ManyVector__subvec_array_set(SwigClassWrapper const *farg1, void *farg2) {
  struct N_VectorContent_ManyVector_ *arg1 = (struct N_VectorContent_ManyVector_ *) 0 ;
  N_Vector *arg2 = (N_Vector *) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct N_VectorContent_ManyVector_ *", "N_VectorContent_ManyVector_", "N_VectorContent_ManyVector_::subvec_array", return );
  arg1 = (struct N_VectorContent_ManyVector_ *)(farg1->cptr);
  arg2 = (N_Vector *)(farg2);
  if (arg1) (arg1)->subvec_array = arg2;
}


SWIGEXPORT void * _wrap_N_VectorContent_ManyVector__subvec_array_get(SwigClassWrapper const *farg1) {
  void * fresult ;
  struct N_VectorContent_ManyVector_ *arg1 = (struct N_VectorContent_ManyVector_ *) 0 ;
  N_Vector *result = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct N_VectorContent_ManyVector_ *", "N_VectorContent_ManyVector_", "N_VectorContent_ManyVector_::subvec_array", return 0);
  arg1 = (struct N_VectorContent_ManyVector_ *)(farg1->cptr);
  result = (N_Vector *) ((arg1)->subvec_array);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap_N_VectorContent_ManyVector__own_data_set(SwigClassWrapper const *farg1, int const *farg2) {
  struct N_VectorContent_ManyVector_ *arg1 = (struct N_VectorContent_ManyVector_ *) 0 ;
  int arg2 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct N_VectorContent_ManyVector_ *", "N_VectorContent_ManyVector_", "N_VectorContent_ManyVector_::own_data", return );
  arg1 = (struct N_VectorContent_ManyVector_ *)(farg1->cptr);
  arg2 = (int)(*farg2);
  if (arg1) (arg1)->own_data = arg2;
}


SWIGEXPORT int _wrap_N_VectorContent_ManyVector__own_data_get(SwigClassWrapper const *farg1) {
  int fresult ;
  struct N_VectorContent_ManyVector_ *arg1 = (struct N_VectorContent_ManyVector_ *) 0 ;
  int result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct N_VectorContent_ManyVector_ *", "N_VectorContent_ManyVector_", "N_VectorContent_ManyVector_::own_data", return 0);
  arg1 = (struct N_VectorContent_ManyVector_ *)(farg1->cptr);
  result = (int) ((arg1)->own_data);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new_N_VectorContent_ManyVector_() {
  SwigClassWrapper fresult ;
  struct N_VectorContent_ManyVector_ *result = 0 ;
  
  result = (struct N_VectorContent_ManyVector_ *)calloc(1, sizeof(struct N_VectorContent_ManyVector_));
  fresult.cptr = result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete_N_VectorContent_ManyVector_(SwigClassWrapper *farg1) {
  struct N_VectorContent_ManyVector_ *arg1 = (struct N_VectorContent_ManyVector_ *) 0 ;
  
  SWIG_check_mutable(*farg1, "struct N_VectorContent_ManyVector_ *", "N_VectorContent_ManyVector_", "N_VectorContent_ManyVector_::~N_VectorContent_ManyVector_()", return );
  arg1 = (struct N_VectorContent_ManyVector_ *)(farg1->cptr);
  free((char *) arg1);
}


SWIGEXPORT void _wrap_N_VectorContent_ManyVector__op_assign__(SwigClassWrapper *farg1, SwigClassWrapper const *farg2) {
  struct N_VectorContent_ManyVector_ *arg1 = (struct N_VectorContent_ManyVector_ *) 0 ;
  struct N_VectorContent_ManyVector_ *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}


SWIGEXPORT SwigClassWrapper _wrap_FN_VNew_ManyVector(int32_t const *farg1, void *farg2, void *farg3) {
  SwigClassWrapper fresult ;
  sunindextype arg1 ;
  N_Vector *arg2 = (N_Vector *) 0 ;
  SUNContext arg3 = (SUNContext) 0 ;
  N_Vector result;
  
  arg1 = (sunindextype)(*farg1);
  arg2 = (N_Vector *)(farg2);
  arg3 = (SUNContext)(farg3);
  result = (N_Vector)N_VNew_ManyVector(arg1,arg2,arg3);
  fresult.cptr = result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_FN_VGetSubvector_ManyVector(SwigClassWrapper const *farg1, int32_t const *farg2) {
  SwigClassWrapper fresult ;
  N_Vector arg1 = (N_Vector) 0 ;
  sunindextype arg2 ;
  N_Vector result;
  
  SWIG_check_mutable(*farg1, "N_Vector", "N_Vector_", "N_VGetSubvector_ManyVector(N_Vector,sunindextype)", return SwigClassWrapper_uninitialized());
  arg1 = (N_Vector)(farg1->cptr);
  arg2 = (sunindextype)(*farg2);
  result = (N_Vector)N_VGetSubvector_ManyVector(arg1,arg2);
  fresult.cptr = result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT int _wrap_FN_VSetSubvectorArrayPointer_ManyVector(double *farg1, SwigClassWrapper const *farg2, int32_t const *farg3) {
  int fresult ;
  sunrealtype *arg1 = (sunrealtype *) 0 ;
  N_Vector arg2 = (N_Vector) 0 ;
  sunindextype arg3 ;
  SUNErrCode result;
  
  arg1 = (sunrealtype *)(farg1);
  SWIG_check_mutable(*farg2, "N_Vector", "N_Vector_", "N_VSetSubvectorArrayPointer_ManyVector(sunrealtype *,N_Vector,sunindextype)", return 0);
  arg2 = (N_Vector)(farg2->cptr);
  arg3 = (sunindextype)(*farg3);
  result = (SUNErrCode)N_VSetSubvectorArrayPointer_ManyVector(arg1,arg2,arg3);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int32_t _wrap_FN_VGetNumSubvectors_ManyVector(SwigClassWrapper const *farg1) {
  int32_t fresult ;
  N_Vector arg1 = (N_Vector) 0 ;
  sunindextype result;
  
  SWIG_check_mutable(*farg1, "N_Vector", "N_Vector_", "N_VGetNumSubvectors_ManyVector(N_Vector)", return 0);
  arg1 = (N_Vector)(farg1->cptr);
  result = N_VGetNumSubvectors_ManyVector(arg1);
  fresult = (sunindextype)(result);
  return fresult;
}


SWIGEXPORT int32_t _wrap_FN_VGetSubvectorLocalLength_ManyVector(SwigClassWrapper const *farg1, int32_t const *farg2) {
  int32_t fresult ;
  N_Vector arg1 = (N_Vector) 0 ;
  sunindextype arg2 ;
  sunindextype result;
  
  SWIG_check_mutable(*farg1, "N_Vector", "N_Vector_", "N_VGetSubvectorLocalLength_ManyVector(N_Vector,sunindextype)", return 0);
  arg1 = (N_Vector)(farg1->cptr);
  arg2 = (sunindextype)(*farg2);
  result = N_VGetSubvectorLocalLength_ManyVector(arg1,arg2);
  fresult = (sunindextype)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FN_VEnableFusedOps_ManyVector(SwigClassWrapper const *farg1, int const *farg2) {
  int fresult ;
  N_Vector arg1 = (N_Vector) 0 ;
  int arg2 ;
  SUNErrCode result;
  
  SWIG_check_mutable(*farg1, "N_Vector", "N_Vector_", "N_VEnableFusedOps_ManyVector(N_Vector,int)", return 0);
  arg1 = (N_Vector)(farg1->cptr);
  arg2 = (int)(*farg2);
  result = (SUNErrCode)N_VEnableFusedOps_ManyVector(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FN_VEnableLinearCombination_ManyVector(SwigClassWrapper const *farg1, int const *farg2) {
  int fresult ;
  N_Vector arg1 = (N_Vector) 0 ;
  int arg2 ;
  SUNErrCode result;
  
  SWIG_check_mutable(*farg1, "N_Vector", "N_Vector_", "N_VEnableLinearCombination_ManyVector(N_Vector,int)", return 0);
  arg1 = (N_Vector)(farg1->cptr);
  arg2 = (int)(*farg2);
  result = (SUNErrCode)N_VEnableLinearCombination_ManyVector(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FN_VEnableScaleAddMulti_ManyVector(SwigClassWrapper const *farg1, int const *farg2) {
  int fresult ;
  N_Vector arg1 = (N_Vector) 0 ;
  int arg2 ;
  SUNErrCode result;
  
  SWIG_check_mutable(*farg1, "N_Vector", "N_Vector_", "N_VEnableScaleAddMulti_ManyVector(N_Vector,int)", return 0);
  arg1 = (N_Vector)(farg1->cptr);
  arg2 = (int)(*farg2);
  result = (SUNErrCode)N_VEnableScaleAddMulti_ManyVector(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FN_VEnableDotProdMulti_ManyVector(SwigClassWrapper const *farg1, int const *farg2) {
  int fresult ;
  N_Vector arg1 = (N_Vector) 0 ;
  int arg2 ;
  SUNErrCode result;
  
  SWIG_check_mutable(*farg1, "N_Vector", "N_Vector_", "N_VEnableDotProdMulti_ManyVector(N_Vector,int)", return 0);
  arg1 = (N_Vector)(farg1->cptr);
  arg2 = (int)(*farg2);
  result = (SUNErrCode)N_VEnableDotProdMulti_ManyVector(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FN_VEnableLinearSumVectorArray_ManyVector(SwigClassWrapper const *farg1, int const *farg2) {
  int fresult ;
  N_Vector arg1 = (N_Vector) 0 ;
  int arg2 ;
  SUNErrCode result;
  
  SWIG_check_mutable(*farg1, "N_Vector", "N_Vector_", "N_VEnableLinearSumVectorArray_ManyVector(N_Vector,int)", return 0);
  arg1 = (N_Vector)(farg1->cptr);
  arg2 = (int)(*farg2);
  result = (SUNErrCode)N_VEnableLinearSumVectorArray_ManyVector(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FN_VEnableScaleVectorArray_ManyVector(SwigClassWrapper const *farg1, int const *farg2) {
  int fresult ;
  N_Vector arg1 = (N_Vector) 0 ;
  int arg2 ;
  SUNErrCode result;
  
  SWIG_check_mutable(*farg1, "N_Vector", "N_Vector_", "N_VEnableScaleVectorArray_ManyVector(N_Vector,int)", return 0);
  arg1 = (N_Vector)(farg1->cptr);
  arg2 = (int)(*farg2);
  result = (SUNErrCode)N_VEnableScaleVectorArray_ManyVector(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FN_VEnableConstVectorArray_ManyVector(SwigClassWrapper const *farg1, int const *farg2) {
  int fresult ;
  N_Vector arg1 = (N_Vector) 0 ;
  int arg2 ;
  SUNErrCode result;
  
  SWIG_check_mutable(*farg1, "N_Vector", "N_Vector_", "N_VEnableConstVectorArray_ManyVector(N_Vector,int)", return 0);
  arg1 = (N_Vector)(farg1->cptr);
  arg2 = (int)(*farg2);
  result = (SUNErrCode)N_VEnableConstVectorArray_ManyVector(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FN_VEnableWrmsNormVectorArray_ManyVector(SwigClassWrapper const *farg1, int const *farg2) {
  int fresult ;
  N_Vector arg1 = (N_Vector) 0 ;
  int arg2 ;
  SUNErrCode result;
  
  SWIG_check_mutable(*farg1, "N_Vector", "N_Vector_", "N_VEnableWrmsNormVectorArray_ManyVector(N_Vector,int)", return 0);
  arg1 = (N_Vector)(farg1->cptr);
  arg2 = (int)(*farg2);
  result = (SUNErrCode)N_VEnableWrmsNormVectorArray_ManyVector(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FN_VEnableWrmsNormMaskVectorArray_ManyVector(SwigClassWrapper const *farg1, int const *farg2) {
  int fresult ;
  N_Vector arg1 = (N_Vector) 0 ;
  int arg2 ;
  SUNErrCode result;
  
  SWIG_check_mutable(*farg1, "N_Vector", "N_Vector_", "N_VEnableWrmsNormMaskVectorArray_ManyVector(N_Vector,int)", return 0);
  arg1 = (N_Vector)(farg1->cptr);
  arg2 = (int)(*farg2);
  result = (SUNErrCode)N_VEnableWrmsNormMaskVectorArray_ManyVector(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FN_VEnableDotProdMultiLocal_ManyVector(SwigClassWrapper const *farg1, int const *farg2) {
  int fresult ;
  N_Vector arg1 = (N_Vector) 0 ;
  int arg2 ;
  SUNErrCode result;
  
  SWIG_check_mutable(*farg1, "N_Vector", "N_Vector_", "N_VEnableDotProdMultiLocal_ManyVector(N_Vector,int)", return 0);
  arg1 = (N_Vector)(farg1->cptr);
  arg2 = (int)(*farg2);
  result = (SUNErrCode)N_VEnableDotProdMultiLocal_ManyVector(arg1,arg2);
  fresult = (SUNErrCode)(result);
  return fresult;
}



#ifdef SUNDIALS_INT32_T
SWIGEXPORT double * _wrap_FN_VGetSubvectorArrayPointer_ManyVector(N_Vector farg1, int32_t const *farg2) {
  double * fresult ;
  N_Vector arg1 = (N_Vector) 0 ;
  sunindextype arg2 ;
  sunrealtype *result = 0 ;

  arg1 = (N_Vector)(farg1);
  arg2 = (sunindextype)(*farg2);
  result = (sunrealtype *)N_VGetSubvectorArrayPointer_ManyVector(arg1,arg2);
  fresult = result;
  return fresult;
}
#else
SWIGEXPORT double * _wrap_FN_VGetSubvectorArrayPointer_ManyVector(N_Vector farg1, int64_t const *farg2) {
  double * fresult ;
  N_Vector arg1 = (N_Vector) 0 ;
  sunindextype arg2 ;
  sunrealtype *result = 0 ;

  arg1 = (N_Vector)(farg1);
  arg2 = (sunindextype)(*farg2);
  result = (sunrealtype *)N_VGetSubvectorArrayPointer_ManyVector(arg1,arg2);
  fresult = result;
  return fresult;
}
#endif


