#!/usr/bin/env groovy
pipeline {
    agent any

    stages {
        stage('Test') {
            steps {
              // output for collapse setions plugin
              echo "END JENKINS SETUP"

              // run regression tests
              sh('cd regression && ./suntest_driver.sh')
            }
        }
    }
}
