# -----------------------------------------------------------------
# $Revision: $
# $Date: $
# -----------------------------------------------------------------
# Programmer(s): Radu Serban @ LLNL
# -----------------------------------------------------------------
# Copyright (c) 2002, The Regents of the University of California.
# Produced at the Lawrence Livermore National Laboratory.
# All rights reserved.
# For details, see sundials/kinsol/LICENSE.
# -----------------------------------------------------------------
# Makefile for KINSOL documents
# -----------------------------------------------------------------

#QUIET =

USER_GUIDE = kin_guide
EXAMPLES   = kin_examples


UG_FILES = \
${USER_GUIDE}.tex \
kin_intro.tex \
kin_install.tex \
kin_math.tex \
kin_use.tex \
kin_fcmix.tex \
kin_nvec.tex \
kin_org.tex \
kin_newlinsolv.tex \
kin_constants.tex
#kin_linsolv.tex \

EX_FILES = \
${EXAMPLES}.tex \
kin_ex_intro.tex \
kin_ex_c.tex \
kin_ex_fortran.tex \
kin_ex_codes.tex

