# -----------------------------------------------------------------
# Programmer(s): Slaven Peles, Cody Balos @ LLNL
# -----------------------------------------------------------------
# SUNDIALS Copyright Start
# Copyright (c) 2002-2020, Lawrence Livermore National Security
# and Southern Methodist University.
# All rights reserved.
#
# See the top-level LICENSE and NOTICE files for details.
#
# SPDX-License-Identifier: BSD-3-Clause
# SUNDIALS Copyright End
# -----------------------------------------------------------------
# Makefile for KINSOL documentation
# -----------------------------------------------------------------

USER_GUIDE = kin_guide
EXAMPLES   = kin_examples

# names of guide files
UG_FILES = \
${USER_GUIDE}.tex \
kin_intro.tex \
kin_math.tex \
kin_org.tex \
kin_use.tex \
kin_fcmix.tex \
kin_nvec.tex \
kin_newlinsolv.tex \
kin_sunmat.tex \
kin_sunlinsol.tex \
kin_constants.tex

EX_FILES = \
${EXAMPLES}.tex \
kin_ex_intro.tex \
kin_ex_c.tex \
kin_ex_fortran.tex

include ../Makefile.in
