# -----------------------------------------------------------------
# $Revision$
# $Date$
# -----------------------------------------------------------------
# Programmer(s): Slaven Peles @ LLNL
# -----------------------------------------------------------------
# LLNS Copyright Start
# Copyright (c) 2014, Lawrence Livermore National Security
# This work was performed under the auspices of the U.S. Department 
# of Energy by Lawrence Livermore National Laboratory in part under 
# Contract W-7405-Eng-48 and in part under Contract DE-AC52-07NA27344.
# Produced at the Lawrence Livermore National Laboratory.
# All rights reserved.
# For details, see the LICENSE file.
# LLNS Copyright End
# -----------------------------------------------------------------
# Makefile for KINSOL documents
# -----------------------------------------------------------------

#QUIET =

USER_GUIDE = kin_guide
EXAMPLES   = kin_examples


UG_FILES = \
${USER_GUIDE}.tex \
kin_intro.tex \
kin_math.tex \
kin_org.tex \
kin_use.tex \
kin_fcmix.tex \
kin_nvec.tex \
kin_newlinsolv.tex \
kin_constants.tex

EX_FILES = \
${EXAMPLES}.tex \
kin_ex_intro.tex \
kin_ex_c.tex \
kin_ex_fortran.tex

include ../Makefile.in
