name: Build and Test
description: Builds and tests SUNDIALS using the test_driver.sh script

inputs:
  precision:
    description: SUNDIALS_PRECISION
    required: true
  indexsize:
    description: SUNDIALS_INDEX_SIZE
    required: true
  tpls:
    description: "enable/disable TPLs"
    required: true

runs:
  using: composite
  steps:
    - id: container-information
      run: |
        cat /proc/cpuinfo
        uname -p
      shell: bash
    - id: spack-find
      run: |
        eval `/opt/spack/bin/spack env activate --sh /opt/spack-environment`
        /opt/spack/bin/spack find -vl
      shell: bash
    - id: run-test-driver
      run: |
        export PATH="/opt/views/int${{ inputs.indexsize }}-${{ inputs.precision }}/bin:$PATH"
        git config --global --add safe.directory $GITHUB_WORKSPACE
        cd test
        ./test_driver.sh \
        --testtype CUSTOM \
        --env env/docker.sh \
        --tpls ${{ inputs.tpls }} \
        --sunrealtype ${{ inputs.precision }} \
        --indexsize ${{ inputs.indexsize }}
      shell: bash
