name: Build and Test
description: Builds and tests SUNDIALS using the test_driver.sh script

inputs:
  precision:
    description: SUNDIALS_PRECISION
    required: true
  indexsize:
    description: SUNDIALS_INDEX_SIZE
    required: true

runs:
  using: composite
  steps:
    - id: container-information
      run: |
          cat /proc/cpuinfo
          uname -p
      shell: bash
    - id: spack-find
      run: |
          eval `/opt/spack/bin/spack env activate --sh /opt/spack-environment`
          /opt/spack/bin/spack find -v
      shell: bash
    - id: run-test-driver
      run: |
        git config --global --add safe.directory $GITHUB_WORKSPACE
        cd test
        # Turn off GTest unit tests since test_sundials_errors.c randomly Segfaults in Github actions CI
        export SUNDIALS_TEST_DISABLE_GTEST=ON
        ./test_driver.sh --testtype CUSTOM --env env/docker.sh --tpls --sunrealtype ${{ inputs.precision }} --indexsize ${{ inputs.indexsize }}
      shell: bash
