# -----------------------------------------------------------------
# $Revision:  $
# $Date:  $
# -----------------------------------------------------------------
# Programmer(s): Slaven Peles @ LLNL
# -----------------------------------------------------------------
# LLNS Copyright Start
# Copyright (c) 2014, Lawrence Livermore National Security
# This work was performed under the auspices of the U.S. Department 
# of Energy by Lawrence Livermore National Laboratory in part under 
# Contract W-7405-Eng-48 and in part under Contract DE-AC52-07NA27344.
# Produced at the Lawrence Livermore National Laboratory.
# All rights reserved.
# For details, see the LICENSE file.
# LLNS Copyright End
# -----------------------------------------------------------------
# Makefile for CVODES documents
# -----------------------------------------------------------------

USER_GUIDE = cvs_guide
EXAMPLES   = cvs_examples

UG_FILES = \
${USER_GUIDE}.tex \
cvs_intro.tex \
cvs_install.tex \
cvs_math.tex \
cvs_org.tex \
cvs_sim.tex \
cvs_fwd.tex \
cvs_adj.tex \
cvs_nvec.tex \
cvs_newlinsolv.tex \
#cvs_linsolv.tex \
cvs_constants.tex

EX_FILES = \
${EXAMPLES}.tex \
cvs_ex_intro.tex \
cvs_ex_fwd.tex \
cvs_ex_adj.tex \
cvs_ex_codes.tex \
cvs_ex_tests.tex   

include ../Makefile.in
