! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! ---------------------------------------------------------------
! Programmer(s): Auto-generated by swig.
! ---------------------------------------------------------------
! SUNDIALS Copyright Start
! Copyright (c) 2002-2023, Lawrence Livermore National Security
! and Southern Methodist University.
! All rights reserved.
!
! See the top-level LICENSE and NOTICE files for details.
!
! SPDX-License-Identifier: BSD-3-Clause
! SUNDIALS Copyright End
! ---------------------------------------------------------------

module fsunadaptcontroller_expgus_mod
 use, intrinsic :: ISO_C_BINDING
 use fsundials_adaptcontroller_mod
 use fsundials_types_mod
 use fsundials_context_mod
 implicit none
 private

 ! DECLARATION CONSTRUCTS
 public :: FSUNAdaptController_ExpGus
 public :: FSUNAdaptController_SetParams_ExpGus
 public :: FSUNAdaptController_GetType_ExpGus
 public :: FSUNAdaptController_EstimateStep_ExpGus
 public :: FSUNAdaptController_Reset_ExpGus
 public :: FSUNAdaptController_SetDefaults_ExpGus
 public :: FSUNAdaptController_Write_ExpGus
 public :: FSUNAdaptController_SetMethodOrder_ExpGus
 public :: FSUNAdaptController_SetEmbeddingOrder_ExpGus
 public :: FSUNAdaptController_SetErrorBias_ExpGus
 public :: FSUNAdaptController_Update_ExpGus
 public :: FSUNAdaptController_Space_ExpGus

! WRAPPER DECLARATIONS
interface
function swigc_FSUNAdaptController_ExpGus(farg1) &
bind(C, name="_wrap_FSUNAdaptController_ExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR) :: fresult
end function

function swigc_FSUNAdaptController_SetParams_ExpGus(farg1, farg2, farg3, farg4) &
bind(C, name="_wrap_FSUNAdaptController_SetParams_ExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
real(C_DOUBLE), intent(in) :: farg3
real(C_DOUBLE), intent(in) :: farg4
integer(C_INT) :: fresult
end function

function swigc_FSUNAdaptController_GetType_ExpGus(farg1) &
bind(C, name="_wrap_FSUNAdaptController_GetType_ExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT) :: fresult
end function

function swigc_FSUNAdaptController_EstimateStep_ExpGus(farg1, farg2, farg3, farg4) &
bind(C, name="_wrap_FSUNAdaptController_EstimateStep_ExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
real(C_DOUBLE), intent(in) :: farg2
real(C_DOUBLE), intent(in) :: farg3
type(C_PTR), value :: farg4
integer(C_INT) :: fresult
end function

function swigc_FSUNAdaptController_Reset_ExpGus(farg1) &
bind(C, name="_wrap_FSUNAdaptController_Reset_ExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT) :: fresult
end function

function swigc_FSUNAdaptController_SetDefaults_ExpGus(farg1) &
bind(C, name="_wrap_FSUNAdaptController_SetDefaults_ExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT) :: fresult
end function

function swigc_FSUNAdaptController_Write_ExpGus(farg1, farg2) &
bind(C, name="_wrap_FSUNAdaptController_Write_ExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNAdaptController_SetMethodOrder_ExpGus(farg1, farg2) &
bind(C, name="_wrap_FSUNAdaptController_SetMethodOrder_ExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNAdaptController_SetEmbeddingOrder_ExpGus(farg1, farg2) &
bind(C, name="_wrap_FSUNAdaptController_SetEmbeddingOrder_ExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNAdaptController_SetErrorBias_ExpGus(farg1, farg2) &
bind(C, name="_wrap_FSUNAdaptController_SetErrorBias_ExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
real(C_DOUBLE), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNAdaptController_Update_ExpGus(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNAdaptController_Update_ExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
real(C_DOUBLE), intent(in) :: farg2
real(C_DOUBLE), intent(in) :: farg3
integer(C_INT) :: fresult
end function

function swigc_FSUNAdaptController_Space_ExpGus(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNAdaptController_Space_ExpGus") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
integer(C_INT) :: fresult
end function

end interface


contains
 ! MODULE SUBPROGRAMS
function FSUNAdaptController_ExpGus(sunctx) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SUNAdaptController), pointer :: swig_result
type(C_PTR) :: sunctx
type(C_PTR) :: fresult 
type(C_PTR) :: farg1 

farg1 = sunctx
fresult = swigc_FSUNAdaptController_ExpGus(farg1)
call c_f_pointer(fresult, swig_result)
end function

function FSUNAdaptController_SetParams_ExpGus(c, pq, k1, k2) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNAdaptController), target, intent(inout) :: c
integer(C_INT), intent(in) :: pq
real(C_DOUBLE), intent(in) :: k1
real(C_DOUBLE), intent(in) :: k2
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 
real(C_DOUBLE) :: farg3 
real(C_DOUBLE) :: farg4 

farg1 = c_loc(c)
farg2 = pq
farg3 = k1
farg4 = k2
fresult = swigc_FSUNAdaptController_SetParams_ExpGus(farg1, farg2, farg3, farg4)
swig_result = fresult
end function

function FSUNAdaptController_GetType_ExpGus(c) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(SUNAdaptController_Type) :: swig_result
type(SUNAdaptController), target, intent(inout) :: c
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(c)
fresult = swigc_FSUNAdaptController_GetType_ExpGus(farg1)
swig_result = fresult
end function

function FSUNAdaptController_EstimateStep_ExpGus(c, h, dsm, hnew) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNAdaptController), target, intent(inout) :: c
real(C_DOUBLE), intent(in) :: h
real(C_DOUBLE), intent(in) :: dsm
real(C_DOUBLE), dimension(*), target, intent(inout) :: hnew
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
real(C_DOUBLE) :: farg2 
real(C_DOUBLE) :: farg3 
type(C_PTR) :: farg4 

farg1 = c_loc(c)
farg2 = h
farg3 = dsm
farg4 = c_loc(hnew(1))
fresult = swigc_FSUNAdaptController_EstimateStep_ExpGus(farg1, farg2, farg3, farg4)
swig_result = fresult
end function

function FSUNAdaptController_Reset_ExpGus(c) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNAdaptController), target, intent(inout) :: c
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(c)
fresult = swigc_FSUNAdaptController_Reset_ExpGus(farg1)
swig_result = fresult
end function

function FSUNAdaptController_SetDefaults_ExpGus(c) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNAdaptController), target, intent(inout) :: c
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(c)
fresult = swigc_FSUNAdaptController_SetDefaults_ExpGus(farg1)
swig_result = fresult
end function

function FSUNAdaptController_Write_ExpGus(c, fptr) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNAdaptController), target, intent(inout) :: c
type(C_PTR) :: fptr
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(c)
farg2 = fptr
fresult = swigc_FSUNAdaptController_Write_ExpGus(farg1, farg2)
swig_result = fresult
end function

function FSUNAdaptController_SetMethodOrder_ExpGus(c, q) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNAdaptController), target, intent(inout) :: c
integer(C_INT), intent(in) :: q
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(c)
farg2 = q
fresult = swigc_FSUNAdaptController_SetMethodOrder_ExpGus(farg1, farg2)
swig_result = fresult
end function

function FSUNAdaptController_SetEmbeddingOrder_ExpGus(c, p) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNAdaptController), target, intent(inout) :: c
integer(C_INT), intent(in) :: p
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(c)
farg2 = p
fresult = swigc_FSUNAdaptController_SetEmbeddingOrder_ExpGus(farg1, farg2)
swig_result = fresult
end function

function FSUNAdaptController_SetErrorBias_ExpGus(c, bias) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNAdaptController), target, intent(inout) :: c
real(C_DOUBLE), intent(in) :: bias
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
real(C_DOUBLE) :: farg2 

farg1 = c_loc(c)
farg2 = bias
fresult = swigc_FSUNAdaptController_SetErrorBias_ExpGus(farg1, farg2)
swig_result = fresult
end function

function FSUNAdaptController_Update_ExpGus(c, h, dsm) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNAdaptController), target, intent(inout) :: c
real(C_DOUBLE), intent(in) :: h
real(C_DOUBLE), intent(in) :: dsm
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
real(C_DOUBLE) :: farg2 
real(C_DOUBLE) :: farg3 

farg1 = c_loc(c)
farg2 = h
farg3 = dsm
fresult = swigc_FSUNAdaptController_Update_ExpGus(farg1, farg2, farg3)
swig_result = fresult
end function

function FSUNAdaptController_Space_ExpGus(c, lenrw, leniw) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNAdaptController), target, intent(inout) :: c
integer(C_LONG), dimension(*), target, intent(inout) :: lenrw
integer(C_LONG), dimension(*), target, intent(inout) :: leniw
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = c_loc(c)
farg2 = c_loc(lenrw(1))
farg3 = c_loc(leniw(1))
fresult = swigc_FSUNAdaptController_Space_ExpGus(farg1, farg2, farg3)
swig_result = fresult
end function


end module
