set(example cv_analytic_sys_klu_f2003)
set(CMAKE_Fortran_MODULE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/CMakeFiles/${example}.dir)
sundials_add_executable(${example} ${example}.f90)
set_target_properties(${example} PROPERTIES FOLDER "Examples")
sundials_add_test(${example} ${example} ANSWER_DIR ${CMAKE_CURRENT_SOURCE_DIR} ANSWER_FILE ${example}.out EXAMPLE_TYPE develop)
target_link_libraries(${example} sundials_cvode sundials_fcvode_mod sundials_fsunlinsolklu_mod ${EXE_EXTRA_LINK_LIBS})
if(SUNDIALS_ENABLE_PACKAGE_FUSED_KERNELS)
  target_link_libraries(${example} sundials_cvode_fused_stubs)
endif()
if(SUNDIALS_ENABLE_EXAMPLES_INSTALL)
  install(FILES ${example}.f90 ${example}.out DESTINATION ${SUNDIALS_EXAMPLES_INSTALL_PATH}/cvode/fortran/cv_analytic_sys_klu_f2003)
endif()
