! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! ---------------------------------------------------------------
! Programmer(s): Auto-generated by swig.
! ---------------------------------------------------------------
! SUNDIALS Copyright Start
! Copyright (c) 2025-2026, Lawrence Livermore National Security,
! University of Maryland Baltimore County, and the SUNDIALS contributors.
! Copyright (c) 2013-2025, Lawrence Livermore National Security
! and Southern Methodist University.
! Copyright (c) 2002-2013, Lawrence Livermore National Security.
! All rights reserved.
!
! See the top-level LICENSE and NOTICE files for details.
!
! SPDX-License-Identifier: BSD-3-Clause
! SUNDIALS Copyright End
! ---------------------------------------------------------------

module fsunnonlinsol_newton_mod
 use, intrinsic :: ISO_C_BINDING
 use fsundials_core_mod
 implicit none
 private

 ! DECLARATION CONSTRUCTS
 public :: FSUNNonlinSol_Newton
 public :: FSUNNonlinSol_NewtonSens
 public :: FSUNNonlinSolSetComputeStiffnessRatio_Newton
 public :: FSUNNonlinSolGetSysFn_Newton
 public :: FSUNNonlinSolGetStiffnessRatio_Newton

! WRAPPER DECLARATIONS
interface
function swigc_FSUNNonlinSol_Newton(farg1, farg2) &
bind(C, name="_wrap_FSUNNonlinSol_Newton") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR) :: fresult
end function

function swigc_FSUNNonlinSol_NewtonSens(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNNonlinSol_NewtonSens") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
type(C_PTR) :: fresult
end function

function swigc_FSUNNonlinSolSetComputeStiffnessRatio_Newton(farg1, farg2) &
bind(C, name="_wrap_FSUNNonlinSolSetComputeStiffnessRatio_Newton") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolGetSysFn_Newton(farg1, farg2) &
bind(C, name="_wrap_FSUNNonlinSolGetSysFn_Newton") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNNonlinSolGetStiffnessRatio_Newton(farg1, farg2) &
bind(C, name="_wrap_FSUNNonlinSolGetStiffnessRatio_Newton") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
integer(C_INT) :: fresult
end function

end interface


contains
 ! MODULE SUBPROGRAMS
function FSUNNonlinSol_Newton(y, sunctx) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SUNNonlinearSolver), pointer :: swig_result
type(N_Vector), target, intent(inout) :: y
type(C_PTR) :: sunctx
type(C_PTR) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(y)
farg2 = sunctx
fresult = swigc_FSUNNonlinSol_Newton(farg1, farg2)
call c_f_pointer(fresult, swig_result)
end function

function FSUNNonlinSol_NewtonSens(count, y, sunctx) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SUNNonlinearSolver), pointer :: swig_result
integer(C_INT), intent(in) :: count
type(N_Vector), target, intent(inout) :: y
type(C_PTR) :: sunctx
type(C_PTR) :: fresult 
integer(C_INT) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = count
farg2 = c_loc(y)
farg3 = sunctx
fresult = swigc_FSUNNonlinSol_NewtonSens(farg1, farg2, farg3)
call c_f_pointer(fresult, swig_result)
end function

function FSUNNonlinSolSetComputeStiffnessRatio_Newton(nls, onoff) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
integer(C_INT), intent(in) :: onoff
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(nls)
farg2 = onoff
fresult = swigc_FSUNNonlinSolSetComputeStiffnessRatio_Newton(farg1, farg2)
swig_result = fresult
end function

function FSUNNonlinSolGetSysFn_Newton(nls, sysfn) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
type(C_FUNPTR), target, intent(inout) :: sysfn
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(nls)
farg2 = c_loc(sysfn)
fresult = swigc_FSUNNonlinSolGetSysFn_Newton(farg1, farg2)
swig_result = fresult
end function

function FSUNNonlinSolGetStiffnessRatio_Newton(nls, stiffr) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNNonlinearSolver), target, intent(inout) :: nls
real(C_DOUBLE), dimension(*), target, intent(inout) :: stiffr
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(nls)
farg2 = c_loc(stiffr(1))
fresult = swigc_FSUNNonlinSolGetStiffnessRatio_Newton(farg1, farg2)
swig_result = fresult
end function


end module
