spack:
  packages:
    all:
      providers:
        target: [x86_64]
        blas:
        - openblas+ilp64
        mpi:
        - openmpi
      compiler:
      - gcc@9.4.0
  specs:
  - cmake %gcc@9.4.0 arch=x86_64
  - openmpi %gcc@9.4.0 arch=x86_64
  - openblas+ilp64 %gcc@9.4.0 arch=x86_64
  - superlu-mt+int64~blas %gcc@9.4.0 arch=x86_64
  config:
    install_tree: /opt/software
  mirrors:
    local: /var/cache/spack-mirror
    E4S: https://cache.e4s.io
  repos: []
  upstreams: {}
  concretization: together
  view: /opt/view
