# -----------------------------------------------------------------
# Programmer(s): Slaven Peles, Cody Balos @ LLNL
# -----------------------------------------------------------------
# SUNDIALS Copyright Start
# Copyright (c) 2002-2021, Lawrence Livermore National Security
# and Southern Methodist University.
# All rights reserved.
#
# See the top-level LICENSE and NOTICE files for details.
#
# SPDX-License-Identifier: BSD-3-Clause
# SUNDIALS Copyright End
# -----------------------------------------------------------------
# Makefile for CVODE documentation
# -----------------------------------------------------------------

USER_GUIDE = cv_guide
EXAMPLES   = cv_examples

# names of guide files
UG_FILES = \
${USER_GUIDE}.tex \
cv_intro.tex \
cv_math.tex \
cv_org.tex \
cv_usage.tex \
cv_fcmix.tex \
cv_gpu.tex \
cv_nvec.tex \
cv_newlinsolv.tex \
cv_sunlinsol.tex \
cv_sunnonlinsol.tex \
cv_sunmem.tex \
cv_constants.tex

EX_FILES = \
${EXAMPLES}.tex \
cv_ex_intro.tex \
cv_ex_serial.tex \
cv_ex_parallel.tex \
cv_ex_parhyp.tex \
cv_ex_fortran.tex \
cv_ex_tests.tex

include ../Makefile.in
