# -----------------------------------------------------------------
# $Revision:  $
# $Date:  $
# -----------------------------------------------------------------
# Programmer(s): Radu Serban @ LLNL
# -----------------------------------------------------------------
# Copyright (c) 2002, The Regents of the University of California.
# Produced at the Lawrence Livermore National Laboratory.
# All rights reserved.
# For details, see sundials/cvode/LICENSE.
# -----------------------------------------------------------------
# Makefile for CVODE documents
# -----------------------------------------------------------------

USER_GUIDE = cv_guide
EXAMPLES   = cv_examples

UG_FILES = \
${USER_GUIDE}.tex \
cv_intro.tex \
cv_install.tex \
cv_math.tex \
cv_usage.tex \
cv_fcmix.tex \
cv_nvec.tex \
cv_org.tex \
cv_newlinsolv.tex \
#cv_linsolv.tex \
cv_constants.tex \

EX_FILES = \
${EXAMPLES}.tex \
cv_ex_intro.tex \
cv_ex_serial.tex \
cv_ex_parallel.tex \
cv_ex_fortran.tex \
cv_ex_codes.tex \
cv_ex_tests.tex   

