if(SUNDIALS_ENABLE_CXX_EXAMPLES)
  if(SUNDIALS_ENABLE_GINKGO)
    add_subdirectory(cpp-ginkgo)
  endif()
  if(SUNDIALS_ENABLE_SUNLINSOL_KOKKOSDENSE)
    add_subdirectory(cpp-kokkos)
    add_subdirectory(cpp-kokkos-2d)
  endif()
  if(SUNDIALS_ENABLE_MAGMA)
    add_subdirectory(cpp-magma)
  endif()
endif()

if(SUNDIALS_ENABLE_FORTRAN_EXAMPLES AND SUNDIALS_INDEX_SIZE MATCHES "64")
  add_subdirectory(fortran)
endif()
