[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "suntools"
version = "7.9.0"
description = "Utilities designed to assist users of the SUNDIALS suite of nonlinear and differential/algebraic equation solvers."
authors = [
  { name = "SUNDIALS Developers", email = "sundials-users@llnl.gov" }
]
license = "BSD-3-Clause"
license-files = ["LICENSE", "NOTICE"]
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent"
]

[project.optional-dependencies]
dev = [
  "ruff",
]

[project.urls]
Homepage = "https://computing.llnl.gov/projects/sundials"
Documentation = "https://sundials.readthedocs.io/"
Source = "https://github.com/LLNL/sundials"

[project.scripts]
suntools = "suntools.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/suntools"]

[tool.hatch.build.targets.sdist]
include = [
  "/src/suntools",
  "/examples",
  "/README.md",
  "/pyproject.toml",
]

[tool.ruff]
line-length = 99

[tool.ruff.format]
skip-magic-trailing-comma = true
