spack:
  packages:
    all:
      providers:
        target: [x86_64]
        blas:
        - openblas
        mpi:
        - openmpi
      compiler:
      - gcc@9.4.0
  specs:
  - cmake arch=x86_64 %gcc@9.4.0
  - petsc~double~int64~superlu-dist~hypre ^openblas arch=x86_64 %gcc@9.4.0
  - openmpi arch=x86_64 %gcc@9.4.0
  - openblas arch=x86_64 %gcc@9.4.0
  - superlu-mt~int64~blas arch=x86_64 %gcc@9.4.0
  - trilinos+float+tpetra gotype=int ^openblas arch=x86_64 %gcc@9.4.0
  config:
    install_tree: /opt/software
  mirrors:
    local: /var/cache/spack-mirror
    E4S: https://cache.e4s.io
  repos: []
  upstreams: {}
  concretization: together
  view:
    default:
      root: /opt/view
      projections:
        superlu-mt: '{name}'
