# -----------------------------------------------------------------
# Programmer(s): Slaven Peles, Cody Balos @ LLNL
# -----------------------------------------------------------------
# SUNDIALS Copyright Start
# Copyright (c) 2002-2021, Lawrence Livermore National Security
# and Southern Methodist University.
# All rights reserved.
#
# See the top-level LICENSE and NOTICE files for details.
#
# SPDX-License-Identifier: BSD-3-Clause
# SUNDIALS Copyright End
# -----------------------------------------------------------------
# Makefile for IDAS developer documentation
# -----------------------------------------------------------------

USER_GUIDE = idas_guide
EXAMPLES   = idas_examples

# names of guide files
UG_FILES = \
${USER_GUIDE}.tex \
idas_intro.tex \
idas_gpu.tex \
idas_math.tex \
idas_org.tex \
idas_sim.tex \
idas_fwd.tex \
idas_adj.tex \
idas_fcmix.tex \
idas_nvec.tex \
idas_newlinsolv.tex \
idas_sunlinsol.tex \
idas_sunmat.tex \
idas_sunnonlinsol.tex \
idas_sunmem.tex \
idas_constants.tex

EX_FILES = \
${EXAMPLES}.tex \
idas_ex_intro.tex \
idas_ex_fwd.tex \
idas_ex_adj.tex

include ../Makefile.in
