# -----------------------------------------------------------------
# Programmer(s): Daniel R. Reynolds @ SMU, Slaven Peles @ LLNL
# -----------------------------------------------------------------
# SUNDIALS Copyright Start
# Copyright (c) 2002-2020, Lawrence Livermore National Security
# and Southern Methodist University.
# All rights reserved.
#
# See the top-level LICENSE and NOTICE files for details.
#
# SPDX-License-Identifier: BSD-3-Clause
# SUNDIALS Copyright End
# -----------------------------------------------------------------
# Sources for ARKode documents
# -----------------------------------------------------------------


USER_GUIDE = ark_guide
EXAMPLES   = ark_examples

UG_FILES = \
${USER_GUIDE}.tex \
ARKode.tex

EX_FILES = \
${EXAMPLES}.tex \
ARKode_example.tex

include ./Makefile.in
