! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! ---------------------------------------------------------------
! Programmer(s): Auto-generated by swig.
! ---------------------------------------------------------------
! SUNDIALS Copyright Start
! Copyright (c) 2002-2023, Lawrence Livermore National Security
! and Southern Methodist University.
! All rights reserved.
!
! See the top-level LICENSE and NOTICE files for details.
!
! SPDX-License-Identifier: BSD-3-Clause
! SUNDIALS Copyright End
! ---------------------------------------------------------------

module fsunadaptcontroller_i_mod
 use, intrinsic :: ISO_C_BINDING
 use fsundials_adaptcontroller_mod
 use fsundials_types_mod
 use fsundials_context_mod
 implicit none
 private

 ! DECLARATION CONSTRUCTS

 integer, parameter :: swig_cmem_own_bit = 0
 integer, parameter :: swig_cmem_rvalue_bit = 1
 integer, parameter :: swig_cmem_const_bit = 2
 type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: cptr = C_NULL_PTR
  integer(C_INT), public :: cmemflags = 0
 end type
 ! struct struct SUNAdaptControllerContent_I_
 type, public :: SUNAdaptControllerContent_I_
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_k1 => swigf_SUNAdaptControllerContent_I__k1_set
  procedure :: get_k1 => swigf_SUNAdaptControllerContent_I__k1_get
  procedure :: set_bias => swigf_SUNAdaptControllerContent_I__bias_set
  procedure :: get_bias => swigf_SUNAdaptControllerContent_I__bias_get
  procedure :: set_p => swigf_SUNAdaptControllerContent_I__p_set
  procedure :: get_p => swigf_SUNAdaptControllerContent_I__p_get
  procedure :: set_pq => swigf_SUNAdaptControllerContent_I__pq_set
  procedure :: get_pq => swigf_SUNAdaptControllerContent_I__pq_get
  procedure :: release => swigf_release_SUNAdaptControllerContent_I_
  procedure, private :: swigf_SUNAdaptControllerContent_I__op_assign__
  generic :: assignment(=) => swigf_SUNAdaptControllerContent_I__op_assign__
 end type SUNAdaptControllerContent_I_
 interface SUNAdaptControllerContent_I_
  module procedure swigf_create_SUNAdaptControllerContent_I_
 end interface
 public :: FSUNAdaptController_I
 public :: FSUNAdaptController_SetParams_I
 public :: FSUNAdaptController_GetType_I
 public :: FSUNAdaptController_EstimateStep_I
 public :: FSUNAdaptController_SetDefaults_I
 public :: FSUNAdaptController_Write_I
 public :: FSUNAdaptController_SetMethodOrder_I
 public :: FSUNAdaptController_SetEmbeddingOrder_I
 public :: FSUNAdaptController_SetErrorBias_I
 public :: FSUNAdaptController_Space_I

! WRAPPER DECLARATIONS
interface
subroutine swigc_SUNAdaptControllerContent_I__k1_set(farg1, farg2) &
bind(C, name="_wrap_SUNAdaptControllerContent_I__k1_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
real(C_DOUBLE), intent(in) :: farg2
end subroutine

function swigc_SUNAdaptControllerContent_I__k1_get(farg1) &
bind(C, name="_wrap_SUNAdaptControllerContent_I__k1_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
real(C_DOUBLE) :: fresult
end function

subroutine swigc_SUNAdaptControllerContent_I__bias_set(farg1, farg2) &
bind(C, name="_wrap_SUNAdaptControllerContent_I__bias_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
real(C_DOUBLE), intent(in) :: farg2
end subroutine

function swigc_SUNAdaptControllerContent_I__bias_get(farg1) &
bind(C, name="_wrap_SUNAdaptControllerContent_I__bias_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
real(C_DOUBLE) :: fresult
end function

subroutine swigc_SUNAdaptControllerContent_I__p_set(farg1, farg2) &
bind(C, name="_wrap_SUNAdaptControllerContent_I__p_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_SUNAdaptControllerContent_I__p_get(farg1) &
bind(C, name="_wrap_SUNAdaptControllerContent_I__p_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_SUNAdaptControllerContent_I__pq_set(farg1, farg2) &
bind(C, name="_wrap_SUNAdaptControllerContent_I__pq_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_SUNAdaptControllerContent_I__pq_get(farg1) &
bind(C, name="_wrap_SUNAdaptControllerContent_I__pq_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

function swigc_new_SUNAdaptControllerContent_I_() &
bind(C, name="_wrap_new_SUNAdaptControllerContent_I_") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_SUNAdaptControllerContent_I_(farg1) &
bind(C, name="_wrap_delete_SUNAdaptControllerContent_I_")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_SUNAdaptControllerContent_I__op_assign__(farg1, farg2) &
bind(C, name="_wrap_SUNAdaptControllerContent_I__op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

function swigc_FSUNAdaptController_I(farg1) &
bind(C, name="_wrap_FSUNAdaptController_I") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(C_PTR), value :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_FSUNAdaptController_SetParams_I(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNAdaptController_SetParams_I") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
real(C_DOUBLE), intent(in) :: farg3
integer(C_INT) :: fresult
end function

function swigc_FSUNAdaptController_GetType_I(farg1) &
bind(C, name="_wrap_FSUNAdaptController_GetType_I") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

function swigc_FSUNAdaptController_EstimateStep_I(farg1, farg2, farg3, farg4) &
bind(C, name="_wrap_FSUNAdaptController_EstimateStep_I") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
real(C_DOUBLE), intent(in) :: farg2
real(C_DOUBLE), intent(in) :: farg3
type(C_PTR), value :: farg4
integer(C_INT) :: fresult
end function

function swigc_FSUNAdaptController_SetDefaults_I(farg1) &
bind(C, name="_wrap_FSUNAdaptController_SetDefaults_I") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

function swigc_FSUNAdaptController_Write_I(farg1, farg2) &
bind(C, name="_wrap_FSUNAdaptController_Write_I") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR), value :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNAdaptController_SetMethodOrder_I(farg1, farg2) &
bind(C, name="_wrap_FSUNAdaptController_SetMethodOrder_I") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNAdaptController_SetEmbeddingOrder_I(farg1, farg2) &
bind(C, name="_wrap_FSUNAdaptController_SetEmbeddingOrder_I") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNAdaptController_SetErrorBias_I(farg1, farg2) &
bind(C, name="_wrap_FSUNAdaptController_SetErrorBias_I") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
real(C_DOUBLE), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNAdaptController_Space_I(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNAdaptController_Space_I") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
integer(C_INT) :: fresult
end function

end interface


contains
 ! MODULE SUBPROGRAMS
subroutine swigf_SUNAdaptControllerContent_I__k1_set(self, k1)
use, intrinsic :: ISO_C_BINDING
class(SUNAdaptControllerContent_I_), intent(in) :: self
real(C_DOUBLE), intent(in) :: k1
type(SwigClassWrapper) :: farg1 
real(C_DOUBLE) :: farg2 

farg1 = self%swigdata
farg2 = k1
call swigc_SUNAdaptControllerContent_I__k1_set(farg1, farg2)
end subroutine

function swigf_SUNAdaptControllerContent_I__k1_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
class(SUNAdaptControllerContent_I_), intent(in) :: self
real(C_DOUBLE) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNAdaptControllerContent_I__k1_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNAdaptControllerContent_I__bias_set(self, bias)
use, intrinsic :: ISO_C_BINDING
class(SUNAdaptControllerContent_I_), intent(in) :: self
real(C_DOUBLE), intent(in) :: bias
type(SwigClassWrapper) :: farg1 
real(C_DOUBLE) :: farg2 

farg1 = self%swigdata
farg2 = bias
call swigc_SUNAdaptControllerContent_I__bias_set(farg1, farg2)
end subroutine

function swigf_SUNAdaptControllerContent_I__bias_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
class(SUNAdaptControllerContent_I_), intent(in) :: self
real(C_DOUBLE) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNAdaptControllerContent_I__bias_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNAdaptControllerContent_I__p_set(self, p)
use, intrinsic :: ISO_C_BINDING
class(SUNAdaptControllerContent_I_), intent(in) :: self
integer(C_INT), intent(in) :: p
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = p
call swigc_SUNAdaptControllerContent_I__p_set(farg1, farg2)
end subroutine

function swigf_SUNAdaptControllerContent_I__p_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(SUNAdaptControllerContent_I_), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNAdaptControllerContent_I__p_get(farg1)
swig_result = fresult
end function

subroutine swigf_SUNAdaptControllerContent_I__pq_set(self, pq)
use, intrinsic :: ISO_C_BINDING
class(SUNAdaptControllerContent_I_), intent(in) :: self
integer(C_INT), intent(in) :: pq
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = pq
call swigc_SUNAdaptControllerContent_I__pq_set(farg1, farg2)
end subroutine

function swigf_SUNAdaptControllerContent_I__pq_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(SUNAdaptControllerContent_I_), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_SUNAdaptControllerContent_I__pq_get(farg1)
swig_result = fresult
end function

function swigf_create_SUNAdaptControllerContent_I_() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(SUNAdaptControllerContent_I_) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_SUNAdaptControllerContent_I_()
self%swigdata = fresult
end function

subroutine swigf_release_SUNAdaptControllerContent_I_(self)
use, intrinsic :: ISO_C_BINDING
class(SUNAdaptControllerContent_I_), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_SUNAdaptControllerContent_I_(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_SUNAdaptControllerContent_I__op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(SUNAdaptControllerContent_I_), intent(inout) :: self
type(SUNAdaptControllerContent_I_), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_SUNAdaptControllerContent_I__op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

function FSUNAdaptController_I(sunctx) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(generic_SUNAdaptController_) :: swig_result
type(C_PTR) :: sunctx
type(SwigClassWrapper) :: fresult 
type(C_PTR) :: farg1 

farg1 = sunctx
fresult = swigc_FSUNAdaptController_I(farg1)
swig_result%swigdata = fresult
end function

function FSUNAdaptController_SetParams_I(c, pq, k1) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(generic_SUNAdaptController_), intent(in) :: c
integer(C_INT), intent(in) :: pq
real(C_DOUBLE), intent(in) :: k1
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 
real(C_DOUBLE) :: farg3 

farg1 = c%swigdata
farg2 = pq
farg3 = k1
fresult = swigc_FSUNAdaptController_SetParams_I(farg1, farg2, farg3)
swig_result = fresult
end function

function FSUNAdaptController_GetType_I(c) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(SUNAdaptController_Type) :: swig_result
class(generic_SUNAdaptController_), intent(in) :: c
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = c%swigdata
fresult = swigc_FSUNAdaptController_GetType_I(farg1)
swig_result = fresult
end function

function FSUNAdaptController_EstimateStep_I(c, h, dsm, hnew) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(generic_SUNAdaptController_), intent(in) :: c
real(C_DOUBLE), intent(in) :: h
real(C_DOUBLE), intent(in) :: dsm
real(C_DOUBLE), dimension(*), target, intent(inout) :: hnew
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
real(C_DOUBLE) :: farg2 
real(C_DOUBLE) :: farg3 
type(C_PTR) :: farg4 

farg1 = c%swigdata
farg2 = h
farg3 = dsm
farg4 = c_loc(hnew(1))
fresult = swigc_FSUNAdaptController_EstimateStep_I(farg1, farg2, farg3, farg4)
swig_result = fresult
end function

function FSUNAdaptController_SetDefaults_I(c) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(generic_SUNAdaptController_), intent(in) :: c
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = c%swigdata
fresult = swigc_FSUNAdaptController_SetDefaults_I(farg1)
swig_result = fresult
end function

function FSUNAdaptController_Write_I(c, fptr) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(generic_SUNAdaptController_), intent(in) :: c
type(C_PTR) :: fptr
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = c%swigdata
farg2 = fptr
fresult = swigc_FSUNAdaptController_Write_I(farg1, farg2)
swig_result = fresult
end function

function FSUNAdaptController_SetMethodOrder_I(c, q) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(generic_SUNAdaptController_), intent(in) :: c
integer(C_INT), intent(in) :: q
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = c%swigdata
farg2 = q
fresult = swigc_FSUNAdaptController_SetMethodOrder_I(farg1, farg2)
swig_result = fresult
end function

function FSUNAdaptController_SetEmbeddingOrder_I(c, p) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(generic_SUNAdaptController_), intent(in) :: c
integer(C_INT), intent(in) :: p
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = c%swigdata
farg2 = p
fresult = swigc_FSUNAdaptController_SetEmbeddingOrder_I(farg1, farg2)
swig_result = fresult
end function

function FSUNAdaptController_SetErrorBias_I(c, bias) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(generic_SUNAdaptController_), intent(in) :: c
real(C_DOUBLE), intent(in) :: bias
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
real(C_DOUBLE) :: farg2 

farg1 = c%swigdata
farg2 = bias
fresult = swigc_FSUNAdaptController_SetErrorBias_I(farg1, farg2)
swig_result = fresult
end function

function FSUNAdaptController_Space_I(c, lenrw, leniw) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(generic_SUNAdaptController_), intent(in) :: c
integer(C_LONG), dimension(*), target, intent(inout) :: lenrw
integer(C_LONG), dimension(*), target, intent(inout) :: leniw
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = c%swigdata
farg2 = c_loc(lenrw(1))
farg3 = c_loc(leniw(1))
fresult = swigc_FSUNAdaptController_Space_I(farg1, farg2, farg3)
swig_result = fresult
end function


end module
