! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! ---------------------------------------------------------------
! Programmer(s): Auto-generated by swig.
! ---------------------------------------------------------------
! SUNDIALS Copyright Start
! Copyright (c) 2002-2023, Lawrence Livermore National Security
! and Southern Methodist University.
! All rights reserved.
!
! See the top-level LICENSE and NOTICE files for details.
!
! SPDX-License-Identifier: BSD-3-Clause
! SUNDIALS Copyright End
! ---------------------------------------------------------------

module fsuncontrol_pid_mod
 use, intrinsic :: ISO_C_BINDING
 use fsundials_control_mod
 use fsundials_types_mod
 use fsundials_context_mod
 implicit none
 private

 ! DECLARATION CONSTRUCTS

 integer, parameter :: swig_cmem_own_bit = 0
 integer, parameter :: swig_cmem_rvalue_bit = 1
 integer, parameter :: swig_cmem_const_bit = 2
 type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: cptr = C_NULL_PTR
  integer(C_INT), public :: cmemflags = 0
 end type
 public :: FSUNControlPID
 public :: FSUNControlPID_SetParams
 public :: FSUNControlGetType_PID
 public :: FSUNControlEstimateStep_PID
 public :: FSUNControlReset_PID
 public :: FSUNControlSetDefaults_PID
 public :: FSUNControlWrite_PID
 public :: FSUNControlSetMethodOrder_PID
 public :: FSUNControlSetEmbeddingOrder_PID
 public :: FSUNControlSetErrorBias_PID
 public :: FSUNControlUpdate_PID
 public :: FSUNControlSpace_PID

! WRAPPER DECLARATIONS
interface
function swigc_FSUNControlPID(farg1) &
bind(C, name="_wrap_FSUNControlPID") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(C_PTR), value :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_FSUNControlPID_SetParams(farg1, farg2, farg3, farg4, farg5) &
bind(C, name="_wrap_FSUNControlPID_SetParams") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
real(C_DOUBLE), intent(in) :: farg3
real(C_DOUBLE), intent(in) :: farg4
real(C_DOUBLE), intent(in) :: farg5
integer(C_INT) :: fresult
end function

function swigc_FSUNControlGetType_PID(farg1) &
bind(C, name="_wrap_FSUNControlGetType_PID") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

function swigc_FSUNControlEstimateStep_PID(farg1, farg2, farg3, farg4) &
bind(C, name="_wrap_FSUNControlEstimateStep_PID") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
real(C_DOUBLE), intent(in) :: farg2
real(C_DOUBLE), intent(in) :: farg3
type(C_PTR), value :: farg4
integer(C_INT) :: fresult
end function

function swigc_FSUNControlReset_PID(farg1) &
bind(C, name="_wrap_FSUNControlReset_PID") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

function swigc_FSUNControlSetDefaults_PID(farg1) &
bind(C, name="_wrap_FSUNControlSetDefaults_PID") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

function swigc_FSUNControlWrite_PID(farg1, farg2) &
bind(C, name="_wrap_FSUNControlWrite_PID") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR), value :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNControlSetMethodOrder_PID(farg1, farg2) &
bind(C, name="_wrap_FSUNControlSetMethodOrder_PID") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNControlSetEmbeddingOrder_PID(farg1, farg2) &
bind(C, name="_wrap_FSUNControlSetEmbeddingOrder_PID") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNControlSetErrorBias_PID(farg1, farg2) &
bind(C, name="_wrap_FSUNControlSetErrorBias_PID") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
real(C_DOUBLE), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNControlUpdate_PID(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNControlUpdate_PID") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
real(C_DOUBLE), intent(in) :: farg2
real(C_DOUBLE), intent(in) :: farg3
integer(C_INT) :: fresult
end function

function swigc_FSUNControlSpace_PID(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNControlSpace_PID") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
integer(C_INT) :: fresult
end function

end interface


contains
 ! MODULE SUBPROGRAMS
function FSUNControlPID(sunctx) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(generic_SUNControl_) :: swig_result
type(C_PTR) :: sunctx
type(SwigClassWrapper) :: fresult 
type(C_PTR) :: farg1 

farg1 = sunctx
fresult = swigc_FSUNControlPID(farg1)
swig_result%swigdata = fresult
end function

function FSUNControlPID_SetParams(c, pq, k1, k2, k3) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(generic_SUNControl_), intent(in) :: c
integer(C_INT), intent(in) :: pq
real(C_DOUBLE), intent(in) :: k1
real(C_DOUBLE), intent(in) :: k2
real(C_DOUBLE), intent(in) :: k3
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 
real(C_DOUBLE) :: farg3 
real(C_DOUBLE) :: farg4 
real(C_DOUBLE) :: farg5 

farg1 = c%swigdata
farg2 = pq
farg3 = k1
farg4 = k2
farg5 = k3
fresult = swigc_FSUNControlPID_SetParams(farg1, farg2, farg3, farg4, farg5)
swig_result = fresult
end function

function FSUNControlGetType_PID(c) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(SUNControl_Type) :: swig_result
class(generic_SUNControl_), intent(in) :: c
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = c%swigdata
fresult = swigc_FSUNControlGetType_PID(farg1)
swig_result = fresult
end function

function FSUNControlEstimateStep_PID(c, h, dsm, hnew) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(generic_SUNControl_), intent(in) :: c
real(C_DOUBLE), intent(in) :: h
real(C_DOUBLE), intent(in) :: dsm
real(C_DOUBLE), dimension(*), target, intent(inout) :: hnew
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
real(C_DOUBLE) :: farg2 
real(C_DOUBLE) :: farg3 
type(C_PTR) :: farg4 

farg1 = c%swigdata
farg2 = h
farg3 = dsm
farg4 = c_loc(hnew(1))
fresult = swigc_FSUNControlEstimateStep_PID(farg1, farg2, farg3, farg4)
swig_result = fresult
end function

function FSUNControlReset_PID(c) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(generic_SUNControl_), intent(in) :: c
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = c%swigdata
fresult = swigc_FSUNControlReset_PID(farg1)
swig_result = fresult
end function

function FSUNControlSetDefaults_PID(c) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(generic_SUNControl_), intent(in) :: c
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = c%swigdata
fresult = swigc_FSUNControlSetDefaults_PID(farg1)
swig_result = fresult
end function

function FSUNControlWrite_PID(c, fptr) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(generic_SUNControl_), intent(in) :: c
type(C_PTR) :: fptr
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = c%swigdata
farg2 = fptr
fresult = swigc_FSUNControlWrite_PID(farg1, farg2)
swig_result = fresult
end function

function FSUNControlSetMethodOrder_PID(c, q) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(generic_SUNControl_), intent(in) :: c
integer(C_INT), intent(in) :: q
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = c%swigdata
farg2 = q
fresult = swigc_FSUNControlSetMethodOrder_PID(farg1, farg2)
swig_result = fresult
end function

function FSUNControlSetEmbeddingOrder_PID(c, p) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(generic_SUNControl_), intent(in) :: c
integer(C_INT), intent(in) :: p
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = c%swigdata
farg2 = p
fresult = swigc_FSUNControlSetEmbeddingOrder_PID(farg1, farg2)
swig_result = fresult
end function

function FSUNControlSetErrorBias_PID(c, bias) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(generic_SUNControl_), intent(in) :: c
real(C_DOUBLE), intent(in) :: bias
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
real(C_DOUBLE) :: farg2 

farg1 = c%swigdata
farg2 = bias
fresult = swigc_FSUNControlSetErrorBias_PID(farg1, farg2)
swig_result = fresult
end function

function FSUNControlUpdate_PID(c, h, dsm) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(generic_SUNControl_), intent(in) :: c
real(C_DOUBLE), intent(in) :: h
real(C_DOUBLE), intent(in) :: dsm
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
real(C_DOUBLE) :: farg2 
real(C_DOUBLE) :: farg3 

farg1 = c%swigdata
farg2 = h
farg3 = dsm
fresult = swigc_FSUNControlUpdate_PID(farg1, farg2, farg3)
swig_result = fresult
end function

function FSUNControlSpace_PID(c, lenrw, leniw) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(generic_SUNControl_), intent(in) :: c
integer(C_LONG), dimension(*), target, intent(inout) :: lenrw
integer(C_LONG), dimension(*), target, intent(inout) :: leniw
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = c%swigdata
farg2 = c_loc(lenrw(1))
farg3 = c_loc(leniw(1))
fresult = swigc_FSUNControlSpace_PID(farg1, farg2, farg3)
swig_result = fresult
end function


end module
