workflow:
  name: '$GITHUB_PIPELINE_NAME'

stages:
  - build-and-test

# sync:
#   stage: sync
#   variables:
#     GIT_STRATEGY: none
#     GITHUB_TOKEN: $GITHUB_TOKEN
#     GITLAB_SSH_KEY_BASE64: $GITLAB_SSH_KEY_BASE64
#   script:
#     - wget https://raw.githubusercontent.com/spack/spack-infrastructure/refs/heads/main/images/gh-gl-sync/SpackCIBridge.py
#     - wget https://raw.githubusercontent.com/spack/spack-infrastructure/refs/heads/main/images/gh-gl-sync/requirements.txt
#     - pip3 install -r requirements.txt
#     - pip3 install requests==2.32.2
#     - python3 ./SpackCIBridge.py "llnl/sundials" "ssh://git@ssh.gitlab.spack.io/sundials/sundials" "https://gitlab.spack.io" "sundials/sundials"

.build-and-test:
  stage: build-and-test
  variables:
    GIT_STRATEGY: fetch
    GIT_DEPTH: 1
    GIT_SUBMODULE_STRATEGY: recursive
    SPACK_REF: "2e2169d5282d166f63e3ee4db8d4446c43cefa8a" # v1.1.1
    BUILD_ROOT: ${CI_PROJECT_DIR}
    TEMP_PREFIX: /tmp
    BUILDCACHE_ROOT:
    GPG_KEY_PREFIX:
  before_script:
    - apt-get update && apt-get install -y git cmake python3
    
nvidia-grace-cuda-12.8:
  extends: [.build-and-test]
  tags: [grace]
  image: nvcr.io/nvidia/cuda:12.8.0-devel-ubuntu24.04
  variables:
    SPEC: "%c,cxx,fortran=nvhpc"
    SPACK_YAML: scripts/spack/environments/ubuntu_2404_nvidia/spack.yaml
  script:
    - .gitlab/build_and_test.sh

nvidia-grace-hopper-cuda-12.8:
  extends: [.build-and-test]
  tags: [nvidia-gh200]
  image: nvcr.io/nvidia/cuda:12.8.0-devel-ubuntu24.04
  variables:
    SPEC: "+cuda cuda_arch=90 %c,cxx,fortran=nvhpc"
    SPACK_YAML: scripts/spack/environments/ubuntu_2404_nvidia/spack.yaml
  script:
    - .gitlab/build_and_test.sh

intel-pvc:
  extends: [.build-and-test]
  tags: [intel-data-center-max-1100]
  image: intel/oneapi-basekit:2025.3.0-0-devel-ubuntu24.04
  variables:
    SPEC: "+sycl %c,cxx,fortran=oneapi"
    SPACK_YAML: scripts/spack/environments/ubuntu_2404_oneapi/spack.yaml
  script:
    - sycl-ls
    - export ONEAPI_DEVICE_SELECTOR=level_zero:gpu
    - .gitlab/build_and_test.sh
