#!/bin/sh

tarfile=$1
distrobase=$2
doc=$3

shift 3
tar=$*

echo "   --- Add arkode module to $tarfile"

if [ $doc = "T" ]; then
$tar $tarfile $distrobase/doc/arkode/ARKode.pdf
$tar $tarfile $distrobase/doc/arkode/ARKode_example.pdf
fi

$tar $tarfile $distrobase/include/arkode/arkode.h
$tar $tarfile $distrobase/include/arkode/arkode_band.h
$tar $tarfile $distrobase/include/arkode/arkode_bandpre.h
$tar $tarfile $distrobase/include/arkode/arkode_bbdpre.h
$tar $tarfile $distrobase/include/arkode/arkode_dense.h
$tar $tarfile $distrobase/include/arkode/arkode_direct.h
$tar $tarfile $distrobase/include/arkode/arkode_klu.h
$tar $tarfile $distrobase/include/arkode/arkode_lapack.h
$tar $tarfile $distrobase/include/arkode/arkode_pcg.h
$tar $tarfile $distrobase/include/arkode/arkode_sparse.h
$tar $tarfile $distrobase/include/arkode/arkode_spbcgs.h
$tar $tarfile $distrobase/include/arkode/arkode_spfgmr.h
$tar $tarfile $distrobase/include/arkode/arkode_spgmr.h
$tar $tarfile $distrobase/include/arkode/arkode_spils.h
$tar $tarfile $distrobase/include/arkode/arkode_sptfqmr.h
$tar $tarfile $distrobase/include/arkode/arkode_superlumt.h

$tar $tarfile $distrobase/src/arkode/LICENSE
$tar $tarfile $distrobase/src/arkode/README
$tar $tarfile $distrobase/src/arkode/CMakeLists.txt

$tar $tarfile $distrobase/src/arkode/arkode.c
$tar $tarfile $distrobase/src/arkode/arkode_band.c
$tar $tarfile $distrobase/src/arkode/arkode_bandpre.c
$tar $tarfile $distrobase/src/arkode/arkode_bandpre_impl.h
$tar $tarfile $distrobase/src/arkode/arkode_bbdpre.c
$tar $tarfile $distrobase/src/arkode/arkode_bbdpre_impl.h
$tar $tarfile $distrobase/src/arkode/arkode_butcher.c
$tar $tarfile $distrobase/src/arkode/arkode_dense.c
$tar $tarfile $distrobase/src/arkode/arkode_direct.c
$tar $tarfile $distrobase/src/arkode/arkode_direct_impl.h
$tar $tarfile $distrobase/src/arkode/arkode_impl.h
$tar $tarfile $distrobase/src/arkode/arkode_io.c
$tar $tarfile $distrobase/src/arkode/arkode_klu.c
$tar $tarfile $distrobase/src/arkode/arkode_lapack.c
$tar $tarfile $distrobase/src/arkode/arkode_pcg.c
$tar $tarfile $distrobase/src/arkode/arkode_sparse.c
$tar $tarfile $distrobase/src/arkode/arkode_sparse_impl.h
$tar $tarfile $distrobase/src/arkode/arkode_spbcgs.c
$tar $tarfile $distrobase/src/arkode/arkode_spfgmr.c
$tar $tarfile $distrobase/src/arkode/arkode_spgmr.c
$tar $tarfile $distrobase/src/arkode/arkode_spils.c
$tar $tarfile $distrobase/src/arkode/arkode_spils_impl.h
$tar $tarfile $distrobase/src/arkode/arkode_sptfqmr.c
$tar $tarfile $distrobase/src/arkode/arkode_superlumt.c

echo "   --- Add farkode module to $tarfile"

$tar $tarfile $distrobase/src/arkode/fcmix/CMakeLists.txt

$tar $tarfile $distrobase/src/arkode/fcmix/farkadapt.c
$tar $tarfile $distrobase/src/arkode/fcmix/farkband.c
$tar $tarfile $distrobase/src/arkode/fcmix/farkbandmass.c
$tar $tarfile $distrobase/src/arkode/fcmix/farkbbd.c
$tar $tarfile $distrobase/src/arkode/fcmix/farkbbd.h
$tar $tarfile $distrobase/src/arkode/fcmix/farkbp.c
$tar $tarfile $distrobase/src/arkode/fcmix/farkbp.h
$tar $tarfile $distrobase/src/arkode/fcmix/farkdense.c
$tar $tarfile $distrobase/src/arkode/fcmix/farkdensemass.c
$tar $tarfile $distrobase/src/arkode/fcmix/farkewt.c
$tar $tarfile $distrobase/src/arkode/fcmix/farkexpstab.c
$tar $tarfile $distrobase/src/arkode/fcmix/farkjtimes.c
$tar $tarfile $distrobase/src/arkode/fcmix/farkklu.c
$tar $tarfile $distrobase/src/arkode/fcmix/farklapack.c
$tar $tarfile $distrobase/src/arkode/fcmix/farklapband.c
$tar $tarfile $distrobase/src/arkode/fcmix/farklapbandmass.c
$tar $tarfile $distrobase/src/arkode/fcmix/farklapdense.c
$tar $tarfile $distrobase/src/arkode/fcmix/farklapdensemass.c
$tar $tarfile $distrobase/src/arkode/fcmix/farkmasspreco.c
$tar $tarfile $distrobase/src/arkode/fcmix/farkmtimes.c
$tar $tarfile $distrobase/src/arkode/fcmix/farkode.c
$tar $tarfile $distrobase/src/arkode/fcmix/farkode.h
$tar $tarfile $distrobase/src/arkode/fcmix/farkpreco.c
$tar $tarfile $distrobase/src/arkode/fcmix/farkroot.c
$tar $tarfile $distrobase/src/arkode/fcmix/farkroot.h
$tar $tarfile $distrobase/src/arkode/fcmix/farksparse.c
$tar $tarfile $distrobase/src/arkode/fcmix/farksparsemass.c
$tar $tarfile $distrobase/src/arkode/fcmix/farksuperlumt.c

echo "   --- Add arkode examples to $tarfile"

$tar $tarfile $distrobase/examples/arkode/C_openmp/CMakeLists.txt
$tar $tarfile $distrobase/examples/arkode/C_openmp/README
$tar $tarfile $distrobase/examples/arkode/C_openmp/ark_brusselator1D_omp.c
$tar $tarfile $distrobase/examples/arkode/C_openmp/ark_brusselator1D_omp.out
$tar $tarfile $distrobase/examples/arkode/C_openmp/plot_brusselator1D.py

$tar $tarfile $distrobase/examples/arkode/CXX_parallel/CMakeLists.txt
$tar $tarfile $distrobase/examples/arkode/CXX_parallel/README
$tar $tarfile $distrobase/examples/arkode/CXX_parallel/ark_heat2D.cpp
$tar $tarfile $distrobase/examples/arkode/CXX_parallel/ark_heat2D.out
$tar $tarfile $distrobase/examples/arkode/CXX_parallel/plot_heat2D.py

$tar $tarfile $distrobase/examples/arkode/CXX_serial/CMakeLists.txt
$tar $tarfile $distrobase/examples/arkode/CXX_serial/README
$tar $tarfile $distrobase/examples/arkode/CXX_serial/ark_analytic_sys.cpp
$tar $tarfile $distrobase/examples/arkode/CXX_serial/ark_analytic_sys.out
$tar $tarfile $distrobase/examples/arkode/CXX_serial/plot_sol.py

$tar $tarfile $distrobase/examples/arkode/C_parallel/CMakeLists.txt
$tar $tarfile $distrobase/examples/arkode/C_parallel/README
$tar $tarfile $distrobase/examples/arkode/C_parallel/ark_diurnal_kry_bbd_p.c
$tar $tarfile $distrobase/examples/arkode/C_parallel/ark_diurnal_kry_bbd_p.out
$tar $tarfile $distrobase/examples/arkode/C_parallel/ark_diurnal_kry_p.c
$tar $tarfile $distrobase/examples/arkode/C_parallel/ark_diurnal_kry_p.out

$tar $tarfile $distrobase/examples/arkode/C_serial/CMakeLists.txt
$tar $tarfile $distrobase/examples/arkode/C_serial/README
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_analytic.c
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_analytic.out
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_analytic_nonlin.c
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_analytic_nonlin.out
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_brusselator.c
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_brusselator.out
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_brusselator1D.c
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_brusselator1D.out
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_brusselator1D_FEM_slu.c
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_brusselator1D_FEM_slu.out
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_brusselator1D_klu.c
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_brusselator1D_klu.out
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_brusselator_fp.c
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_brusselator_fp.out
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_heat1D.c
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_heat1D.out
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_heat1D_adapt.c
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_heat1D_adapt.out
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_KrylovDemo_prec.c
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_KrylovDemo_prec.out
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_robertson.c
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_robertson.out
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_robertson_root.c
$tar $tarfile $distrobase/examples/arkode/C_serial/ark_robertson_root.out
$tar $tarfile $distrobase/examples/arkode/C_serial/bruss_plots.m
$tar $tarfile $distrobase/examples/arkode/C_serial/plot_brusselator1D.py
$tar $tarfile $distrobase/examples/arkode/C_serial/plot_brusselator1D_FEM.py
$tar $tarfile $distrobase/examples/arkode/C_serial/plot_heat1D.py
$tar $tarfile $distrobase/examples/arkode/C_serial/plot_heat1D_adapt.py
$tar $tarfile $distrobase/examples/arkode/C_serial/plot_sol.py
$tar $tarfile $distrobase/examples/arkode/C_serial/plot_sol_log.py

$tar $tarfile $distrobase/examples/arkode/F77_parallel/CMakeLists.txt
$tar $tarfile $distrobase/examples/arkode/F77_parallel/README
$tar $tarfile $distrobase/examples/arkode/F77_parallel/fark_diag_kry_bbd_p.f
$tar $tarfile $distrobase/examples/arkode/F77_parallel/fark_diag_kry_bbd_p.out
$tar $tarfile $distrobase/examples/arkode/F77_parallel/fark_diag_non_p.f
$tar $tarfile $distrobase/examples/arkode/F77_parallel/fark_diag_non_p.out

$tar $tarfile $distrobase/examples/arkode/F77_serial/CMakeLists.txt
$tar $tarfile $distrobase/examples/arkode/F77_serial/README
$tar $tarfile $distrobase/examples/arkode/F77_serial/fark_diurnal_kry_bp.f
$tar $tarfile $distrobase/examples/arkode/F77_serial/fark_diurnal_kry_bp.out
$tar $tarfile $distrobase/examples/arkode/F77_serial/fark_roberts_dnsL.f
$tar $tarfile $distrobase/examples/arkode/F77_serial/fark_roberts_dnsL.out

$tar $tarfile $distrobase/examples/arkode/F90_parallel/CMakeLists.txt
$tar $tarfile $distrobase/examples/arkode/F90_parallel/README
$tar $tarfile $distrobase/examples/arkode/F90_parallel/fark_heat2D.f90
$tar $tarfile $distrobase/examples/arkode/F90_parallel/fark_heat2D.out
$tar $tarfile $distrobase/examples/arkode/F90_parallel/plot_heat2D.py

$tar $tarfile $distrobase/examples/arkode/F90_serial/CMakeLists.txt
$tar $tarfile $distrobase/examples/arkode/F90_serial/README
$tar $tarfile $distrobase/examples/arkode/F90_serial/ark_bruss.f90
$tar $tarfile $distrobase/examples/arkode/F90_serial/ark_bruss.out
$tar $tarfile $distrobase/examples/arkode/F90_serial/plot_sol.py

# 3/3/2015:LEBanks - Don't add to release yet. Many tests will fail, which can be confusing to users
#echo "   --- Add regression test files to $tarfile"
#$tar $tarfile $distrobase/test/answers/ark_analytic
#$tar $tarfile $distrobase/test/answers/ark_analytic_nonlin
#$tar $tarfile $distrobase/test/answers/ark_analytic_sys
#$tar $tarfile $distrobase/test/answers/ark_bruss
#$tar $tarfile $distrobase/test/answers/ark_brusselator
#$tar $tarfile $distrobase/test/answers/ark_brusselator1D
#$tar $tarfile $distrobase/test/answers/ark_brusselator1D_FEM_slu
#$tar $tarfile $distrobase/test/answers/ark_brusselator1D_klu
#$tar $tarfile $distrobase/test/answers/ark_brusselator1D_omp
#$tar $tarfile $distrobase/test/answers/ark_brusselator_fp
#$tar $tarfile $distrobase/test/answers/ark_diurnal_kry_bbd_p
#$tar $tarfile $distrobase/test/answers/ark_diurnal_kry_p
#$tar $tarfile $distrobase/test/answers/ark_heat1D
#$tar $tarfile $distrobase/test/answers/ark_heat1D_adapt
#$tar $tarfile $distrobase/test/answers/ark_heat2D
#$tar $tarfile $distrobase/test/answers/ark_KrylovDemo_prec
#$tar $tarfile $distrobase/test/answers/ark_robertson
#$tar $tarfile $distrobase/test/answers/ark_robertson_root
#$tar $tarfile $distrobase/test/answers/fark_diag_kry_bbd_p
#$tar $tarfile $distrobase/test/answers/fark_diag_non_p
#$tar $tarfile $distrobase/test/answers/fark_diurnal_kry_bp
#$tar $tarfile $distrobase/test/answers/fark_heat2D
#$tar $tarfile $distrobase/test/answers/fark_roberts_dnsL

