#!/bin/sh

tarfile=$1
distrobase=$2
doc=$3

shift 3
tar=$*

echo "   --- Add cpodes module to $tarfile"

#if [ $doc = "T" ]; then
#$tar $tarfile $distrobase/doc/cpodes/cps_guide.ps
#$tar $tarfile $distrobase/doc/cpodes/cps_guide.pdf
#$tar $tarfile $distrobase/doc/cpodes/cps_examples.ps
#$tar $tarfile $distrobase/doc/cpodes/cps_examples.pdf
#fi

$tar $tarfile $distrobase/include/cpodes/cpodes.h
$tar $tarfile $distrobase/include/cpodes/cpodes_direct.h
$tar $tarfile $distrobase/include/cpodes/cpodes_dense.h
$tar $tarfile $distrobase/include/cpodes/cpodes_band.h
$tar $tarfile $distrobase/include/cpodes/cpodes_lapack.h
$tar $tarfile $distrobase/include/cpodes/cpodes_spgmr.h
$tar $tarfile $distrobase/include/cpodes/cpodes_spbcgs.h
$tar $tarfile $distrobase/include/cpodes/cpodes_sptfqmr.h
$tar $tarfile $distrobase/include/cpodes/cpodes_spils.h
$tar $tarfile $distrobase/include/cpodes/cpodes_bandpre.h
$tar $tarfile $distrobase/include/cpodes/cpodes_bbdpre.h

$tar $tarfile $distrobase/src/cpodes/LICENSE
$tar $tarfile $distrobase/src/cpodes/NOTICE
$tar $tarfile $distrobase/src/cpodes/README
$tar $tarfile $distrobase/src/cpodes/CMakeLists.txt

$tar $tarfile $distrobase/src/cpodes/cpodes.c
$tar $tarfile $distrobase/src/cpodes/cpodes_nls.c
$tar $tarfile $distrobase/src/cpodes/cpodes_proj.c
$tar $tarfile $distrobase/src/cpodes/cpodes_root.c
$tar $tarfile $distrobase/src/cpodes/cpodes_io.c
$tar $tarfile $distrobase/src/cpodes/cpodes_ic.c
$tar $tarfile $distrobase/src/cpodes/cpodes_direct.c
$tar $tarfile $distrobase/src/cpodes/cpodes_dense.c
$tar $tarfile $distrobase/src/cpodes/cpodes_band.c
$tar $tarfile $distrobase/src/cpodes/cpodes_lapack.c
$tar $tarfile $distrobase/src/cpodes/cpodes_spils.c
$tar $tarfile $distrobase/src/cpodes/cpodes_spgmr.c
$tar $tarfile $distrobase/src/cpodes/cpodes_spbcgs.c
$tar $tarfile $distrobase/src/cpodes/cpodes_sptfqmr.c
$tar $tarfile $distrobase/src/cpodes/cpodes_bandpre.c
$tar $tarfile $distrobase/src/cpodes/cpodes_bbdpre.c
$tar $tarfile $distrobase/src/cpodes/cpodes_private.h
$tar $tarfile $distrobase/src/cpodes/cpodes_impl.h
$tar $tarfile $distrobase/src/cpodes/cpodes_direct_impl.h
$tar $tarfile $distrobase/src/cpodes/cpodes_spils_impl.h
$tar $tarfile $distrobase/src/cpodes/cpodes_bandpre_impl.h
$tar $tarfile $distrobase/src/cpodes/cpodes_bbdpre_impl.h

echo "   --- Add cpodes examples to $tarfile"

$tar $tarfile $distrobase/examples/cpodes/CMakeLists.txt

$tar $tarfile $distrobase/examples/cpodes/serial/README
$tar $tarfile $distrobase/examples/cpodes/serial/CMakeLists.txt
$tar $tarfile $distrobase/examples/cpodes/serial/cpsAdvDiff_bnd.c
$tar $tarfile $distrobase/examples/cpodes/serial/cpsAdvDiff_bndL.c
$tar $tarfile $distrobase/examples/cpodes/serial/cpsAdvDiff_non.c
$tar $tarfile $distrobase/examples/cpodes/serial/cpsAkzoNob_dnsL.c
$tar $tarfile $distrobase/examples/cpodes/serial/cpsNewtCrd_dns.c
$tar $tarfile $distrobase/examples/cpodes/serial/cpsPend_dns.c
$tar $tarfile $distrobase/examples/cpodes/serial/cpsPend_dnsL.c
$tar $tarfile $distrobase/examples/cpodes/serial/cpsRoberts_dns.c
$tar $tarfile $distrobase/examples/cpodes/serial/cpsRoberts_dnsL.c
$tar $tarfile $distrobase/examples/cpodes/serial/cpsSlCrank_dns.c
$tar $tarfile $distrobase/examples/cpodes/serial/cpsVanDPol_non.c

$tar $tarfile $distrobase/examples/cpodes/parallel/README
$tar $tarfile $distrobase/examples/cpodes/parallel/CMakeLists.txt
$tar $tarfile $distrobase/examples/cpodes/parallel/cpsHeat2D_kry_bbd_p.c
$tar $tarfile $distrobase/examples/cpodes/parallel/cpsHeat2D_kry_bbd_p.out

