#!/bin/sh

tarfile=$1
distrobase=$2
doc=$3

echo "   --- Add cpodes module to $tarfile"

#if [ $doc = "T" ]; then
#tar ufv $tarfile $distrobase/doc/cpodes/cps_guide.ps
#tar ufv $tarfile $distrobase/doc/cpodes/cps_guide.pdf
#tar ufv $tarfile $distrobase/doc/cpodes/cps_examples.ps
#tar ufv $tarfile $distrobase/doc/cpodes/cps_examples.pdf
#fi

tar ufv $tarfile $distrobase/include/cpodes/cpodes.h
tar ufv $tarfile $distrobase/include/cpodes/cpodes_direct.h
tar ufv $tarfile $distrobase/include/cpodes/cpodes_dense.h
tar ufv $tarfile $distrobase/include/cpodes/cpodes_band.h
tar ufv $tarfile $distrobase/include/cpodes/cpodes_lapack.h
tar ufv $tarfile $distrobase/include/cpodes/cpodes_spgmr.h
tar ufv $tarfile $distrobase/include/cpodes/cpodes_spbcgs.h
tar ufv $tarfile $distrobase/include/cpodes/cpodes_sptfqmr.h
tar ufv $tarfile $distrobase/include/cpodes/cpodes_spils.h
tar ufv $tarfile $distrobase/include/cpodes/cpodes_bandpre.h
tar ufv $tarfile $distrobase/include/cpodes/cpodes_bbdpre.h

tar ufv $tarfile $distrobase/src/cpodes/LICENSE
tar ufv $tarfile $distrobase/src/cpodes/README
tar ufv $tarfile $distrobase/src/cpodes/Makefile.in
tar ufv $tarfile $distrobase/src/cpodes/CMakeLists.txt

tar ufv $tarfile $distrobase/src/cpodes/cpodes.c
tar ufv $tarfile $distrobase/src/cpodes/cpodes_nls.c
tar ufv $tarfile $distrobase/src/cpodes/cpodes_proj.c
tar ufv $tarfile $distrobase/src/cpodes/cpodes_root.c
tar ufv $tarfile $distrobase/src/cpodes/cpodes_io.c
tar ufv $tarfile $distrobase/src/cpodes/cpodes_ic.c
tar ufv $tarfile $distrobase/src/cpodes/cpodes_direct.c
tar ufv $tarfile $distrobase/src/cpodes/cpodes_dense.c
tar ufv $tarfile $distrobase/src/cpodes/cpodes_band.c
tar ufv $tarfile $distrobase/src/cpodes/cpodes_lapack.c
tar ufv $tarfile $distrobase/src/cpodes/cpodes_spils.c
tar ufv $tarfile $distrobase/src/cpodes/cpodes_spgmr.c
tar ufv $tarfile $distrobase/src/cpodes/cpodes_spbcgs.c
tar ufv $tarfile $distrobase/src/cpodes/cpodes_sptfqmr.c
tar ufv $tarfile $distrobase/src/cpodes/cpodes_bandpre.c
tar ufv $tarfile $distrobase/src/cpodes/cpodes_bbdpre.c
tar ufv $tarfile $distrobase/src/cpodes/cpodes_private.h
tar ufv $tarfile $distrobase/src/cpodes/cpodes_impl.h
tar ufv $tarfile $distrobase/src/cpodes/cpodes_direct_impl.h
tar ufv $tarfile $distrobase/src/cpodes/cpodes_spils_impl.h
tar ufv $tarfile $distrobase/src/cpodes/cpodes_bandpre_impl.h
tar ufv $tarfile $distrobase/src/cpodes/cpodes_bbdpre_impl.h

echo "   --- Add cpodes examples to $tarfile"

tar ufv $tarfile $distrobase/examples/cpodes/serial/README
tar ufv $tarfile $distrobase/examples/cpodes/serial/Makefile.in
tar ufv $tarfile $distrobase/examples/cpodes/serial/CMakeLists.txt
tar ufv $tarfile $distrobase/examples/cpodes/serial/cpsAdvDiff_bnd.c
tar ufv $tarfile $distrobase/examples/cpodes/serial/cpsAdvDiff_bndL.c
tar ufv $tarfile $distrobase/examples/cpodes/serial/cpsAdvDiff_non.c
tar ufv $tarfile $distrobase/examples/cpodes/serial/cpsAkzoNob_dnsL.c
tar ufv $tarfile $distrobase/examples/cpodes/serial/cpsNewtCrd_dns.c
tar ufv $tarfile $distrobase/examples/cpodes/serial/cpsPend_dns.c
tar ufv $tarfile $distrobase/examples/cpodes/serial/cpsPend_dnsL.c
tar ufv $tarfile $distrobase/examples/cpodes/serial/cpsRoberts_dns.c
tar ufv $tarfile $distrobase/examples/cpodes/serial/cpsRoberts_dnsL.c
tar ufv $tarfile $distrobase/examples/cpodes/serial/cpsSlCrank_dns.c
tar ufv $tarfile $distrobase/examples/cpodes/serial/cpsVanDPol_non.c

tar ufv $tarfile $distrobase/examples/cpodes/parallel/README
tar ufv $tarfile $distrobase/examples/cpodes/parallel/CMakeLists.txt
tar ufv $tarfile $distrobase/examples/cpodes/parallel/Makefile_ex.in
tar ufv $tarfile $distrobase/examples/cpodes/parallel/cpsHeat2D_kry_bbd_p.c
tar ufv $tarfile $distrobase/examples/cpodes/parallel/cpsHeat2D_kry_bbd_p.out

