#!/bin/sh

tarfile=$1
distrobase=$2
par=$3

echo ""
echo "  Generate cvode documentation"
cd $distrobase/cvode/doc
make QUIET=-q ug_pdf
make QUIET=-q ex_pdf
cd -

echo "  Add cvode module"

tar uf $tarfile $distrobase/cvode/LICENSE
tar uf $tarfile $distrobase/cvode/README

tar uf $tarfile $distrobase/cvode/doc/cv_guide.ps
tar uf $tarfile $distrobase/cvode/doc/cv_guide.pdf
tar uf $tarfile $distrobase/cvode/doc/cv_examples.ps
tar uf $tarfile $distrobase/cvode/doc/cv_examples.pdf

tar uf $tarfile $distrobase/cvode/include/cvode.h
tar uf $tarfile $distrobase/cvode/include/cvdense.h
tar uf $tarfile $distrobase/cvode/include/cvband.h
tar uf $tarfile $distrobase/cvode/include/cvdiag.h
tar uf $tarfile $distrobase/cvode/include/cvspgmr.h
tar uf $tarfile $distrobase/cvode/include/cvspbcg.h
tar uf $tarfile $distrobase/cvode/include/cvsptfqmr.h
tar uf $tarfile $distrobase/cvode/include/cvspils.h
tar uf $tarfile $distrobase/cvode/include/cvbandpre.h
tar uf $tarfile $distrobase/cvode/include/cvbbdpre.h

tar uf $tarfile $distrobase/cvode/source/Makefile.in
tar uf $tarfile $distrobase/cvode/source/cvode.c
tar uf $tarfile $distrobase/cvode/source/cvodeio.c
tar uf $tarfile $distrobase/cvode/source/cvdense.c
tar uf $tarfile $distrobase/cvode/source/cvband.c
tar uf $tarfile $distrobase/cvode/source/cvdiag.c
tar uf $tarfile $distrobase/cvode/source/cvspgmr.c
tar uf $tarfile $distrobase/cvode/source/cvspbcg.c
tar uf $tarfile $distrobase/cvode/source/cvsptfqmr.c
tar uf $tarfile $distrobase/cvode/source/cvbandpre.c
tar uf $tarfile $distrobase/cvode/source/cvbbdpre.c
tar uf $tarfile $distrobase/cvode/source/cvode_impl.h
tar uf $tarfile $distrobase/cvode/source/cvdense_impl.h
tar uf $tarfile $distrobase/cvode/source/cvband_impl.h
tar uf $tarfile $distrobase/cvode/source/cvdiag_impl.h
tar uf $tarfile $distrobase/cvode/source/cvspgmr_impl.h
tar uf $tarfile $distrobase/cvode/source/cvspbcg_impl.h
tar uf $tarfile $distrobase/cvode/source/cvsptfqmr_impl.h
tar uf $tarfile $distrobase/cvode/source/cvbandpre_impl.h
tar uf $tarfile $distrobase/cvode/source/cvbbdpre_impl.h

tar uf $tarfile $distrobase/cvode/fcmix/Makefile.in
tar uf $tarfile $distrobase/cvode/fcmix/fcvode.h
tar uf $tarfile $distrobase/cvode/fcmix/fcvode.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvewt.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvpreco.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvjtimes.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvband.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvdense.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvbp.h
tar uf $tarfile $distrobase/cvode/fcmix/fcvbp.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvbbd.h
tar uf $tarfile $distrobase/cvode/fcmix/fcvbbd.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvroot.h
tar uf $tarfile $distrobase/cvode/fcmix/fcvroot.c

tar uf $tarfile $distrobase/cvode/examples_ser/README
tar uf $tarfile $distrobase/cvode/examples_ser/Makefile.in
tar uf $tarfile $distrobase/cvode/examples_ser/cvdx.c
tar uf $tarfile $distrobase/cvode/examples_ser/cvdx.out
tar uf $tarfile $distrobase/cvode/examples_ser/cvdxe.c
tar uf $tarfile $distrobase/cvode/examples_ser/cvdxe.out
tar uf $tarfile $distrobase/cvode/examples_ser/cvbx.c
tar uf $tarfile $distrobase/cvode/examples_ser/cvbx.out
tar uf $tarfile $distrobase/cvode/examples_ser/cvkx.c
tar uf $tarfile $distrobase/cvode/examples_ser/cvkx.out
tar uf $tarfile $distrobase/cvode/examples_ser/cvkxb.c
tar uf $tarfile $distrobase/cvode/examples_ser/cvkxb.out
tar uf $tarfile $distrobase/cvode/examples_ser/cvdemd.c
tar uf $tarfile $distrobase/cvode/examples_ser/cvdemd.out
tar uf $tarfile $distrobase/cvode/examples_ser/cvdemk.c
tar uf $tarfile $distrobase/cvode/examples_ser/cvdemk.out

tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/README
tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/Makefile.in
tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/cvdensef.f
tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/cvdensef.out
tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/cvbandf.f
tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/cvbandf.out
tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/cvkryf.f
tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/cvkryf.out
tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/cvkrybf.f
tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/cvkrybf.out

if [ $par = "T" ]
then
    tar uf $tarfile $distrobase/cvode/examples_par/README
    tar uf $tarfile $distrobase/cvode/examples_par/Makefile.in
    tar uf $tarfile $distrobase/cvode/examples_par/pvnx.c
    tar uf $tarfile $distrobase/cvode/examples_par/pvnx.out
    tar uf $tarfile $distrobase/cvode/examples_par/pvkx.c
    tar uf $tarfile $distrobase/cvode/examples_par/pvkx.out
    tar uf $tarfile $distrobase/cvode/examples_par/pvkxb.c
    tar uf $tarfile $distrobase/cvode/examples_par/pvkxb.out

    tar uf $tarfile $distrobase/cvode/fcmix/examples_par/README
    tar uf $tarfile $distrobase/cvode/fcmix/examples_par/Makefile.in
    tar uf $tarfile $distrobase/cvode/fcmix/examples_par/pvdiagnf.f
    tar uf $tarfile $distrobase/cvode/fcmix/examples_par/pvdiagnf.out
    tar uf $tarfile $distrobase/cvode/fcmix/examples_par/pvdiagkf.f
    tar uf $tarfile $distrobase/cvode/fcmix/examples_par/pvdiagkf.out
    tar uf $tarfile $distrobase/cvode/fcmix/examples_par/pvdiagkbf.f
    tar uf $tarfile $distrobase/cvode/fcmix/examples_par/pvdiagkbf.out
fi
