#!/bin/sh

tarfile=$1
distrobase=$2

echo "  >>> Generate cvode documentation"
cd $distrobase/cvode/doc
make QUIET=-q ug_pdf
make QUIET=-q ex_pdf
cd -

echo "  >>> Add cvode module"

tar uf $tarfile $distrobase/cvode/LICENSE
tar uf $tarfile $distrobase/cvode/README

tar uf $tarfile $distrobase/cvode/doc/cv_guide.ps
tar uf $tarfile $distrobase/cvode/doc/cv_guide.pdf
tar uf $tarfile $distrobase/cvode/doc/cv_examples.ps
tar uf $tarfile $distrobase/cvode/doc/cv_examples.pdf

tar uf $tarfile $distrobase/cvode/include/cvode.h
tar uf $tarfile $distrobase/cvode/include/cvode_dense.h
tar uf $tarfile $distrobase/cvode/include/cvode_band.h
tar uf $tarfile $distrobase/cvode/include/cvode_diag.h
tar uf $tarfile $distrobase/cvode/include/cvode_spgmr.h
tar uf $tarfile $distrobase/cvode/include/cvode_spbcgs.h
tar uf $tarfile $distrobase/cvode/include/cvode_sptfqmr.h
tar uf $tarfile $distrobase/cvode/include/cvode_spils.h
tar uf $tarfile $distrobase/cvode/include/cvode_bandpre.h
tar uf $tarfile $distrobase/cvode/include/cvode_bbdpre.h

tar uf $tarfile $distrobase/cvode/source/Makefile.in
tar uf $tarfile $distrobase/cvode/source/cvode.c
tar uf $tarfile $distrobase/cvode/source/cvode_io.c
tar uf $tarfile $distrobase/cvode/source/cvode_dense.c
tar uf $tarfile $distrobase/cvode/source/cvode_band.c
tar uf $tarfile $distrobase/cvode/source/cvode_diag.c
tar uf $tarfile $distrobase/cvode/source/cvode_spils.c
tar uf $tarfile $distrobase/cvode/source/cvode_spgmr.c
tar uf $tarfile $distrobase/cvode/source/cvode_spbcgs.c
tar uf $tarfile $distrobase/cvode/source/cvode_sptfqmr.c
tar uf $tarfile $distrobase/cvode/source/cvode_bandpre.c
tar uf $tarfile $distrobase/cvode/source/cvode_bbdpre.c
tar uf $tarfile $distrobase/cvode/source/cvode_impl.h
tar uf $tarfile $distrobase/cvode/source/cvode_dense_impl.h
tar uf $tarfile $distrobase/cvode/source/cvode_band_impl.h
tar uf $tarfile $distrobase/cvode/source/cvode_diag_impl.h
tar uf $tarfile $distrobase/cvode/source/cvode_spils_impl.h
tar uf $tarfile $distrobase/cvode/source/cvode_bandpre_impl.h
tar uf $tarfile $distrobase/cvode/source/cvode_bbdpre_impl.h

tar uf $tarfile $distrobase/cvode/fcmix/Makefile.in
tar uf $tarfile $distrobase/cvode/fcmix/fcvode.h
tar uf $tarfile $distrobase/cvode/fcmix/fcvode.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvewt.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvpreco.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvjtimes.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvband.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvdense.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvbp.h
tar uf $tarfile $distrobase/cvode/fcmix/fcvbp.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvbbd.h
tar uf $tarfile $distrobase/cvode/fcmix/fcvbbd.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvroot.h
tar uf $tarfile $distrobase/cvode/fcmix/fcvroot.c

tar uf $tarfile $distrobase/cvode/examples_ser/README
tar uf $tarfile $distrobase/cvode/examples_ser/Makefile.in
tar uf $tarfile $distrobase/cvode/examples_ser/cvbanx.c
tar uf $tarfile $distrobase/cvode/examples_ser/cvbanx.out
tar uf $tarfile $distrobase/cvode/examples_ser/cvdenx.c
tar uf $tarfile $distrobase/cvode/examples_ser/cvdenx.out
tar uf $tarfile $distrobase/cvode/examples_ser/cvdenx_uw.c
tar uf $tarfile $distrobase/cvode/examples_ser/cvdenx_uw.out
tar uf $tarfile $distrobase/cvode/examples_ser/cvdirectdem.c
tar uf $tarfile $distrobase/cvode/examples_ser/cvdirectdem.out
tar uf $tarfile $distrobase/cvode/examples_ser/cvkrydem_lin.c
tar uf $tarfile $distrobase/cvode/examples_ser/cvkrydem_lin.out
tar uf $tarfile $distrobase/cvode/examples_ser/cvkrydem_pre.c
tar uf $tarfile $distrobase/cvode/examples_ser/cvkrydem_pre.out
tar uf $tarfile $distrobase/cvode/examples_ser/cvkryx_bp.c
tar uf $tarfile $distrobase/cvode/examples_ser/cvkryx_bp.out
tar uf $tarfile $distrobase/cvode/examples_ser/cvkryx.c
tar uf $tarfile $distrobase/cvode/examples_ser/cvkryx.out

tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/README
tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/Makefile.in
tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/fcvbanx.f
tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/fcvbanx.out
tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/fcvdenx.f
tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/fcvdenx.out
tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/fcvkryx_bp.f
tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/fcvkryx_bp.out
tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/fcvkryx.f
tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/fcvkryx.out

tar uf $tarfile $distrobase/cvode/examples_par/README
tar uf $tarfile $distrobase/cvode/examples_par/Makefile.in
tar uf $tarfile $distrobase/cvode/examples_par/cvkryx_bbd_p.c
tar uf $tarfile $distrobase/cvode/examples_par/cvkryx_bbd_p.out
tar uf $tarfile $distrobase/cvode/examples_par/cvkryx_p.c
tar uf $tarfile $distrobase/cvode/examples_par/cvkryx_p.out
tar uf $tarfile $distrobase/cvode/examples_par/cvnonx_p.c
tar uf $tarfile $distrobase/cvode/examples_par/cvnonx_p.out

tar uf $tarfile $distrobase/cvode/fcmix/examples_par/README
tar uf $tarfile $distrobase/cvode/fcmix/examples_par/Makefile.in
tar uf $tarfile $distrobase/cvode/fcmix/examples_par/fcvkryx_bbd_p.f
tar uf $tarfile $distrobase/cvode/fcmix/examples_par/fcvkryx_bbd_p.out
tar uf $tarfile $distrobase/cvode/fcmix/examples_par/fcvkryx_p.f
tar uf $tarfile $distrobase/cvode/fcmix/examples_par/fcvkryx_p.out
tar uf $tarfile $distrobase/cvode/fcmix/examples_par/fcvnonx_p.f
tar uf $tarfile $distrobase/cvode/fcmix/examples_par/fcvnonx_p.out

cd $distrobase/cvode/doc
make QUIET=-q clean
cd -
