#!/bin/sh

tarfile=$1
distrobase=$2
doc=$3

shift 3
tar=$*

echo "   --- Add cvode module to $tarfile"

if [ $doc = "T" ]; then
#$tar $tarfile $distrobase/doc/cvode/cv_guide.ps
$tar $tarfile $distrobase/doc/cvode/cv_guide.pdf
#$tar $tarfile $distrobase/doc/cvode/cv_examples.ps
$tar $tarfile $distrobase/doc/cvode/cv_examples.pdf
fi

$tar $tarfile $distrobase/include/cvode/cvode.h
$tar $tarfile $distrobase/include/cvode/cvode_direct.h
$tar $tarfile $distrobase/include/cvode/cvode_dense.h
$tar $tarfile $distrobase/include/cvode/cvode_band.h
$tar $tarfile $distrobase/include/cvode/cvode_klu.h
$tar $tarfile $distrobase/include/cvode/cvode_lapack.h
$tar $tarfile $distrobase/include/cvode/cvode_diag.h
$tar $tarfile $distrobase/include/cvode/cvode_spgmr.h
$tar $tarfile $distrobase/include/cvode/cvode_spbcgs.h
$tar $tarfile $distrobase/include/cvode/cvode_sptfqmr.h
$tar $tarfile $distrobase/include/cvode/cvode_spils.h
$tar $tarfile $distrobase/include/cvode/cvode_bandpre.h
$tar $tarfile $distrobase/include/cvode/cvode_bbdpre.h
$tar $tarfile $distrobase/include/cvode/cvode_sparse.h
$tar $tarfile $distrobase/include/cvode/cvode_superlumt.h

$tar $tarfile $distrobase/src/cvode/LICENSE
$tar $tarfile $distrobase/src/cvode/README
$tar $tarfile $distrobase/src/cvode/Makefile.in
$tar $tarfile $distrobase/src/cvode/CMakeLists.txt

$tar $tarfile $distrobase/src/cvode/cvode.c
$tar $tarfile $distrobase/src/cvode/cvode_io.c
$tar $tarfile $distrobase/src/cvode/cvode_klu.c
$tar $tarfile $distrobase/src/cvode/cvode_direct.c
$tar $tarfile $distrobase/src/cvode/cvode_dense.c
$tar $tarfile $distrobase/src/cvode/cvode_band.c
$tar $tarfile $distrobase/src/cvode/cvode_lapack.c
$tar $tarfile $distrobase/src/cvode/cvode_diag.c
$tar $tarfile $distrobase/src/cvode/cvode_spils.c
$tar $tarfile $distrobase/src/cvode/cvode_spgmr.c
$tar $tarfile $distrobase/src/cvode/cvode_spbcgs.c
$tar $tarfile $distrobase/src/cvode/cvode_sptfqmr.c
$tar $tarfile $distrobase/src/cvode/cvode_sparse.c
$tar $tarfile $distrobase/src/cvode/cvode_superlumt.c
$tar $tarfile $distrobase/src/cvode/cvode_bandpre.c
$tar $tarfile $distrobase/src/cvode/cvode_bbdpre.c
$tar $tarfile $distrobase/src/cvode/cvode_impl.h
$tar $tarfile $distrobase/src/cvode/cvode_direct_impl.h
$tar $tarfile $distrobase/src/cvode/cvode_diag_impl.h
$tar $tarfile $distrobase/src/cvode/cvode_spils_impl.h
$tar $tarfile $distrobase/src/cvode/cvode_sparse_impl.h
$tar $tarfile $distrobase/src/cvode/cvode_bandpre_impl.h
$tar $tarfile $distrobase/src/cvode/cvode_bbdpre_impl.h

echo "   --- Add fcvode module to $tarfile"

$tar $tarfile $distrobase/src/cvode/fcmix/Makefile.in
$tar $tarfile $distrobase/src/cvode/fcmix/CMakeLists.txt

$tar $tarfile $distrobase/src/cvode/fcmix/fcvode.c
$tar $tarfile $distrobase/src/cvode/fcmix/fcvewt.c
$tar $tarfile $distrobase/src/cvode/fcmix/fcvpreco.c
$tar $tarfile $distrobase/src/cvode/fcmix/fcvjtimes.c
$tar $tarfile $distrobase/src/cvode/fcmix/fcvband.c
$tar $tarfile $distrobase/src/cvode/fcmix/fcvdense.c
$tar $tarfile $distrobase/src/cvode/fcmix/fcvlapack.c
$tar $tarfile $distrobase/src/cvode/fcmix/fcvlapband.c
$tar $tarfile $distrobase/src/cvode/fcmix/fcvlapdense.c
$tar $tarfile $distrobase/src/cvode/fcmix/fcvbp.c
$tar $tarfile $distrobase/src/cvode/fcmix/fcvbbd.c
$tar $tarfile $distrobase/src/cvode/fcmix/fcvroot.c
$tar $tarfile $distrobase/src/cvode/fcmix/fcvode.h
$tar $tarfile $distrobase/src/cvode/fcmix/fcvbp.h
$tar $tarfile $distrobase/src/cvode/fcmix/fcvbbd.h
$tar $tarfile $distrobase/src/cvode/fcmix/fcvroot.h

echo "   --- Add cvode examples to $tarfile"

$tar $tarfile $distrobase/examples/cvode/serial/README
$tar $tarfile $distrobase/examples/cvode/serial/Makefile.in
$tar $tarfile $distrobase/examples/cvode/serial/CMakeLists.txt
$tar $tarfile $distrobase/examples/cvode/serial/cvAdvDiff_bnd.c
$tar $tarfile $distrobase/examples/cvode/serial/cvAdvDiff_bndL.c
$tar $tarfile $distrobase/examples/cvode/serial/cvAdvDiff_bndL.out
$tar $tarfile $distrobase/examples/cvode/serial/cvAdvDiff_bnd.out
$tar $tarfile $distrobase/examples/cvode/serial/cvDirectDemo_ls.c
$tar $tarfile $distrobase/examples/cvode/serial/cvDirectDemo_ls.out
$tar $tarfile $distrobase/examples/cvode/serial/cvDiurnal_kry_bp.c
$tar $tarfile $distrobase/examples/cvode/serial/cvDiurnal_kry_bp.out
$tar $tarfile $distrobase/examples/cvode/serial/cvDiurnal_kry.c
$tar $tarfile $distrobase/examples/cvode/serial/cvDiurnal_kry.out
$tar $tarfile $distrobase/examples/cvode/serial/cvKrylovDemo_ls.c
$tar $tarfile $distrobase/examples/cvode/serial/cvKrylovDemo_ls.out
$tar $tarfile $distrobase/examples/cvode/serial/cvKrylovDemo_prec.c
$tar $tarfile $distrobase/examples/cvode/serial/cvKrylovDemo_prec.out
$tar $tarfile $distrobase/examples/cvode/serial/cvRoberts_dns.c
$tar $tarfile $distrobase/examples/cvode/serial/cvRoberts_dnsL.c
$tar $tarfile $distrobase/examples/cvode/serial/cvRoberts_dnsL.out
$tar $tarfile $distrobase/examples/cvode/serial/cvRoberts_dns.out
$tar $tarfile $distrobase/examples/cvode/serial/cvRoberts_dns_uw.c
$tar $tarfile $distrobase/examples/cvode/serial/cvRoberts_dns_uw.out
$tar $tarfile $distrobase/examples/cvode/serial/cvRoberts_klu.c
$tar $tarfile $distrobase/examples/cvode/serial/cvRoberts_klu.out
$tar $tarfile $distrobase/examples/cvode/serial/cvRoberts_sps.c
$tar $tarfile $distrobase/examples/cvode/serial/cvRoberts_sps.out

$tar $tarfile $distrobase/examples/cvode/fcmix_serial/README
$tar $tarfile $distrobase/examples/cvode/fcmix_serial/Makefile.in
$tar $tarfile $distrobase/examples/cvode/fcmix_serial/CMakeLists.txt
$tar $tarfile $distrobase/examples/cvode/fcmix_serial/fcvAdvDiff_bnd.f
$tar $tarfile $distrobase/examples/cvode/fcmix_serial/fcvAdvDiff_bnd.out
$tar $tarfile $distrobase/examples/cvode/fcmix_serial/fcvDiurnal_kry_bp.f
$tar $tarfile $distrobase/examples/cvode/fcmix_serial/fcvDiurnal_kry_bp.out
$tar $tarfile $distrobase/examples/cvode/fcmix_serial/fcvDiurnal_kry.f
$tar $tarfile $distrobase/examples/cvode/fcmix_serial/fcvDiurnal_kry.out
$tar $tarfile $distrobase/examples/cvode/fcmix_serial/fcvRoberts_dns.f
$tar $tarfile $distrobase/examples/cvode/fcmix_serial/fcvRoberts_dnsL.f
$tar $tarfile $distrobase/examples/cvode/fcmix_serial/fcvRoberts_dnsL.out
$tar $tarfile $distrobase/examples/cvode/fcmix_serial/fcvRoberts_dns.out

$tar $tarfile $distrobase/examples/cvode/parallel/README
$tar $tarfile $distrobase/examples/cvode/parallel/Makefile.in
$tar $tarfile $distrobase/examples/cvode/parallel/CMakeLists.txt
$tar $tarfile $distrobase/examples/cvode/parallel/cvAdvDiff_non_p.c
$tar $tarfile $distrobase/examples/cvode/parallel/cvAdvDiff_non_p.out
$tar $tarfile $distrobase/examples/cvode/parallel/cvDiurnal_kry_bbd_p.c
$tar $tarfile $distrobase/examples/cvode/parallel/cvDiurnal_kry_bbd_p.out
$tar $tarfile $distrobase/examples/cvode/parallel/cvDiurnal_kry_p.c
$tar $tarfile $distrobase/examples/cvode/parallel/cvDiurnal_kry_p.out

$tar $tarfile $distrobase/examples/cvode/fcmix_parallel/README
$tar $tarfile $distrobase/examples/cvode/fcmix_parallel/Makefile.in
$tar $tarfile $distrobase/examples/cvode/fcmix_parallel/CMakeLists.txt
$tar $tarfile $distrobase/examples/cvode/fcmix_parallel/fcvDiag_non_p.f
$tar $tarfile $distrobase/examples/cvode/fcmix_parallel/fcvDiag_non_p.out
$tar $tarfile $distrobase/examples/cvode/fcmix_parallel/fcvDiag_kry_bbd_p.f
$tar $tarfile $distrobase/examples/cvode/fcmix_parallel/fcvDiag_kry_bbd_p.out
$tar $tarfile $distrobase/examples/cvode/fcmix_parallel/fcvDiag_kry_p.f
$tar $tarfile $distrobase/examples/cvode/fcmix_parallel/fcvDiag_kry_p.out

echo "   --- Add regression test files to $tarfile"
$tar $tarfile $distrobase/test/answers/cvAdvDiff_bnd
$tar $tarfile $distrobase/test/answers/cvAdvDiff_bndL
$tar $tarfile $distrobase/test/answers/cvAdvDiff_non_p
$tar $tarfile $distrobase/test/answers/cvDirectDemo_ls
$tar $tarfile $distrobase/test/answers/cvDiurnal_kry
$tar $tarfile $distrobase/test/answers/cvDiurnal_kry_bbd_p
$tar $tarfile $distrobase/test/answers/cvDiurnal_kry_bp
$tar $tarfile $distrobase/test/answers/cvDiurnal_kry_p
$tar $tarfile $distrobase/test/answers/cvKrylovDemo_ls
$tar $tarfile $distrobase/test/answers/cvKrylovDemo_prec
$tar $tarfile $distrobase/test/answers/cvRoberts_dns
$tar $tarfile $distrobase/test/answers/cvRoberts_dnsL
$tar $tarfile $distrobase/test/answers/cvRoberts_dns_uw
$tar $tarfile $distrobase/test/answers/cvRoberts_klu
$tar $tarfile $distrobase/test/answers/cvRoberts_sps
$tar $tarfile $distrobase/test/answers/fcvAdvDiff_bnd
$tar $tarfile $distrobase/test/answers/fcvDiag_kry_bbd_p
$tar $tarfile $distrobase/test/answers/fcvDiag_kry_p
$tar $tarfile $distrobase/test/answers/fcvDiag_non_p
$tar $tarfile $distrobase/test/answers/fcvDiurnal_kry
$tar $tarfile $distrobase/test/answers/fcvDiurnal_kry_bp
$tar $tarfile $distrobase/test/answers/fcvRoberts_dns
$tar $tarfile $distrobase/test/answers/fcvRoberts_dnsL
