#!/bin/sh

tarfile=$1
distrobase=$2

echo "  >>> Generate cvodes documentation"
cd $distrobase/cvodes/doc
make QUIET=-q ug_pdf
make QUIET=-q ex_pdf
cd -

echo "  >>> Add cvodes module"

tar uf $tarfile $distrobase/cvodes/LICENSE
tar uf $tarfile $distrobase/cvodes/README

tar uf $tarfile $distrobase/cvodes/doc/cvs_guide.ps
tar uf $tarfile $distrobase/cvodes/doc/cvs_guide.pdf
tar uf $tarfile $distrobase/cvodes/doc/cvs_examples.ps
tar uf $tarfile $distrobase/cvodes/doc/cvs_examples.pdf

tar uf $tarfile $distrobase/cvodes/include/cvodes.h
tar uf $tarfile $distrobase/cvodes/include/cvodea.h
tar uf $tarfile $distrobase/cvodes/include/cvdense.h
tar uf $tarfile $distrobase/cvodes/include/cvband.h
tar uf $tarfile $distrobase/cvodes/include/cvdiag.h
tar uf $tarfile $distrobase/cvodes/include/cvspgmr.h
tar uf $tarfile $distrobase/cvodes/include/cvspbcg.h
tar uf $tarfile $distrobase/cvodes/include/cvsptfqmr.h
tar uf $tarfile $distrobase/cvodes/include/cvspils.h
tar uf $tarfile $distrobase/cvodes/include/cvbandpre.h
tar uf $tarfile $distrobase/cvodes/include/cvbbdpre.h

tar uf $tarfile $distrobase/cvodes/source/Makefile.in
tar uf $tarfile $distrobase/cvodes/source/cvodes.c
tar uf $tarfile $distrobase/cvodes/source/cvodesio.c
tar uf $tarfile $distrobase/cvodes/source/cvodea.c
tar uf $tarfile $distrobase/cvodes/source/cvdense.c
tar uf $tarfile $distrobase/cvodes/source/cvband.c
tar uf $tarfile $distrobase/cvodes/source/cvdiag.c
tar uf $tarfile $distrobase/cvodes/source/cvspgmr.c
tar uf $tarfile $distrobase/cvodes/source/cvspbcg.c
tar uf $tarfile $distrobase/cvodes/source/cvsptfqmr.c
tar uf $tarfile $distrobase/cvodes/source/cvbandpre.c
tar uf $tarfile $distrobase/cvodes/source/cvbbdpre.c
tar uf $tarfile $distrobase/cvodes/source/cvodes_impl.h
tar uf $tarfile $distrobase/cvodes/source/cvodea_impl.h
tar uf $tarfile $distrobase/cvodes/source/cvdense_impl.h
tar uf $tarfile $distrobase/cvodes/source/cvband_impl.h
tar uf $tarfile $distrobase/cvodes/source/cvdiag_impl.h
tar uf $tarfile $distrobase/cvodes/source/cvspgmr_impl.h
tar uf $tarfile $distrobase/cvodes/source/cvspbcg_impl.h
tar uf $tarfile $distrobase/cvodes/source/cvsptfqmr_impl.h
tar uf $tarfile $distrobase/cvodes/source/cvbandpre_impl.h
tar uf $tarfile $distrobase/cvodes/source/cvbbdpre_impl.h

tar uf $tarfile $distrobase/cvodes/examples_ser/README
tar uf $tarfile $distrobase/cvodes/examples_ser/Makefile.in
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsadjbanx.c
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsadjbanx.out
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsadjdenx.c
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsadjdenx.out
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsadjkryx_int.c
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsadjkryx_int.out
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsadjkryx_pnt.c
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsadjkryx_pnt.out
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsbanx.c
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsbanx.out
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsdenx.c
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsdenx.out
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsdenx_uw.c
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsdenx_uw.out
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsdirectdem.c
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsdirectdem.out
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsfwddenx.c
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsfwddenx.out1
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsfwddenx.out2
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsfwdkryx.c
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsfwdkryx.out1
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsfwdkryx.out2
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsfwdnonx.c
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsfwdnonx.out1
tar uf $tarfile $distrobase/cvodes/examples_ser/cvsfwdnonx.out2
tar uf $tarfile $distrobase/cvodes/examples_ser/cvskrydem_lin.c
tar uf $tarfile $distrobase/cvodes/examples_ser/cvskrydem_lin.out
tar uf $tarfile $distrobase/cvodes/examples_ser/cvskrydem_pre.c
tar uf $tarfile $distrobase/cvodes/examples_ser/cvskrydem_pre.out
tar uf $tarfile $distrobase/cvodes/examples_ser/cvskryx_bp.c
tar uf $tarfile $distrobase/cvodes/examples_ser/cvskryx_bp.out
tar uf $tarfile $distrobase/cvodes/examples_ser/cvskryx.c
tar uf $tarfile $distrobase/cvodes/examples_ser/cvskryx.out

tar uf $tarfile $distrobase/cvodes/examples_par/README
tar uf $tarfile $distrobase/cvodes/examples_par/Makefile.in
tar uf $tarfile $distrobase/cvodes/examples_par/cvsadjkryx_p.c
tar uf $tarfile $distrobase/cvodes/examples_par/cvsadjkryx_p.out
tar uf $tarfile $distrobase/cvodes/examples_par/cvsadjnonx_p.c
tar uf $tarfile $distrobase/cvodes/examples_par/cvsadjnonx_p.out
tar uf $tarfile $distrobase/cvodes/examples_par/cvsfwdkryx_p.c
tar uf $tarfile $distrobase/cvodes/examples_par/cvsfwdkryx_p.out1
tar uf $tarfile $distrobase/cvodes/examples_par/cvsfwdkryx_p.out2
tar uf $tarfile $distrobase/cvodes/examples_par/cvsfwdnonx_p.c
tar uf $tarfile $distrobase/cvodes/examples_par/cvsfwdnonx_p.out1
tar uf $tarfile $distrobase/cvodes/examples_par/cvsfwdnonx_p.out2
tar uf $tarfile $distrobase/cvodes/examples_par/cvskryx_bbd_p.c
tar uf $tarfile $distrobase/cvodes/examples_par/cvskryx_bbd_p.out
tar uf $tarfile $distrobase/cvodes/examples_par/cvskryx_p.c
tar uf $tarfile $distrobase/cvodes/examples_par/cvskryx_p.out
tar uf $tarfile $distrobase/cvodes/examples_par/cvsnonx_p.c
tar uf $tarfile $distrobase/cvodes/examples_par/cvsnonx_p.out
