#!/bin/sh

tarfile=$1
distrobase=$2

echo -n "   --- Add ida module ... "

tar uf $tarfile $distrobase/src/ida/LICENSE
tar uf $tarfile $distrobase/src/ida/README

#tar uf $tarfile $distrobase/doc/ida/ida_guide.ps
#tar uf $tarfile $distrobase/doc/ida/ida_guide.pdf
#tar uf $tarfile $distrobase/doc/ida/ida_examples.ps
#tar uf $tarfile $distrobase/doc/ida/ida_examples.pdf

tar uf $tarfile $distrobase/include/ida/ida.h
tar uf $tarfile $distrobase/include/ida/ida_dense.h
tar uf $tarfile $distrobase/include/ida/ida_band.h
tar uf $tarfile $distrobase/include/ida/ida_spgmr.h
tar uf $tarfile $distrobase/include/ida/ida_spbcgs.h
tar uf $tarfile $distrobase/include/ida/ida_sptfqmr.h
tar uf $tarfile $distrobase/include/ida/ida_spils.h
tar uf $tarfile $distrobase/include/ida/ida_bbdpre.h

tar uf $tarfile $distrobase/src/ida/Makefile.in
tar uf $tarfile $distrobase/src/ida/ida.c
tar uf $tarfile $distrobase/src/ida/ida_io.c
tar uf $tarfile $distrobase/src/ida/ida_ic.c
tar uf $tarfile $distrobase/src/ida/ida_dense.c
tar uf $tarfile $distrobase/src/ida/ida_band.c
tar uf $tarfile $distrobase/src/ida/ida_spils.c
tar uf $tarfile $distrobase/src/ida/ida_spgmr.c
tar uf $tarfile $distrobase/src/ida/ida_spbcgs.c
tar uf $tarfile $distrobase/src/ida/ida_sptfqmr.c
tar uf $tarfile $distrobase/src/ida/ida_bbdpre.c
tar uf $tarfile $distrobase/src/ida/ida_impl.h
tar uf $tarfile $distrobase/src/ida/ida_dense_impl.h
tar uf $tarfile $distrobase/src/ida/ida_band_impl.h
tar uf $tarfile $distrobase/src/ida/ida_spils_impl.h
tar uf $tarfile $distrobase/src/ida/ida_bbdpre_impl.h

tar uf $tarfile $distrobase/src/ida/fcmix/Makefile.in
tar uf $tarfile $distrobase/src/ida/fcmix/fidaband.c
tar uf $tarfile $distrobase/src/ida/fcmix/fidabbd.c
tar uf $tarfile $distrobase/src/ida/fcmix/fidabbd.h
tar uf $tarfile $distrobase/src/ida/fcmix/fida.c
tar uf $tarfile $distrobase/src/ida/fcmix/fidadense.c
tar uf $tarfile $distrobase/src/ida/fcmix/fidaewt.c
tar uf $tarfile $distrobase/src/ida/fcmix/fida.h
tar uf $tarfile $distrobase/src/ida/fcmix/fidajtimes.c
tar uf $tarfile $distrobase/src/ida/fcmix/fidapreco.c
tar uf $tarfile $distrobase/src/ida/fcmix/fidaroot.c
tar uf $tarfile $distrobase/src/ida/fcmix/fidaroot.h

tar uf $tarfile $distrobase/examples/ida/serial/README
tar uf $tarfile $distrobase/examples/ida/serial/Makefile.in
tar uf $tarfile $distrobase/examples/ida/serial/idabanx1.c
tar uf $tarfile $distrobase/examples/ida/serial/idabanx1.out
tar uf $tarfile $distrobase/examples/ida/serial/idabanx2.c
tar uf $tarfile $distrobase/examples/ida/serial/idabanx2.out
tar uf $tarfile $distrobase/examples/ida/serial/idadenx.c
tar uf $tarfile $distrobase/examples/ida/serial/idadenx.out
tar uf $tarfile $distrobase/examples/ida/serial/idakrydem_lin.c
tar uf $tarfile $distrobase/examples/ida/serial/idakrydem_lin.out
tar uf $tarfile $distrobase/examples/ida/serial/idakryx.c
tar uf $tarfile $distrobase/examples/ida/serial/idakryx.out

tar uf $tarfile $distrobase/examples/ida/fcmix_serial/README
tar uf $tarfile $distrobase/examples/ida/fcmix_serial/Makefile.in
tar uf $tarfile $distrobase/examples/ida/fcmix_serial/fidadenx.f
tar uf $tarfile $distrobase/examples/ida/fcmix_serial/fidadenx.out

tar uf $tarfile $distrobase/examples/ida/parallel/README
tar uf $tarfile $distrobase/examples/ida/parallel/Makefile.in
tar uf $tarfile $distrobase/examples/ida/parallel/idakryx1_bbd_p.c
tar uf $tarfile $distrobase/examples/ida/parallel/idakryx1_bbd_p.out
tar uf $tarfile $distrobase/examples/ida/parallel/idakryx1_p.c
tar uf $tarfile $distrobase/examples/ida/parallel/idakryx1_p.out
tar uf $tarfile $distrobase/examples/ida/parallel/idakryx2_bbd_p.c
tar uf $tarfile $distrobase/examples/ida/parallel/idakryx2_bbd_p.out
tar uf $tarfile $distrobase/examples/ida/parallel/idakryx2_p.c
tar uf $tarfile $distrobase/examples/ida/parallel/idakryx2_p.out

tar uf $tarfile $distrobase/examples/ida/fcmix_parallel/README
tar uf $tarfile $distrobase/examples/ida/fcmix_parallel/Makefile.in
tar uf $tarfile $distrobase/examples/ida/fcmix_parallel/fidakryx_bbd_p.f
tar uf $tarfile $distrobase/examples/ida/fcmix_parallel/fidakryx_bbd_p.out

echo "done"