#!/bin/sh

tarfile=$1
distrobase=$2
doc=$3

shift 3
tar=$*

echo "   --- Add idas module to $tarfile"

if [ $doc = "T" ]; then
#$tar $tarfile $distrobase/doc/idas/idas_guide.ps
$tar $tarfile $distrobase/doc/idas/idas_guide.pdf
#$tar $tarfile $distrobase/doc/idas/idas_examples.ps
$tar $tarfile $distrobase/doc/idas/idas_examples.pdf
fi

$tar $tarfile $distrobase/include/idas/idas.h
$tar $tarfile $distrobase/include/idas/idas_direct.h
$tar $tarfile $distrobase/include/idas/idas_dense.h
$tar $tarfile $distrobase/include/idas/idas_band.h
$tar $tarfile $distrobase/include/idas/idas_sparse.h
$tar $tarfile $distrobase/include/idas/idas_lapack.h
$tar $tarfile $distrobase/include/idas/idas_spgmr.h
$tar $tarfile $distrobase/include/idas/idas_spbcgs.h
$tar $tarfile $distrobase/include/idas/idas_sptfqmr.h
$tar $tarfile $distrobase/include/idas/idas_spils.h
$tar $tarfile $distrobase/include/idas/idas_bbdpre.h
$tar $tarfile $distrobase/include/idas/idas_superlumt.h
$tar $tarfile $distrobase/include/idas/idas_klu.h

$tar $tarfile $distrobase/src/idas/LICENSE
$tar $tarfile $distrobase/src/idas/README
$tar $tarfile $distrobase/src/idas/CMakeLists.txt

$tar $tarfile $distrobase/src/idas/idas.c
$tar $tarfile $distrobase/src/idas/idaa.c
$tar $tarfile $distrobase/src/idas/idas_io.c
$tar $tarfile $distrobase/src/idas/idaa_io.c
$tar $tarfile $distrobase/src/idas/idas_ic.c
$tar $tarfile $distrobase/src/idas/idas_direct.c
$tar $tarfile $distrobase/src/idas/idas_dense.c
$tar $tarfile $distrobase/src/idas/idas_sparse.c
$tar $tarfile $distrobase/src/idas/idas_band.c
$tar $tarfile $distrobase/src/idas/idas_klu.c
$tar $tarfile $distrobase/src/idas/idas_lapack.c
$tar $tarfile $distrobase/src/idas/idas_spils.c
$tar $tarfile $distrobase/src/idas/idas_spgmr.c
$tar $tarfile $distrobase/src/idas/idas_spbcgs.c
$tar $tarfile $distrobase/src/idas/idas_sptfqmr.c
$tar $tarfile $distrobase/src/idas/idas_superlumt.c
$tar $tarfile $distrobase/src/idas/idas_bbdpre.c
$tar $tarfile $distrobase/src/idas/idas_impl.h
$tar $tarfile $distrobase/src/idas/idas_direct_impl.h
$tar $tarfile $distrobase/src/idas/idas_sparse_impl.h
$tar $tarfile $distrobase/src/idas/idas_spils_impl.h
$tar $tarfile $distrobase/src/idas/idas_bbdpre_impl.h

echo "   --- Add idas examples to $tarfile"

$tar $tarfile $distrobase/examples/idas/serial/README
$tar $tarfile $distrobase/examples/idas/serial/CMakeLists.txt
$tar $tarfile $distrobase/examples/idas/serial/idasAkzoNob_ASAi_dns.c
$tar $tarfile $distrobase/examples/idas/serial/idasAkzoNob_ASAi_dns.out
$tar $tarfile $distrobase/examples/idas/serial/idasAkzoNob_dns.c
$tar $tarfile $distrobase/examples/idas/serial/idasAkzoNob_dns.out
$tar $tarfile $distrobase/examples/idas/serial/idasFoodWeb_bnd.c
$tar $tarfile $distrobase/examples/idas/serial/idasFoodWeb_bnd.out
$tar $tarfile $distrobase/examples/idas/serial/idasHeat2D_bnd.c
$tar $tarfile $distrobase/examples/idas/serial/idasHeat2D_bnd.out
$tar $tarfile $distrobase/examples/idas/serial/idasHeat2D_kry.c
$tar $tarfile $distrobase/examples/idas/serial/idasHeat2D_kry.out
$tar $tarfile $distrobase/examples/idas/serial/idasHessian_ASA_FSA.c
$tar $tarfile $distrobase/examples/idas/serial/idasHessian_ASA_FSA.out
$tar $tarfile $distrobase/examples/idas/serial/idasKrylovDemo_ls.c
$tar $tarfile $distrobase/examples/idas/serial/idasKrylovDemo_ls.out
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_ASAi_dns.c
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_ASAi_dns.out
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_ASAi_klu.c
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_ASAi_klu.out
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_ASAi_sps.c
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_ASAi_sps.out
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_dns.c
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_dns.out
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_FSA_dns.c
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_FSA_dns.out
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_FSA_klu.c
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_FSA_klu.out
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_FSA_sps.c
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_FSA_sps.out
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_klu.c
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_klu.out
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_sps.c
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_sps.out
$tar $tarfile $distrobase/examples/idas/serial/idasSlCrank_dns.c
$tar $tarfile $distrobase/examples/idas/serial/idasSlCrank_dns.out
$tar $tarfile $distrobase/examples/idas/serial/idasSlCrank_FSA_dns.c
$tar $tarfile $distrobase/examples/idas/serial/idasSlCrank_FSA_dns.out

$tar $tarfile $distrobase/examples/idas/C_openmp/README
$tar $tarfile $distrobase/examples/idas/C_openmp/CMakeLists.txt
$tar $tarfile $distrobase/examples/idas/C_openmp/idasFoodWeb_bnd_omp.c
$tar $tarfile $distrobase/examples/idas/C_openmp/idasFoodWeb_bnd_omp.out
$tar $tarfile $distrobase/examples/idas/C_openmp/idasFoodWeb_kry_omp.c
$tar $tarfile $distrobase/examples/idas/C_openmp/idasFoodWeb_kry_omp.out

$tar $tarfile $distrobase/examples/idas/parallel/README
$tar $tarfile $distrobase/examples/idas/parallel/CMakeLists.txt
$tar $tarfile $distrobase/examples/idas/parallel/idasBruss_ASAp_kry_bbd_p.c
$tar $tarfile $distrobase/examples/idas/parallel/idasBruss_ASAp_kry_bbd_p.out
$tar $tarfile $distrobase/examples/idas/parallel/idasBruss_FSA_kry_bbd_p.c
$tar $tarfile $distrobase/examples/idas/parallel/idasBruss_FSA_kry_bbd_p.out
$tar $tarfile $distrobase/examples/idas/parallel/idasBruss_kry_bbd_p.c
$tar $tarfile $distrobase/examples/idas/parallel/idasBruss_kry_bbd_p.out
$tar $tarfile $distrobase/examples/idas/parallel/idasFoodWeb_kry_bbd_p.c
$tar $tarfile $distrobase/examples/idas/parallel/idasFoodWeb_kry_bbd_p.out
$tar $tarfile $distrobase/examples/idas/parallel/idasFoodWeb_kry_p.c
$tar $tarfile $distrobase/examples/idas/parallel/idasFoodWeb_kry_p.out
$tar $tarfile $distrobase/examples/idas/parallel/idasHeat2D_FSA_kry_bbd_p.c
$tar $tarfile $distrobase/examples/idas/parallel/idasHeat2D_FSA_kry_bbd_p.out
$tar $tarfile $distrobase/examples/idas/parallel/idasHeat2D_kry_bbd_p.c
$tar $tarfile $distrobase/examples/idas/parallel/idasHeat2D_kry_bbd_p.out
$tar $tarfile $distrobase/examples/idas/parallel/idasHeat2D_kry_p.c
$tar $tarfile $distrobase/examples/idas/parallel/idasHeat2D_kry_p.out

# 3/3/2015:LEBanks - Don't add to release yet. Many tests will fail, which can be confusing to users
#echo "   --- Add regression test files to $tarfile"
#$tar $tarfile $distrobase/test/answers/idasAkzoNob_ASAi_dns
#$tar $tarfile $distrobase/test/answers/idasAkzoNob_dns
#$tar $tarfile $distrobase/test/answers/idasBruss_ASAp_kry_bbd_p
#$tar $tarfile $distrobase/test/answers/idasBruss_FSA_kry_bbd_p
#$tar $tarfile $distrobase/test/answers/idasBruss_kry_bbd_p
#$tar $tarfile $distrobase/test/answers/idasFoodWeb_bnd
#$tar $tarfile $distrobase/test/answers/idasFoodWeb_kry_bbd_p
#$tar $tarfile $distrobase/test/answers/idasFoodWeb_kry_p
#$tar $tarfile $distrobase/test/answers/idasHeat2D_bnd
#$tar $tarfile $distrobase/test/answers/idasHeat2D_FSA_kry_bbd_p
#$tar $tarfile $distrobase/test/answers/idasHeat2D_FSA_kry_bbd_p_-sensi_stg_t
#$tar $tarfile $distrobase/test/answers/idasHeat2D_kry
#$tar $tarfile $distrobase/test/answers/idasHeat2D_kry_bbd_p
#$tar $tarfile $distrobase/test/answers/idasHeat2D_kry_p
#$tar $tarfile $distrobase/test/answers/idasHessian_ASA_FSA
#$tar $tarfile $distrobase/test/answers/idasKrylovDemo_ls
#$tar $tarfile $distrobase/test/answers/idaSlCrank_dns
#$tar $tarfile $distrobase/test/answers/idasRoberts_ASAi_dns
#$tar $tarfile $distrobase/test/answers/idasRoberts_dns
#$tar $tarfile $distrobase/test/answers/idasRoberts_FSA_dns_-sensi_stg_t
#$tar $tarfile $distrobase/test/answers/idasRoberts_klu
#$tar $tarfile $distrobase/test/answers/idasRoberts_sps
#$tar $tarfile $distrobase/test/answers/idasSlCrank_dns
#$tar $tarfile $distrobase/test/answers/idasSlCrank_FSA_dns
