#!/bin/sh

tarfile=$1
distrobase=$2
doc=$3

# all remaining inputs are for tar command
shift 3
tar=$*

echo "   --- Add idas module to $tarfile"

if [ $doc = "T" ]; then
    $tar $tarfile $distrobase/doc/idas/idas_guide.pdf    || exit 1
    $tar $tarfile $distrobase/doc/idas/idas_examples.pdf || exit 1
    $tar $tarfile $distrobase/doc/idas/guide             || exit 1
fi

$tar $tarfile $distrobase/include/idas/idas.h        || exit 1
$tar $tarfile $distrobase/include/idas/idas_bbdpre.h || exit 1
$tar $tarfile $distrobase/include/idas/idas_direct.h || exit 1
$tar $tarfile $distrobase/include/idas/idas_ls.h     || exit 1
$tar $tarfile $distrobase/include/idas/idas_spils.h  || exit 1

$tar $tarfile $distrobase/src/idas/LICENSE        || exit 1
$tar $tarfile $distrobase/src/idas/NOTICE         || exit 1
$tar $tarfile $distrobase/src/idas/README.md      || exit 1
$tar $tarfile $distrobase/src/idas/CMakeLists.txt || exit 1

$tar $tarfile $distrobase/src/idas/idaa.c             || exit 1
$tar $tarfile $distrobase/src/idas/idaa_io.c          || exit 1
$tar $tarfile $distrobase/src/idas/idas.c             || exit 1
$tar $tarfile $distrobase/src/idas/idas_bbdpre.c      || exit 1
$tar $tarfile $distrobase/src/idas/idas_bbdpre_impl.h || exit 1
$tar $tarfile $distrobase/src/idas/idas_direct.c      || exit 1
$tar $tarfile $distrobase/src/idas/idas_ic.c          || exit 1
$tar $tarfile $distrobase/src/idas/idas_impl.h        || exit 1
$tar $tarfile $distrobase/src/idas/idas_io.c          || exit 1
$tar $tarfile $distrobase/src/idas/idas_ls.c          || exit 1
$tar $tarfile $distrobase/src/idas/idas_ls_impl.h     || exit 1
$tar $tarfile $distrobase/src/idas/idas_nls.c         || exit 1
$tar $tarfile $distrobase/src/idas/idas_nls_sim.c     || exit 1
$tar $tarfile $distrobase/src/idas/idas_nls_stg.c     || exit 1
$tar $tarfile $distrobase/src/idas/idas_spils.c       || exit 1

$tar $tarfile $distrobase/src/idas/fmod/CMakeLists.txt || exit 1
$tar $tarfile $distrobase/src/idas/fmod/fidas_mod.c    || exit 1
$tar $tarfile $distrobase/src/idas/fmod/fidas_mod.f90  || exit 1

echo "   --- Add idas examples to $tarfile"

$tar $tarfile $distrobase/examples/idas/CMakeLists.txt || exit 1

$tar $tarfile $distrobase/examples/idas/serial/README                               || exit 1
$tar $tarfile $distrobase/examples/idas/serial/CMakeLists.txt                       || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasAkzoNob_ASAi_dns.c               || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasAkzoNob_ASAi_dns.out             || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasAkzoNob_dns.c                    || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasAkzoNob_dns.out                  || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasAnalytic_mels.c                  || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasAnalytic_mels.out                || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasFoodWeb_bnd.c                    || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasFoodWeb_bnd.out                  || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasHeat2D_bnd.c                     || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasHeat2D_bnd.out                   || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasHeat2D_kry.c                     || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasHeat2D_kry.out                   || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasHessian_ASA_FSA.c                || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasHessian_ASA_FSA.out              || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasKrylovDemo_ls.c                  || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasKrylovDemo_ls.out                || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasKrylovDemo_ls_1.out              || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasKrylovDemo_ls_2.out              || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_ASAi_dns.c               || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_ASAi_dns.out             || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_ASAi_klu.c               || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_ASAi_klu.out             || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_ASAi_sps.c               || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_ASAi_sps.out             || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_dns.c                    || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_dns.out                  || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_FSA_dns.c                || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_FSA_dns_-sensi_stg_t.out || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_FSA_klu.c                || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_FSA_klu_-sensi_stg_t.out || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_FSA_sps.c                || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_FSA_sps_-sensi_stg_t.out || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_klu.c                    || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_klu.out                  || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_sps.c                    || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasRoberts_sps.out                  || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasSlCrank_dns.c                    || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasSlCrank_dns.out                  || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasSlCrank_FSA_dns.c                || exit 1
$tar $tarfile $distrobase/examples/idas/serial/idasSlCrank_FSA_dns.out              || exit 1

$tar $tarfile $distrobase/examples/idas/C_openmp/README                  || exit 1
$tar $tarfile $distrobase/examples/idas/C_openmp/CMakeLists.txt          || exit 1
$tar $tarfile $distrobase/examples/idas/C_openmp/idasFoodWeb_bnd_omp.c   || exit 1
$tar $tarfile $distrobase/examples/idas/C_openmp/idasFoodWeb_bnd_omp.out || exit 1
$tar $tarfile $distrobase/examples/idas/C_openmp/idasFoodWeb_kry_omp.c   || exit 1
$tar $tarfile $distrobase/examples/idas/C_openmp/idasFoodWeb_kry_omp.out || exit 1

$tar $tarfile $distrobase/examples/idas/parallel/README                                    || exit 1
$tar $tarfile $distrobase/examples/idas/parallel/CMakeLists.txt                            || exit 1
$tar $tarfile $distrobase/examples/idas/parallel/idasBruss_ASAp_kry_bbd_p.c                || exit 1
$tar $tarfile $distrobase/examples/idas/parallel/idasBruss_ASAp_kry_bbd_p.out              || exit 1
$tar $tarfile $distrobase/examples/idas/parallel/idasBruss_FSA_kry_bbd_p.c                 || exit 1
$tar $tarfile $distrobase/examples/idas/parallel/idasBruss_FSA_kry_bbd_p.out               || exit 1
$tar $tarfile $distrobase/examples/idas/parallel/idasBruss_kry_bbd_p.c                     || exit 1
$tar $tarfile $distrobase/examples/idas/parallel/idasBruss_kry_bbd_p.out                   || exit 1
$tar $tarfile $distrobase/examples/idas/parallel/idasFoodWeb_kry_bbd_p.c                   || exit 1
$tar $tarfile $distrobase/examples/idas/parallel/idasFoodWeb_kry_bbd_p.out                 || exit 1
$tar $tarfile $distrobase/examples/idas/parallel/idasFoodWeb_kry_p.c                       || exit 1
$tar $tarfile $distrobase/examples/idas/parallel/idasFoodWeb_kry_p.out                     || exit 1
$tar $tarfile $distrobase/examples/idas/parallel/idasHeat2D_FSA_kry_bbd_p.c                || exit 1
$tar $tarfile $distrobase/examples/idas/parallel/idasHeat2D_FSA_kry_bbd_p_-sensi_stg_t.out || exit 1
$tar $tarfile $distrobase/examples/idas/parallel/idasHeat2D_kry_bbd_p.c                    || exit 1
$tar $tarfile $distrobase/examples/idas/parallel/idasHeat2D_kry_bbd_p.out                  || exit 1
$tar $tarfile $distrobase/examples/idas/parallel/idasHeat2D_kry_p.c                        || exit 1
$tar $tarfile $distrobase/examples/idas/parallel/idasHeat2D_kry_p.out                      || exit 1

$tar $tarfile $distrobase/examples/idas/F2003_serial/README                         || exit 1
$tar $tarfile $distrobase/examples/idas/F2003_serial/CMakeLists.txt                 || exit 1
$tar $tarfile $distrobase/examples/idas/F2003_serial/idasAkzoNob_ASAi_dns_f2003.f90 || exit 1
$tar $tarfile $distrobase/examples/idas/F2003_serial/idasAkzoNob_ASAi_dns_f2003.out || exit 1
$tar $tarfile $distrobase/examples/idas/F2003_serial/idasHeat2D_kry_f2003.f90       || exit 1
$tar $tarfile $distrobase/examples/idas/F2003_serial/idasHeat2D_kry_f2003.out       || exit 1
