#!/bin/sh

tarfile=$1
distrobase=$2
doc=$3

echo "   --- Add idas module to $tarfile"

if [ $doc = "T" ]; then
#tar ufv $tarfile $distrobase/doc/idas/idas_guide.ps
tar ufv $tarfile $distrobase/doc/idas/idas_guide.pdf
#tar ufv $tarfile $distrobase/doc/idas/idas_examples.ps
tar ufv $tarfile $distrobase/doc/idas/idas_examples.pdf
fi

tar ufv $tarfile $distrobase/include/idas/idas.h
tar ufv $tarfile $distrobase/include/idas/idas_direct.h
tar ufv $tarfile $distrobase/include/idas/idas_dense.h
tar ufv $tarfile $distrobase/include/idas/idas_band.h
tar ufv $tarfile $distrobase/include/idas/idas_sparse.h
tar ufv $tarfile $distrobase/include/idas/idas_lapack.h
tar ufv $tarfile $distrobase/include/idas/idas_spgmr.h
tar ufv $tarfile $distrobase/include/idas/idas_spbcgs.h
tar ufv $tarfile $distrobase/include/idas/idas_sptfqmr.h
tar ufv $tarfile $distrobase/include/idas/idas_spils.h
tar ufv $tarfile $distrobase/include/idas/idas_bbdpre.h
tar ufv $tarfile $distrobase/include/idas/idas_superlumt.h

tar ufv $tarfile $distrobase/src/idas/LICENSE
tar ufv $tarfile $distrobase/src/idas/README
tar ufv $tarfile $distrobase/src/idas/Makefile.in
tar ufv $tarfile $distrobase/src/idas/CMakeLists.txt

tar ufv $tarfile $distrobase/src/idas/idas.c
tar ufv $tarfile $distrobase/src/idas/idaa.c
tar ufv $tarfile $distrobase/src/idas/idas_io.c
tar ufv $tarfile $distrobase/src/idas/idaa_io.c
tar ufv $tarfile $distrobase/src/idas/idas_ic.c
tar ufv $tarfile $distrobase/src/idas/idas_direct.c
tar ufv $tarfile $distrobase/src/idas/idas_dense.c
tar ufv $tarfile $distrobase/src/idas/idas_sparse.c
tar ufv $tarfile $distrobase/src/idas/idas_band.c
tar ufv $tarfile $distrobase/src/idas/idas_lapack.c
tar ufv $tarfile $distrobase/src/idas/idas_spils.c
tar ufv $tarfile $distrobase/src/idas/idas_spgmr.c
tar ufv $tarfile $distrobase/src/idas/idas_spbcgs.c
tar ufv $tarfile $distrobase/src/idas/idas_sptfqmr.c
tar ufv $tarfile $distrobase/src/idas/idas_bbdpre.c
tar ufv $tarfile $distrobase/src/idas/idas_impl.h
tar ufv $tarfile $distrobase/src/idas/idas_direct_impl.h
tar ufv $tarfile $distrobase/src/idas/idas_sparse_impl.h
tar ufv $tarfile $distrobase/src/idas/idas_spils_impl.h
tar ufv $tarfile $distrobase/src/idas/idas_bbdpre_impl.h

echo "   --- Add idas examples to $tarfile"

tar ufv $tarfile $distrobase/examples/idas/serial/README
tar ufv $tarfile $distrobase/examples/idas/serial/Makefile.in
tar ufv $tarfile $distrobase/examples/idas/serial/CMakeLists.txt
tar ufv $tarfile $distrobase/examples/idas/serial/idasAkzoNob_ASAi_dns.c
tar ufv $tarfile $distrobase/examples/idas/serial/idasAkzoNob_ASAi_dns.out
tar ufv $tarfile $distrobase/examples/idas/serial/idasAkzoNob_dns.c
tar ufv $tarfile $distrobase/examples/idas/serial/idasAkzoNob_dns.out
tar ufv $tarfile $distrobase/examples/idas/serial/idasFoodWeb_bnd.c
tar ufv $tarfile $distrobase/examples/idas/serial/idasFoodWeb_bnd.out
tar ufv $tarfile $distrobase/examples/idas/serial/idasHeat2D_bnd.c
tar ufv $tarfile $distrobase/examples/idas/serial/idasHeat2D_bnd.out
tar ufv $tarfile $distrobase/examples/idas/serial/idasHeat2D_kry.c
tar ufv $tarfile $distrobase/examples/idas/serial/idasHeat2D_kry.out
tar ufv $tarfile $distrobase/examples/idas/serial/idasHessian_ASA_FSA.c
tar ufv $tarfile $distrobase/examples/idas/serial/idasHessian_ASA_FSA.out
tar ufv $tarfile $distrobase/examples/idas/serial/idasKrylovDemo_ls.c
tar ufv $tarfile $distrobase/examples/idas/serial/idasKrylovDemo_ls.out
tar ufv $tarfile $distrobase/examples/idas/serial/idasRoberts_ASAi_dns.c
tar ufv $tarfile $distrobase/examples/idas/serial/idasRoberts_ASAi_dns.out
tar ufv $tarfile $distrobase/examples/idas/serial/idasRoberts_sps.c
tar ufv $tarfile $distrobase/examples/idas/serial/idasRoberts_dns.c
tar ufv $tarfile $distrobase/examples/idas/serial/idasRoberts_dns.out
tar ufv $tarfile $distrobase/examples/idas/serial/idasRoberts_FSA_dns.c
tar ufv $tarfile $distrobase/examples/idas/serial/idasRoberts_FSA_dns.out
tar ufv $tarfile $distrobase/examples/idas/serial/idasSlCrank_dns.c
tar ufv $tarfile $distrobase/examples/idas/serial/idasSlCrank_dns.out
tar ufv $tarfile $distrobase/examples/idas/serial/idasSlCrank_FSA_dns.c
tar ufv $tarfile $distrobase/examples/idas/serial/idasSlCrank_FSA_dns.out

tar ufv $tarfile $distrobase/examples/idas/parallel/README
tar ufv $tarfile $distrobase/examples/idas/parallel/Makefile.in
tar ufv $tarfile $distrobase/examples/idas/parallel/CMakeLists.txt
tar ufv $tarfile $distrobase/examples/idas/parallel/idasBruss_ASAp_kry_bbd_p.c
tar ufv $tarfile $distrobase/examples/idas/parallel/idasBruss_ASAp_kry_bbd_p.out
tar ufv $tarfile $distrobase/examples/idas/parallel/idasBruss_FSA_kry_bbd_p.c
tar ufv $tarfile $distrobase/examples/idas/parallel/idasBruss_FSA_kry_bbd_p.out
tar ufv $tarfile $distrobase/examples/idas/parallel/idasBruss_kry_bbd_p.c
tar ufv $tarfile $distrobase/examples/idas/parallel/idasBruss_kry_bbd_p.out
tar ufv $tarfile $distrobase/examples/idas/parallel/idasFoodWeb_kry_bbd_p.c
tar ufv $tarfile $distrobase/examples/idas/parallel/idasFoodWeb_kry_bbd_p.out
tar ufv $tarfile $distrobase/examples/idas/parallel/idasFoodWeb_kry_p.c
tar ufv $tarfile $distrobase/examples/idas/parallel/idasFoodWeb_kry_p.out
tar ufv $tarfile $distrobase/examples/idas/parallel/idasHeat2D_FSA_kry_bbd_p.c
tar ufv $tarfile $distrobase/examples/idas/parallel/idasHeat2D_FSA_kry_bbd_p.out
tar ufv $tarfile $distrobase/examples/idas/parallel/idasHeat2D_kry_bbd_p.c
tar ufv $tarfile $distrobase/examples/idas/parallel/idasHeat2D_kry_bbd_p.out
tar ufv $tarfile $distrobase/examples/idas/parallel/idasHeat2D_kry_p.c
tar ufv $tarfile $distrobase/examples/idas/parallel/idasHeat2D_kry_p.out

