#!/bin/sh

tarfile=$1
distrobase=$2
doc=$3

echo "   --- Add sundialsTB files to $tarfile"

if [ $doc = "T" ]; then
tar ufv $tarfile $distrobase/sundialsTB/doc/sundialsTB.pdf
#tar ufv $tarfile $distrobase/sundialsTB/doc/sundialsTB.ps
fi

tar ufv $tarfile $distrobase/sundialsTB/README
tar ufv $tarfile $distrobase/sundialsTB/LICENSE
tar ufv $tarfile $distrobase/sundialsTB/Makefile.in

tar ufv $tarfile $distrobase/sundialsTB/install_STB.m
tar ufv $tarfile $distrobase/sundialsTB/startup_STB.in

tar ufv $tarfile $distrobase/sundialsTB/nvector/Contents.m
tar ufv $tarfile $distrobase/sundialsTB/nvector/N_VDotProd.m
tar ufv $tarfile $distrobase/sundialsTB/nvector/N_VL1Norm.m
tar ufv $tarfile $distrobase/sundialsTB/nvector/N_VMax.m
tar ufv $tarfile $distrobase/sundialsTB/nvector/N_VMaxNorm.m
tar ufv $tarfile $distrobase/sundialsTB/nvector/N_VMin.m
tar ufv $tarfile $distrobase/sundialsTB/nvector/N_VWL2Norm.m
tar ufv $tarfile $distrobase/sundialsTB/nvector/N_VWrmsNorm.m

tar ufv $tarfile $distrobase/sundialsTB/nvector/src/nvm.h
tar ufv $tarfile $distrobase/sundialsTB/nvector/src/nvm_ops.c
tar ufv $tarfile $distrobase/sundialsTB/nvector/src/nvm_parallel.c
tar ufv $tarfile $distrobase/sundialsTB/nvector/src/nvm_serial.c

tar ufv $tarfile $distrobase/sundialsTB/putils/Contents.m
tar ufv $tarfile $distrobase/sundialsTB/putils/mpirun.m
tar ufv $tarfile $distrobase/sundialsTB/putils/mpiruns.m
tar ufv $tarfile $distrobase/sundialsTB/putils/mpistart.m

# CVODES files

tar ufv $tarfile $distrobase/sundialsTB/cvodes/Contents.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeAdjInit.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeAdjReInit.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeFree.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeGet.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeGetStatsB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeGetStats.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeInitB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeInit.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVode.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeMonitorB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeMonitorB_octave.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeMonitor.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeMonitor_octave.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeQuadInitB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeQuadInit.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeQuadReInitB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeQuadReInit.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeQuadSetOptions.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeReInitB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeReInit.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeSensInit.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeSensReInit.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeSensSetOptions.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeSensToggleOff.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeSetB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeSet.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeSetOptions.m

tar ufv $tarfile $distrobase/sundialsTB/cvodes/function_types/CVBandJacFnB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/function_types/CVBandJacFn.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/function_types/CVDenseJacFnB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/function_types/CVDenseJacFn.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/function_types/CVGcommFnB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/function_types/CVGcommFn.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/function_types/CVGlocalFnB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/function_types/CVGlocalFn.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/function_types/CVJacTimesVecFnB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/function_types/CVJacTimesVecFn.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/function_types/CVMonitorFnB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/function_types/CVMonitorFn.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/function_types/CVPrecSetupFnB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/function_types/CVPrecSetupFn.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/function_types/CVPrecSolveFnB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/function_types/CVPrecSolveFn.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/function_types/CVQuadRhsFnB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/function_types/CVQuadRhsFn.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/function_types/CVRhsFnB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/function_types/CVRhsFn.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/function_types/CVRootFn.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/function_types/CVSensRhsFn.m

tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/Contents.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_bjacB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_bjac.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_djacB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_djac.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_gcomB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_gcom.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_glocB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_gloc.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_jtvB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_jtv.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_monitorB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_monitor.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_options.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_psetB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_pset.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_psolB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_psol.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_rhsB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_rhs.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_rhsQB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_rhsQ.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_rhsS.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_root.m

tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/src/cvm.c
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/src/cvm.h
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/src/cvmOpts.c
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/src/cvmWrap.c

tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/mcvsAdvDiff_bnd.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/mcvsDiscRHS_dns.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/mcvsDiscSOL_dns.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/mcvsDiurnal_kry.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/mcvsHessian_FSA_ASA.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/mcvsOzone_FSA_dns.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/mcvsPleiades_non.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/mcvsPollut_FSA_dns.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/mcvsRoberts_ASAi_dns.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/mcvsRoberts_dns.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/mcvsRoberts_FSA_dns.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/mcvsVanDPol_dns.m

tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_par/mcvsAdvDiff_FSA_non_p.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_par/mcvsAtmDisp_kry_bbd_p.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_par/mcvsDecoupl_non_p.m

# IDAS files

tar ufv $tarfile $distrobase/sundialsTB/idas/Contents.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAAdjInit.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAAdjReInit.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDACalcICB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDACalcIC.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAFree.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAGet.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAGetStatsB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAGetStats.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAInitB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAInit.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAMonitorB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAMonitorB_octave.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAMonitor.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAMonitor_octave.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAQuadInitB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAQuadInit.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAQuadReInitB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAQuadReInit.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAQuadSetOptions.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAReInitB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAReInit.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDASensInit.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDASensReInit.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDASensSetOptions.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDASensToggleOff.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDASetB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDASet.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDASetOptions.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDASolveB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDASolve.m

tar ufv $tarfile $distrobase/sundialsTB/idas/function_types/IDABandJacFnB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/function_types/IDABandJacFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/function_types/IDADenseJacFnB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/function_types/IDADenseJacFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/function_types/IDAGcommFnB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/function_types/IDAGcommFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/function_types/IDAGlocalFnB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/function_types/IDAGlocalFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/function_types/IDAJacTimesVecFnB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/function_types/IDAJacTimesVecFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/function_types/IDAMonitorFnB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/function_types/IDAMonitorFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/function_types/IDAPrecSetupFnB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/function_types/IDAPrecSetupFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/function_types/IDAPrecSolveFnB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/function_types/IDAPrecSolveFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/function_types/IDAQuadRhsFnB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/function_types/IDAQuadRhsFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/function_types/IDAResFnB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/function_types/IDAResFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/function_types/IDARootFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/function_types/IDASensResFn.m

tar ufv $tarfile $distrobase/sundialsTB/idas/idm/Contents.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_bjacB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_bjac.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_djacB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_djac.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_gcomB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_gcom.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_glocB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_gloc.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_jtvB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_jtv.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_monitorB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_monitor.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_options.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_psetB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_pset.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_psolB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_psol.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_resB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_res.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_resS.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_rhsQB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_rhsQ.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_root.m

tar ufv $tarfile $distrobase/sundialsTB/idas/idm/src/idm.c
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/src/idm.h
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/src/idmOpts.c
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/src/idmWrap.c

tar ufv $tarfile $distrobase/sundialsTB/idas/examples_ser/midasBruss_ASA_dns.m
tar ufv $tarfile $distrobase/sundialsTB/idas/examples_ser/midasBruss_dns.m
tar ufv $tarfile $distrobase/sundialsTB/idas/examples_ser/midasHeat2D_bnd.m
tar ufv $tarfile $distrobase/sundialsTB/idas/examples_ser/midasPendI1_dns.m
tar ufv $tarfile $distrobase/sundialsTB/idas/examples_ser/midasPendI2_dns.m
tar ufv $tarfile $distrobase/sundialsTB/idas/examples_ser/midasReInit_dns.m
tar ufv $tarfile $distrobase/sundialsTB/idas/examples_ser/midasRoberts_ASAi_dns.m
tar ufv $tarfile $distrobase/sundialsTB/idas/examples_ser/midasRoberts_dns.m
tar ufv $tarfile $distrobase/sundialsTB/idas/examples_ser/midasSlCrank_dns.m
tar ufv $tarfile $distrobase/sundialsTB/idas/examples_ser/midasSlCrank_FSA_dns.m

# KINSOL files

tar ufv $tarfile $distrobase/sundialsTB/kinsol/Contents.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/KINFree.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/KINGetStats.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/KINInit.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/KINSetOptions.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/KINSol.m

tar ufv $tarfile $distrobase/sundialsTB/kinsol/function_types/KINBandJacFn.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/function_types/KINDenseJacFn.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/function_types/KINGcommFn.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/function_types/KINGlocalFn.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/function_types/KINJacTimesVecFn.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/function_types/KINPrecSetupFn.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/function_types/KINPrecSolveFn.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/function_types/KINSysFn.m

tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/Contents.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/kim_bjac.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/kim_djac.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/kim_gcom.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/kim_gloc.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/kim_info.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/kim_jtv.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/kim_pset.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/kim_psol.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/kim_sys.m

tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/src/kim.c
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/src/kim.h
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/src/kimOpts.c
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/src/kimWrap.c

tar ufv $tarfile $distrobase/sundialsTB/kinsol/examples_ser/mkinDiagon_kry.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/examples_ser/mkinFerTron_dns.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/examples_ser/mkinRoboKin_dns.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/examples_ser/mkinTest_dns.m

tar ufv $tarfile $distrobase/sundialsTB/kinsol/examples_par/mkinDiagon_kry_p.m


