#!/bin/sh

tarfile=$1
distrobase=$2
doc=$3

echo "   --- Add sundialsTB files to $tarfile"

if [ $doc = "T" ]; then
tar ufv $tarfile $distrobase/sundialsTB/doc/sundialsTB.pdf
#tar ufv $tarfile $distrobase/sundialsTB/doc/sundialsTB.ps
fi

tar ufv $tarfile $distrobase/sundialsTB/README
tar ufv $tarfile $distrobase/sundialsTB/LICENSE
tar ufv $tarfile $distrobase/sundialsTB/Makefile.in

tar ufv $tarfile $distrobase/sundialsTB/install_STB.m
tar ufv $tarfile $distrobase/sundialsTB/startup_STB.in

tar ufv $tarfile $distrobase/sundialsTB/nvector/Contents.m
tar ufv $tarfile $distrobase/sundialsTB/nvector/N_VDotProd.m
tar ufv $tarfile $distrobase/sundialsTB/nvector/N_VL1Norm.m
tar ufv $tarfile $distrobase/sundialsTB/nvector/N_VMax.m
tar ufv $tarfile $distrobase/sundialsTB/nvector/N_VMaxNorm.m
tar ufv $tarfile $distrobase/sundialsTB/nvector/N_VMin.m
tar ufv $tarfile $distrobase/sundialsTB/nvector/N_VWL2Norm.m
tar ufv $tarfile $distrobase/sundialsTB/nvector/N_VWrmsNorm.m

tar ufv $tarfile $distrobase/sundialsTB/nvector/src/nvm.h
tar ufv $tarfile $distrobase/sundialsTB/nvector/src/nvm_ops.c
tar ufv $tarfile $distrobase/sundialsTB/nvector/src/nvm_parallel.c
tar ufv $tarfile $distrobase/sundialsTB/nvector/src/nvm_serial.c

tar ufv $tarfile $distrobase/sundialsTB/putils/Contents.m
tar ufv $tarfile $distrobase/sundialsTB/putils/mpirun.m
tar ufv $tarfile $distrobase/sundialsTB/putils/mpiruns.m
tar ufv $tarfile $distrobase/sundialsTB/putils/mpistart.m

tar ufv $tarfile $distrobase/sundialsTB/cvodes/Contents.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVadjMalloc.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVBandJacFn.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVDenseJacFn.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVGcommFn.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVGlocalFn.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVJacTimesVecFn.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVMonitorFn.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeFree.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeGet.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeGetStatsB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeGetStats.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVode.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeMallocB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeMalloc.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeMonitor.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeReInitB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeReInit.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeSensMalloc.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeSensReInit.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeSensToggleOff.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeSetFSAOptions.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVodeSetOptions.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVPrecSetupFn.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVPrecSolveFn.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVQuadRhsFn.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVRhsFn.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVRootFn.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/CVSensRhsFn.m

tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/Contents.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_bjac.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_djac.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_gcom.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_gloc.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_jtv.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_monitor.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_pset.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_psol.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_rhs.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_rhsQ.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_rhsS.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/cvm_root.m

tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/src/cvm.c
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/src/cvm.h
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/src/cvmOpts.c
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/src/cvmWrap.c
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/src/Makefile.in
tar ufv $tarfile $distrobase/sundialsTB/cvodes/cvm/src/setup.m.in

tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/cvadx.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/cvbx_f.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/cvbx_J.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/cvbx.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/cvbx_q.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/cvdx_fB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/cvdx_f.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/cvdx_fS.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/cvdx_g.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/cvdx_JB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/cvdx_J.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/cvdx.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/cvdx_qB.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/cvdx_q.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/cvfdx.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/cvkxb.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/cvkx_f.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/cvkx.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/cvkx_pset.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/cvkx_psol.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/pleiades_f.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/pleiades_J.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/pleiades.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/vdp_f.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/vdp_J.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_ser/vdp.m

tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_par/pvfnx_f.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_par/pvfnx.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_par/pvkx_fl.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_par/pvkx_f.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_par/pvkx.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_par/pvnx_f.m
tar ufv $tarfile $distrobase/sundialsTB/cvodes/examples_par/pvnx.m

tar ufv $tarfile $distrobase/sundialsTB/idas/Contents.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAadjMalloc.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDABandJacFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDADenseJacFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDACalcIC.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDACalcICB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAFree.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAGcommFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAGet.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAGetStatsB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAGetStats.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAGlocalFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAJacTimesVecFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAMallocB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAMalloc.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAMonitorFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAMonitor.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAPrecSetupFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAPrecSolveFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAQuadRhsFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAResFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAReInitB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDAReInit.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDARootFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDASensMalloc.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDASensReInit.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDASensResFn.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDASensToggle.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDASetFSAOptions.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDASetOptions.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDASolveB.m
tar ufv $tarfile $distrobase/sundialsTB/idas/IDASolve.m

tar ufv $tarfile $distrobase/sundialsTB/idas/idm/Contents.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_bjac.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_djac.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_gcom.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_gloc.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_jtv.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_monitor.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_pset.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_psol.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_res.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_resS.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_rhsQ.m
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/idm_root.m

tar ufv $tarfile $distrobase/sundialsTB/idas/idm/src/idm.c
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/src/idm.h
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/src/idmOpts.c
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/src/idmWrap.c
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/src/Makefile.in
tar ufv $tarfile $distrobase/sundialsTB/idas/idm/src/setup.m.in

tar ufv $tarfile $distrobase/sundialsTB/idas/examples_ser/idabanx_f.m
tar ufv $tarfile $distrobase/sundialsTB/idas/examples_ser/idabanx_ic.m
tar ufv $tarfile $distrobase/sundialsTB/idas/examples_ser/idabanx.m
tar ufv $tarfile $distrobase/sundialsTB/idas/examples_ser/idadenx_f.m
tar ufv $tarfile $distrobase/sundialsTB/idas/examples_ser/idadenx_g.m
tar ufv $tarfile $distrobase/sundialsTB/idas/examples_ser/idadenx_J.m
tar ufv $tarfile $distrobase/sundialsTB/idas/examples_ser/idadenx.m
tar ufv $tarfile $distrobase/sundialsTB/idas/examples_ser/pend.m
tar ufv $tarfile $distrobase/sundialsTB/idas/examples_ser/pendGGL.m

tar ufv $tarfile $distrobase/sundialsTB/kinsol/Contents.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/KINBandJacFn.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/KINDenseJacFn.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/KINFree.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/KINGcommFn.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/KINGetStats.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/KINGlocalFn.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/KINJacTimesVecFn.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/KINMalloc.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/KINPrecSetupFn.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/KINPrecSolveFn.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/KINSetOptions.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/KINSol.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/KINSysFn.m

tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/Contents.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/kim_bjac.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/kim_djac.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/kim_gcom.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/kim_gloc.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/kim_info.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/kim_jtv.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/kim_pset.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/kim_psol.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/kim_sys.m

tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/src/kim.c
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/src/kim.h
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/src/kimOpts.c
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/src/kimWrap.c
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/src/Makefile.in
tar ufv $tarfile $distrobase/sundialsTB/kinsol/kim/src/setup.m.in

tar ufv $tarfile $distrobase/sundialsTB/kinsol/examples_ser/kindiag.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/examples_ser/kindiag_pset.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/examples_ser/kindiag_psol.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/examples_ser/kindiag_sys.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/examples_ser/kindx.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/examples_ser/kindx_sys.m

tar ufv $tarfile $distrobase/sundialsTB/kinsol/examples_par/kindiagp.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/examples_par/kindiagp_pset.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/examples_par/kindiagp_psol.m
tar ufv $tarfile $distrobase/sundialsTB/kinsol/examples_par/kindiagp_sys.m


