#!/bin/sh
#
# File tarcvodes: Script to build CVODES tar-file.
# Version of 4 September 2002.
#

#---------------------------------------------------------
# Test if the script is executed from within its directory
#---------------------------------------------------------
scriptbase=`basename $0`
if [ ! -f "$scriptbase" ]
then
    echo "This script must be executed from within its directory"
    exit 1
fi

#-------------
# Define flags
#-------------
err=F   # Error flag
hlp=F   # Help flag
ser=F   # Serial flag
par=F   # Parallel flag
fnm=F   # File name flag

#------------------
# Process arguments
#------------------
if [ $# -eq 0 ]
then
   err=T
else
   while getopts asphf: name
   do
     case $name in
        h) hlp=T;;
        a) ser=T;par=T;;
        s) ser=T;;
        p) par=T;;
        f) fnm=T;filename=$OPTARG;;
        ?) err=T;;
     esac
   done
fi

#------------------
# Define some names
#------------------
scriptdir=`pwd`
distrodir=`echo $PWD | sed -e 's/scripts//'`
distrobase=`basename $distrodir`

#------------
# Print usage
#------------
if [ $err = "T" -o $hlp = "T" ]
then
    echo "Usage: tarcvodes [option | file]"
    echo "   -a      : both serial and parallel"
    echo "   -s      : serial"
    echo "   -p      : parallel"
    echo "   -h      : help"
    echo "   -f file : output to file" 
    echo "Note: This script must be executed from within its directory" 
    echo "      Default file will be created in $distrodir"
    if [ $err = "T" -o \( $ser = "F" -a $par = "F" \) ]
    then
        exit 1
    fi
fi

#-----------------
# Create file name
#-----------------
if [ $fnm != "T" ]
then
    if [ $ser = "T" -a $par = "F" ]
    then
        filename="cvodes_ser.tar"
    elif [ $ser = "F" -a $par = "T" ]
    then
        filename="cvodes_par.tar"
    else
        filename="cvodes.tar"
    fi
    tarfile=$distrodir$filename
else
    filebase=`basename $filename`
    cd `dirname $filename`
    filedir=`pwd`
    tarfile=$filedir/$filebase
    cd $scriptdir
fi

#----------------
# Create tar file
#----------------

cd ../..
echo "Generate $distrobase distribution tar-file $tarfile"

# Add top level files
#--------------------

echo "  Add top-level files/directories"

tar cf $tarfile $distrobase/configure
tar uf $tarfile $distrobase/tarch

tar uf $tarfile $distrobase/Makefile.in

tar uf $tarfile $distrobase/INSTALL
tar uf $tarfile $distrobase/README

tar uf $tarfile $distrobase/doc/Readme

# Add SHARED module
#------------------

echo "  Add shared module"

tar uf $tarfile $distrobase/shared/LICENSE

tar uf $tarfile $distrobase/shared/doc/nvecreadme

tar uf $tarfile $distrobase/shared/include/sundialstypes.h
tar uf $tarfile $distrobase/shared/include/sundialsmath.h
tar uf $tarfile $distrobase/shared/include/nvector.h
tar uf $tarfile $distrobase/shared/include/dense.h
tar uf $tarfile $distrobase/shared/include/smalldense.h
tar uf $tarfile $distrobase/shared/include/band.h
tar uf $tarfile $distrobase/shared/include/spgmr.h
tar uf $tarfile $distrobase/shared/include/iterativ.h
tar uf $tarfile $distrobase/shared/include/fcmixpar.h

tar uf $tarfile $distrobase/shared/source/Makefile.in
tar uf $tarfile $distrobase/shared/source/sundialsmath.c
tar uf $tarfile $distrobase/shared/source/nvector.c
tar uf $tarfile $distrobase/shared/source/dense.c
tar uf $tarfile $distrobase/shared/source/smalldense.c
tar uf $tarfile $distrobase/shared/source/band.c
tar uf $tarfile $distrobase/shared/source/spgmr.c
tar uf $tarfile $distrobase/shared/source/iterativ.c

if [ $ser = "T" ]
then
    tar uf $tarfile $distrobase/nvec_ser/nvector_serial.h
    tar uf $tarfile $distrobase/nvec_ser/fnvector_serial.h

    tar uf $tarfile $distrobase/nvec_ser/Makefile.in
    tar uf $tarfile $distrobase/nvec_ser/nvector_serial.c
    tar uf $tarfile $distrobase/nvec_ser/fnvector_serial.c
fi

if [ $par = "T" ]
then
    tar uf $tarfile $distrobase/nvec_par/nvector_parallel.h
    tar uf $tarfile $distrobase/nvec_par/fnvector_parallel.h

    tar uf $tarfile $distrobase/nvec_par/Makefile.in
    tar uf $tarfile $distrobase/nvec_par/nvector_parallel.c
    tar uf $tarfile $distrobase/nvec_par/fnvector_parallel.c
fi

# Add CVODES module
#------------------

echo "  Add cvodes module"

tar uf $tarfile $distrobase/cvodes/LICENSE

tar uf $tarfile $distrobase/cvodes/doc/cvsreadme
tar uf $tarfile $distrobase/cvodes/doc/cvs_guide.ps
tar uf $tarfile $distrobase/cvodes/doc/cvs_guide.pdf

tar uf $tarfile $distrobase/cvodes/include/cvodes.h
tar uf $tarfile $distrobase/cvodes/include/cvodea.h
tar uf $tarfile $distrobase/cvodes/include/cvsdense.h
tar uf $tarfile $distrobase/cvodes/include/cvsband.h
tar uf $tarfile $distrobase/cvodes/include/cvsdiag.h
tar uf $tarfile $distrobase/cvodes/include/cvsspgmr.h
tar uf $tarfile $distrobase/cvodes/include/cvsbandpre.h
tar uf $tarfile $distrobase/cvodes/include/cvsbbdpre.h

tar uf $tarfile $distrobase/cvodes/source/Makefile.in
tar uf $tarfile $distrobase/cvodes/source/cvodes.c
tar uf $tarfile $distrobase/cvodes/source/cvodea.c
tar uf $tarfile $distrobase/cvodes/source/cvsdense.c
tar uf $tarfile $distrobase/cvodes/source/cvsband.c
tar uf $tarfile $distrobase/cvodes/source/cvsdiag.c
tar uf $tarfile $distrobase/cvodes/source/cvsspgmr.c
tar uf $tarfile $distrobase/cvodes/source/cvsbandpre.c
tar uf $tarfile $distrobase/cvodes/source/cvsbbdpre.c

if [ $ser = "T" ]
then
    tar uf $tarfile $distrobase/cvodes/examples_ser/Makefile.in
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvdx.c
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvdx.out
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvbx.c
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvbx.out
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvkx.c
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvkx.out
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvkxb.c
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvkxb.out
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvdemd.c
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvdemd.out
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvdemk.c
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvdemk.out

    tar uf $tarfile $distrobase/cvodes/examples_ser/cvfdx.c
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvfdx.out1
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvfdx.out2
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvfnx.c
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvfnx.out1
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvfnx.out2
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvfkx.c
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvfkx.out1
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvfkx.out2

    tar uf $tarfile $distrobase/cvodes/examples_ser/cvadx.c
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvadx.out
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvabx.c
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvabx.out
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvakx.c
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvakx.out
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvakxb.c
    tar uf $tarfile $distrobase/cvodes/examples_ser/cvakxb.out
fi


if [ $par = "T" ]
then
    tar uf $tarfile $distrobase/cvodes/examples_par/Makefile.in
    tar uf $tarfile $distrobase/cvodes/examples_par/pvnx.c
    tar uf $tarfile $distrobase/cvodes/examples_par/pvnx.out
    tar uf $tarfile $distrobase/cvodes/examples_par/pvkx.c
    tar uf $tarfile $distrobase/cvodes/examples_par/pvkx.out
    tar uf $tarfile $distrobase/cvodes/examples_par/pvkxb.c
    tar uf $tarfile $distrobase/cvodes/examples_par/pvkxb.out

    tar uf $tarfile $distrobase/cvodes/examples_par/pvfnx.c
    tar uf $tarfile $distrobase/cvodes/examples_par/pvfnx.out1
    tar uf $tarfile $distrobase/cvodes/examples_par/pvfnx.out2
    tar uf $tarfile $distrobase/cvodes/examples_par/pvfkx.c
    tar uf $tarfile $distrobase/cvodes/examples_par/pvfkx.out1
    tar uf $tarfile $distrobase/cvodes/examples_par/pvfkx.out2

    tar uf $tarfile $distrobase/cvodes/examples_par/pvanx.c
    tar uf $tarfile $distrobase/cvodes/examples_par/pvanx.out
fi

#----End of tarcvodes script file----
