#!/bin/sh
#
# File tarcvodes: Script to build CVODES tar-file.
# Version of 4 April 2002.
#
#-------------
# Define flags
#-------------
err=F   # Error flag
hlp=F   # Help flag
ser=F   # Serial flag
par=F   # Parallel flag
fnm=F   # File name flag

#------------------
# Process arguments
#------------------
if [ $# -eq 0 ]
then
   err=T
else
   while getopts asphf: name
   do
     case $name in
        h) hlp=T;;
        a) ser=T;par=T;;
        s) ser=T;;
        p) par=T;;
        f) fnm=T;filename=$OPTARG;;
        ?) err=T;;
     esac
   done
fi

#------------
# Print usage
#------------
if [ $err = "T" -o $hlp = "T" ]
then
    echo "Usage: tarcvodes [option | file]"
    echo "   -a      : both serial and parallel"
    echo "   -s      : serial"
    echo "   -p      : parallel"
    echo "   -h      : help"
    echo "   -f file : output to file" 
    if [ $err = "T" -o \( $ser = "F" -a $par = "F" \) ]
    then
        exit 1
    fi
fi

#-----------------
# Create file name
#-----------------
if [ $fnm != "T" ]
then
    if [ $ser = "T" -a $par = "F" ]
    then
        filename="cvodes_ser.tar"
    elif [ $ser = "F" -a $par = "T" ]
    then
        filename="cvodes_par.tar"
    else
        filename="cvodes.tar"
    fi
fi

#----------------
# Create tar file
#----------------

cd ../..
if [ $fnm != "T" ]
then
    echo "Generate tar file $PWD/$filename"
else
    echo "Generate tar file $filename"
fi

# Add top level files
#--------------------

echo "  Add top-level files/directories"

tar cf $filename sundials/Makefile

tar uf $filename sundials/lib/.dontremove

tar uf $filename sundials/include/.dontremove

tar uf $filename sundials/doc/Readme
tar uf $filename sundials/doc/dirstruc

# Add SHARED module
#------------------

echo "  Add shared module"

tar uf $filename sundials/shared/doc/nvecreadme

tar uf $filename sundials/shared/lib/.dontremove

tar uf $filename sundials/shared/include/sundialstypes.h
tar uf $filename sundials/shared/include/sundialsmath.h
tar uf $filename sundials/shared/include/nvector.h
tar uf $filename sundials/shared/include/dense.h
tar uf $filename sundials/shared/include/smalldense.h
tar uf $filename sundials/shared/include/band.h
tar uf $filename sundials/shared/include/spgmr.h
tar uf $filename sundials/shared/include/iterativ.h
tar uf $filename sundials/shared/include/fcmixpar.h

tar uf $filename sundials/shared/source/Makefile
tar uf $filename sundials/shared/source/sundialsmath.c
tar uf $filename sundials/shared/source/nvector.c
tar uf $filename sundials/shared/source/dense.c
tar uf $filename sundials/shared/source/smalldense.c
tar uf $filename sundials/shared/source/band.c
tar uf $filename sundials/shared/source/spgmr.c
tar uf $filename sundials/shared/source/iterativ.c

if [ $ser = "T" ]
then
    tar uf $filename sundials/shared/include/nvector_serial.h
    tar uf $filename sundials/shared/include/fnvector_serial.h

    tar uf $filename sundials/shared/source/nvecserial.mk
    tar uf $filename sundials/shared/source/nvector_serial.c
    tar uf $filename sundials/shared/source/fnvector_serial.c
fi

if [ $par = "T" ]
then
    tar uf $filename sundials/shared/include/nvector_parallel.h
    tar uf $filename sundials/shared/include/fnvector_parallel.h

    tar uf $filename sundials/shared/source/nvecparallel.mk
    tar uf $filename sundials/shared/source/nvector_parallel.c
    tar uf $filename sundials/shared/source/fnvector_parallel.c
fi

# Add CVODES module
#------------------

echo "  Add cvodes module"

tar uf $filename sundials/cvodes/include/cvodes.h
tar uf $filename sundials/cvodes/include/cvodea.h
tar uf $filename sundials/cvodes/include/cvsdense.h
tar uf $filename sundials/cvodes/include/cvsband.h
tar uf $filename sundials/cvodes/include/cvsdiag.h
tar uf $filename sundials/cvodes/include/cvsspgmr.h
tar uf $filename sundials/cvodes/include/cvsbandpre.h
tar uf $filename sundials/cvodes/include/cvsbbdpre.h

tar uf $filename sundials/cvodes/source/Makefile
tar uf $filename sundials/cvodes/source/cvodes.c
tar uf $filename sundials/cvodes/source/cvodea.c
tar uf $filename sundials/cvodes/source/cvsdense.c
tar uf $filename sundials/cvodes/source/cvsband.c
tar uf $filename sundials/cvodes/source/cvsdiag.c
tar uf $filename sundials/cvodes/source/cvsspgmr.c
tar uf $filename sundials/cvodes/source/cvsbandpre.c
tar uf $filename sundials/cvodes/source/cvsbbdpre.c

tar uf $filename sundials/cvodes/lib/.dontremove

tar uf $filename sundials/cvodes/examples/Makefile

tar uf $filename sundials/cvodes/fwd_examples/Makefile

tar uf $filename sundials/cvodes/adj_examples/Makefile

if [ $ser = "T" ]
then
    tar uf $filename sundials/cvodes/examples/cvx_ser.mk
    tar uf $filename sundials/cvodes/examples/cvdx.c
    tar uf $filename sundials/cvodes/examples/cvdx.out
    tar uf $filename sundials/cvodes/examples/cvbx.c
    tar uf $filename sundials/cvodes/examples/cvbx.out
    tar uf $filename sundials/cvodes/examples/cvkx.c
    tar uf $filename sundials/cvodes/examples/cvkx.out
    tar uf $filename sundials/cvodes/examples/cvkxb.c
    tar uf $filename sundials/cvodes/examples/cvkxb.out
    tar uf $filename sundials/cvodes/examples/cvdemd.c
    tar uf $filename sundials/cvodes/examples/cvdemd.out
    tar uf $filename sundials/cvodes/examples/cvdemk.c
    tar uf $filename sundials/cvodes/examples/cvdemk.out

    tar uf $filename sundials/cvodes/fwd_examples/cvfx_ser.mk
    tar uf $filename sundials/cvodes/fwd_examples/cvfdx.c
    tar uf $filename sundials/cvodes/fwd_examples/cvfdx.out1
    tar uf $filename sundials/cvodes/fwd_examples/cvfdx.out2
    tar uf $filename sundials/cvodes/fwd_examples/cvfnx.c
    tar uf $filename sundials/cvodes/fwd_examples/cvfnx.out1
    tar uf $filename sundials/cvodes/fwd_examples/cvfnx.out2
    tar uf $filename sundials/cvodes/fwd_examples/cvfkx.c
    tar uf $filename sundials/cvodes/fwd_examples/cvfkx.out1
    tar uf $filename sundials/cvodes/fwd_examples/cvfkx.out2

    tar uf $filename sundials/cvodes/adj_examples/cvax_ser.mk
    tar uf $filename sundials/cvodes/adj_examples/cvadx.c
    tar uf $filename sundials/cvodes/adj_examples/cvadx.out
    tar uf $filename sundials/cvodes/adj_examples/cvabx.c
    tar uf $filename sundials/cvodes/adj_examples/cvabx.out
    tar uf $filename sundials/cvodes/adj_examples/cvakx.c
    tar uf $filename sundials/cvodes/adj_examples/cvakx.out
    tar uf $filename sundials/cvodes/adj_examples/cvakxb.c
    tar uf $filename sundials/cvodes/adj_examples/cvakxb.out
fi


if [ $par = "T" ]
then
    tar uf $filename sundials/cvodes/examples/cvx_par.mk
    tar uf $filename sundials/cvodes/examples/pvnx.c
    tar uf $filename sundials/cvodes/examples/pvnx.out
    tar uf $filename sundials/cvodes/examples/pvkx.c
    tar uf $filename sundials/cvodes/examples/pvkx.out
    tar uf $filename sundials/cvodes/examples/pvkxb.c
    tar uf $filename sundials/cvodes/examples/pvkxb.out

    tar uf $filename sundials/cvodes/fwd_examples/cvfx_par.mk
    tar uf $filename sundials/cvodes/fwd_examples/pvfnx.c
    tar uf $filename sundials/cvodes/fwd_examples/pvfnx.out1
    tar uf $filename sundials/cvodes/fwd_examples/pvfnx.out2
    tar uf $filename sundials/cvodes/fwd_examples/pvfkx.c
    tar uf $filename sundials/cvodes/fwd_examples/pvfkx.out1
    tar uf $filename sundials/cvodes/fwd_examples/pvfkx.out2

    tar uf $filename sundials/cvodes/adj_examples/cvax_par.mk
    tar uf $filename sundials/cvodes/adj_examples/pvanx.c
    tar uf $filename sundials/cvodes/adj_examples/pvanx.out
fi


#----End of tarcvodes script file----