#!/bin/sh
#
# File tarcvode: Script to build CVODE tar-file.
# Version of 21 February 2003
#

#---------------------------------------------------------
# Test if the script is executed from within its directory
#---------------------------------------------------------
scriptbase=`basename $0`
if [ ! -f "$scriptbase" ]
then
    echo "This script must be executed from within its directory"
    exit 1
fi

#-------------
# Define flags
#-------------
err=F   # Error flag
hlp=F   # Help flag
ser=F   # Serial flag
par=F   # Parallel flag
fnm=F   # File name flag

#------------------
# Process arguments
#------------------
if [ $# -eq 0 ]
then
   err=T
else
   while getopts asphf: name
   do
     case $name in
        h) hlp=T;;
        a) ser=T;par=T;;
        s) ser=T;;
        p) par=T;;
        f) fnm=T;filename=$OPTARG;;
        ?) err=T;;
     esac
   done
fi

#------------------
# Define some names
#------------------
scriptdir=`pwd`
distrodir=`echo $PWD | sed -e 's/scripts//'`
distrobase=`basename $distrodir`

#------------
# Print usage
#------------
if [ $err = "T" -o $hlp = "T" ]
then
    echo "Usage: tarcvode [option | file]"
    echo "   -a      : both serial and parallel"
    echo "   -s      : serial"
    echo "   -p      : parallel"
    echo "   -h      : help"
    echo "   -f file : output to file" 
    echo "Note: This script must be executed from within its directory" 
    echo "      Default file will be created in $distrodir"
    if [ $err = "T" -o \( $ser = "F" -a $par = "F" \) ]
    then
        exit 1
    fi
fi

#-----------------
# Create file name
#-----------------
if [ $fnm != "T" ]
then
    if [ $ser = "T" -a $par = "F" ]
    then
        filename="cvode_ser.tar"
    elif [ $ser = "F" -a $par = "T" ]
    then
        filename="cvode_par.tar"
    else
        filename="cvode.tar"
    fi
    tarfile=$distrodir$filename
else
    filebase=`basename $filename`
    cd `dirname $filename`
    filedir=`pwd`
    tarfile=$filedir/$filebase
    cd $scriptdir
fi

#----------------
# Create tar file
#----------------

cd ../..
echo "Generate $distrobase distribution tar-file $tarfile"

# Add top level files
#--------------------

echo "  Add top-level files/directories"

tar cf $tarfile $distrobase/configure
tar uf $tarfile $distrobase/tarch

tar uf $tarfile $distrobase/Makefile.in

tar uf $tarfile $distrobase/doc/Readme

# Add SHARED module
#------------------

echo "  Add shared module"

tar uf $tarfile $distrobase/shared/LICENSE

tar uf $tarfile $distrobase/shared/doc/nvecreadme

tar uf $tarfile $distrobase/shared/include/sundialstypes.h
tar uf $tarfile $distrobase/shared/include/sundialsmath.h
tar uf $tarfile $distrobase/shared/include/nvector.h
tar uf $tarfile $distrobase/shared/include/dense.h
tar uf $tarfile $distrobase/shared/include/smalldense.h
tar uf $tarfile $distrobase/shared/include/band.h
tar uf $tarfile $distrobase/shared/include/spgmr.h
tar uf $tarfile $distrobase/shared/include/iterativ.h
tar uf $tarfile $distrobase/shared/include/fcmixpar.h

tar uf $tarfile $distrobase/shared/source/Makefile.in
tar uf $tarfile $distrobase/shared/source/sundialsmath.c
tar uf $tarfile $distrobase/shared/source/nvector.c
tar uf $tarfile $distrobase/shared/source/dense.c
tar uf $tarfile $distrobase/shared/source/smalldense.c
tar uf $tarfile $distrobase/shared/source/band.c
tar uf $tarfile $distrobase/shared/source/spgmr.c
tar uf $tarfile $distrobase/shared/source/iterativ.c

if [ $ser = "T" ]
then
    tar uf $tarfile $distrobase/nvec_ser/nvector_serial.h
    tar uf $tarfile $distrobase/nvec_ser/fnvector_serial.h

    tar uf $tarfile $distrobase/nvec_ser/Makefile.in
    tar uf $tarfile $distrobase/nvec_ser/nvector_serial.c
    tar uf $tarfile $distrobase/nvec_ser/fnvector_serial.c
fi

if [ $par = "T" ]
then
    tar uf $tarfile $distrobase/nvec_par/nvector_parallel.h
    tar uf $tarfile $distrobase/nvec_par/fnvector_parallel.h

    tar uf $tarfile $distrobase/nvec_par/Makefile.in
    tar uf $tarfile $distrobase/nvec_par/nvector_parallel.c
    tar uf $tarfile $distrobase/nvec_par/fnvector_parallel.c
fi

# Add CVODE module
#-----------------

echo "  Add cvode module"

tar uf $tarfile $distrobase/cvode/LICENSE

tar uf $tarfile $distrobase/cvode/doc/cvreadme
tar uf $tarfile $distrobase/cvode/doc/stald.doc

tar uf $tarfile $distrobase/cvode/include/cvode.h
tar uf $tarfile $distrobase/cvode/include/cvdense.h
tar uf $tarfile $distrobase/cvode/include/cvband.h
tar uf $tarfile $distrobase/cvode/include/cvdiag.h
tar uf $tarfile $distrobase/cvode/include/cvspgmr.h
tar uf $tarfile $distrobase/cvode/include/cvbandpre.h
tar uf $tarfile $distrobase/cvode/include/cvbbdpre.h

tar uf $tarfile $distrobase/cvode/source/Makefile.in
tar uf $tarfile $distrobase/cvode/source/cvode.c
tar uf $tarfile $distrobase/cvode/source/cvdense.c
tar uf $tarfile $distrobase/cvode/source/cvband.c
tar uf $tarfile $distrobase/cvode/source/cvdiag.c
tar uf $tarfile $distrobase/cvode/source/cvspgmr.c
tar uf $tarfile $distrobase/cvode/source/cvbandpre.c
tar uf $tarfile $distrobase/cvode/source/cvbbdpre.c

tar uf $tarfile $distrobase/cvode/fcmix/Makefile.in
tar uf $tarfile $distrobase/cvode/fcmix/fcvode.h
tar uf $tarfile $distrobase/cvode/fcmix/fcvode.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvspgmr01.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvspgmr10.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvspgmr11.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvspgmr20.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvspgmr21.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvpreco.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvpsol.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvjtimes.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvband1.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvdense1.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvbbd.h
tar uf $tarfile $distrobase/cvode/fcmix/fcvbbd.c
tar uf $tarfile $distrobase/cvode/fcmix/fcvbbdin1.c

if [ $ser = "T" ]
then
    tar uf $tarfile $distrobase/cvode/doc/cvudoc.ps
    tar uf $tarfile $distrobase/cvode/doc/cvudoc.pdf
    tar uf $tarfile $distrobase/cvode/doc/cvaddenda

    tar uf $tarfile $distrobase/cvode/examples_ser/Makefile.in
    tar uf $tarfile $distrobase/cvode/examples_ser/cvdx.c
    tar uf $tarfile $distrobase/cvode/examples_ser/cvdx.out
    tar uf $tarfile $distrobase/cvode/examples_ser/cvbx.c
    tar uf $tarfile $distrobase/cvode/examples_ser/cvbx.out
    tar uf $tarfile $distrobase/cvode/examples_ser/cvkx.c
    tar uf $tarfile $distrobase/cvode/examples_ser/cvkx.out
    tar uf $tarfile $distrobase/cvode/examples_ser/cvkxb.c
    tar uf $tarfile $distrobase/cvode/examples_ser/cvkxb.out
    tar uf $tarfile $distrobase/cvode/examples_ser/cvdemd.c
    tar uf $tarfile $distrobase/cvode/examples_ser/cvdemd.out
    tar uf $tarfile $distrobase/cvode/examples_ser/cvdemk.c
    tar uf $tarfile $distrobase/cvode/examples_ser/cvdemk.out

    tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/Makefile.in
    tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/cvdensef.f
    tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/cvdensef.out
    tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/cvbandf.f
    tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/cvbandf.out
    tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/cvkryf.f
    tar uf $tarfile $distrobase/cvode/fcmix/examples_ser/cvkryf.out
fi

if [ $par = "T" ]
then
    tar uf $tarfile $distrobase/cvode/doc/pvudoc.ps
    tar uf $tarfile $distrobase/cvode/doc/pvudoc.pdf
    tar uf $tarfile $distrobase/cvode/doc/pvaddenda

    tar uf $tarfile $distrobase/cvode/examples_par/Makefile.in
    tar uf $tarfile $distrobase/cvode/examples_par/pvnx.c
    tar uf $tarfile $distrobase/cvode/examples_par/pvnx.out
    tar uf $tarfile $distrobase/cvode/examples_par/pvkx.c
    tar uf $tarfile $distrobase/cvode/examples_par/pvkx.out
    tar uf $tarfile $distrobase/cvode/examples_par/pvkxb.c
    tar uf $tarfile $distrobase/cvode/examples_par/pvkxb.out

    tar uf $tarfile $distrobase/cvode/fcmix/examples_par/Makefile.in
    tar uf $tarfile $distrobase/cvode/fcmix/examples_par/pvdiagnf.f
    tar uf $tarfile $distrobase/cvode/fcmix/examples_par/pvdiagnf.out
    tar uf $tarfile $distrobase/cvode/fcmix/examples_par/pvdiagkf.f
    tar uf $tarfile $distrobase/cvode/fcmix/examples_par/pvdiagkf.out
    tar uf $tarfile $distrobase/cvode/fcmix/examples_par/pvdiagkbf.f
    tar uf $tarfile $distrobase/cvode/fcmix/examples_par/pvdiagkbf.out
fi

#----End of tarcvode script file----
