#!/bin/sh
#
# File tarkinsol: Script to build KINSOL tar-file.
# Version of 4 April 2002.
#
#-------------
# Define flags
#-------------
err=F   # Error flag
hlp=F   # Help flag
ser=F   # Serial flag
par=F   # Parallel flag
fnm=F   # File name flag

#------------------
# Process arguments
#------------------
if [ $# -eq 0 ]
then
   err=T
else
   while getopts asphf: name
   do
     case $name in
        h) hlp=T;;
        a) ser=T;par=T;;
        s) ser=T;;
        p) par=T;;
        f) fnm=T;filename=$OPTARG;;
        ?) err=T;;
     esac
   done
fi

#------------
# Print usage
#------------
if [ $err = "T" -o $hlp = "T" ]
then
    echo "Usage: tarkinsol [option | file]"
    echo "   -a      : both serial and parallel"
    echo "   -s      : serial"
    echo "   -p      : parallel"
    echo "   -h      : help"
    echo "   -f file : output to file" 
    if [ $err = "T" -o \( $ser = "F" -a $par = "F" \) ]
    then
        exit 1
    fi
fi

#-----------------
# Create file name
#-----------------
if [ $fnm != "T" ]
then
    if [ $ser = "T" -a $par = "F" ]
    then
        filename="kinsol_ser.tar"
    elif [ $ser = "F" -a $par = "T" ]
    then
        filename="kinsol_par.tar"
    else
        filename="kinsol.tar"
    fi
fi

#----------------
# Create tar file
#----------------

cd ../..
if [ $fnm != "T" ]
then
    echo "Generate tar file $PWD/$filename"
else
    echo "Generate tar file $filename"
fi

# Add top level files
#--------------------

echo "  Add top-level files/directories"

tar cf $filename sundials/Makefile

tar uf $filename sundials/lib/.dontremove

tar uf $filename sundials/include/.dontremove

tar uf $filename sundials/doc/Readme
tar uf $filename sundials/doc/dirstruc

# Add SHARED module
#------------------

echo "  Add shared module"

tar uf $filename sundials/shared/doc/nvecreadme

tar uf $filename sundials/shared/lib/.dontremove

tar uf $filename sundials/shared/include/sundialstypes.h
tar uf $filename sundials/shared/include/sundialsmath.h
tar uf $filename sundials/shared/include/nvector.h
tar uf $filename sundials/shared/include/dense.h
tar uf $filename sundials/shared/include/smalldense.h
tar uf $filename sundials/shared/include/band.h
tar uf $filename sundials/shared/include/spgmr.h
tar uf $filename sundials/shared/include/iterativ.h
tar uf $filename sundials/shared/include/fcmixpar.h

tar uf $filename sundials/shared/source/Makefile
tar uf $filename sundials/shared/source/sundialsmath.c
tar uf $filename sundials/shared/source/nvector.c
tar uf $filename sundials/shared/source/dense.c
tar uf $filename sundials/shared/source/smalldense.c
tar uf $filename sundials/shared/source/band.c
tar uf $filename sundials/shared/source/spgmr.c
tar uf $filename sundials/shared/source/iterativ.c

if [ $ser = "T" ]
then
    tar uf $filename sundials/shared/include/nvector_serial.h
    tar uf $filename sundials/shared/include/fnvector_serial.h

    tar uf $filename sundials/shared/source/nvecserial.mk
    tar uf $filename sundials/shared/source/nvector_serial.c
    tar uf $filename sundials/shared/source/fnvector_serial.c
fi

if [ $par = "T" ]
then
    tar uf $filename sundials/shared/include/nvector_parallel.h
    tar uf $filename sundials/shared/include/fnvector_parallel.h

    tar uf $filename sundials/shared/source/nvecparallel.mk
    tar uf $filename sundials/shared/source/nvector_parallel.c
    tar uf $filename sundials/shared/source/fnvector_parallel.c
fi

# Add KINSOL module
#------------------

echo "  Add kinsol module"

tar uf $filename sundials/kinsol/doc/kinreadme
tar uf $filename sundials/kinsol/doc/kinaddenda

tar uf $filename sundials/kinsol/include/kinsol.h
tar uf $filename sundials/kinsol/include/kinspgmr.h
tar uf $filename sundials/kinsol/include/kinbbdpre.h

tar uf $filename sundials/kinsol/source/Makefile
tar uf $filename sundials/kinsol/source/kinsol.c
tar uf $filename sundials/kinsol/source/kinspgmr.c
tar uf $filename sundials/kinsol/source/kinbbdpre.c

tar uf $filename sundials/kinsol/lib/.dontremove

tar uf $filename sundials/kinsol/examples/Makefile

tar uf $filename sundials/kinsol/fcmix/Makefile
tar uf $filename sundials/kinsol/fcmix/fkinsol.h
tar uf $filename sundials/kinsol/fcmix/fkinsol.c
tar uf $filename sundials/kinsol/fcmix/fkinspgmr01.c
tar uf $filename sundials/kinsol/fcmix/fkinspgmr10.c
tar uf $filename sundials/kinsol/fcmix/fkinspgmr11.c
tar uf $filename sundials/kinsol/fcmix/fkinspgmr20.c
tar uf $filename sundials/kinsol/fcmix/fkinspgmr21.c
tar uf $filename sundials/kinsol/fcmix/fkinpreco.c
tar uf $filename sundials/kinsol/fcmix/fkinpsol.c
tar uf $filename sundials/kinsol/fcmix/fkinuatimes.c
tar uf $filename sundials/kinsol/fcmix/fkinbbd.h
tar uf $filename sundials/kinsol/fcmix/fkinbbd.c
tar uf $filename sundials/kinsol/fcmix/fkinbbdinit1.c

if [ $ser = "T" ]
then
    tar uf $filename sundials/kinsol/examples/kinx_ser.mk
    tar uf $filename sundials/kinsol/examples/kinwebs.c
    tar uf $filename sundials/kinsol/examples/kinwebs.out

    tar uf $filename sundials/kinsol/fcmix/fkinx_ser.mk
    tar uf $filename sundials/kinsol/fcmix/kindiagsf.f
    tar uf $filename sundials/kinsol/fcmix/kindiagsf.out
fi
    
if [ $par = "T" ]
then
    tar uf $filename sundials/kinsol/examples/kinx_par.mk
    tar uf $filename sundials/kinsol/examples/kinwebp.c
    tar uf $filename sundials/kinsol/examples/kinwebp.out
    tar uf $filename sundials/kinsol/examples/kinwebbbd.c
    tar uf $filename sundials/kinsol/examples/kinwebbbd.out
    
    tar uf $filename sundials/kinsol/fcmix/fkinx_par.mk
    tar uf $filename sundials/kinsol/fcmix/kindiagpf.f
    tar uf $filename sundials/kinsol/fcmix/kindiagpf.out
fi

#----End of tarkinsol script file----
