#!/bin/sh
#
# File tarscript: Script to build SUNDIALS tar-files.
# Author: Radu Serban @ LLNL
# Version of 29 November 2005
#

#==============================================================================
#
# Prints usage if help was requested or if the script was incorectly called
#
#==============================================================================

function print_usage
{
    echo ""
    echo "Usage: tarscript [-h] [module]"
    echo "   -h       : help"
    echo "   module   : all, sundials, cvode, cvodes, ida, kinsol"
    echo ""
    echo "Note1: If the module is not specified, tar files are created"
    echo "       for all of them."
    echo "Note2: This script must be executed from within its directory" 
    echo "       Default file will be created in $distrodir."
    echo ""
    exit 1
}

#==============================================================================
#
# Generates one tar file for the given $module, accordingly to the $par flag
#
#==============================================================================

function create_file
{
    what=$1

    cd ..

    aclocal
    autoconf -f -o configure configure-rel.ac
    autoheader
    tail=".tar"

    tarfile=$distrodir$what$tail

    cd ..

    echo "Generate $distrobase distribution tar-file $tarfile"

    $distrobase/scripts/shared $tarfile $distrobase
    
    if [ $what = "cvode" -o $what = "sundials" ];  then
        $distrobase/scripts/cvode $tarfile $distrobase
    fi
    
    if [ $what = "cvodes" -o $what = "sundials" ]; then
        $distrobase/scripts/cvodes $tarfile $distrobase
    fi

    if [ $what = "ida" -o $what = "sundials" ];    then
        $distrobase/scripts/ida $tarfile $distrobase
    fi

    if [ $what = "kinsol" -o $what = "sundials" ]; then
        $distrobase/scripts/kinsol $tarfile $distrobase
    fi

    gzip $tarfile
    
    cd $scriptdir
}

#==============================================================================
#
# This function decides how many files need to be created for the current
# module
#
#==============================================================================

function create_module
{
    module=$1

    create_file $module
}

#==============================================================================
#
# MAIN SCRIPT
#
#==============================================================================

#---------------------------------------------------------
# Test if the script is executed from within its directory
#---------------------------------------------------------
scriptbase=`basename $0`
if [ ! -f "$scriptbase" ] ; then
    print_usage
fi

#-------------
# Define flags
#-------------
err=F   # Error flag
hlp=F   # Help flag

#----------------
# Process options
#----------------
while getopts ":h" name ; do
    case $name in
        h) hlp=T;;
        ?) err=T;;
    esac
done

#------------------------------
# Extract argument (module name)
#------------------------------
shift $(($OPTIND - 1))
module=$1

#------------
# Test module 
#------------
if [ -z $module ]; then
    module="all"
else
    if [ $module != "all" -a $module != "sundials" -a $module != "cvode" -a $module != "cvodes" -a $module != "ida" -a $module != "kinsol" ]; then
        err=T
    fi
fi

#------------------
# Define some names
#------------------
scriptdir=`pwd`
distrodir=`echo $PWD | sed -e 's/scripts//'`
distrobase=`basename $distrodir`

#------------
# Print usage
#------------
if [ $err = "T" -o $hlp = "T" ]; then
    print_usage
fi

#---------------------------
# Create requested tar files
#---------------------------
if [ $module != "all" ]; then
    create_module $module
else
    create_module "sundials"
    create_module "cvode"
    create_module "cvodes"
    create_module "ida"
    create_module "kinsol"
fi

# That's all folks...
