#!/bin/sh
#
# File tarscript: Script to build SUNDIALS tar-files.
# Author: Radu Serban @ LLNL
# Version of 29 June 2005
#

#---------------------------------------------------------
# VERSION NUMBERS
#---------------------------------------------------------

SUN_VER="2.3.0"
CV_VER="2.5.0"
CVS_VER="2.5.0"
IDA_VER="2.5.0"
KIN_VER="2.5.0"
CPS_VER="0.0.1"

#------------------
# Path to scripts
#------------------

scriptdir=`pwd`

#----------------------------------
# Copy files in temporary directory
#----------------------------------

cd ../..
tmpdir=`pwd`
echo -e "\n--- Create temporary directory ---"
echo "copy sundials to "$tmpdir"/tmp_dir"
rm -rf tmp_dir
cp -r sundials tmp_dir

#----------------------------------
# Create necessary files
#----------------------------------

cd tmp_dir

echo -e "\n--- Generate configure script ---"
aclocal
autoconf -f -o configure configure.ac
autoheader

echo -e "\n--- Generate documentation ---"

echo -e "   --- CVODE documentation"
cd doc/cvode
make QUIET=-q purge
make QUIET=-q ug_pdf
make QUIET=-q ex_pdf
cd -

echo -e "   --- CVODES documentation"
cd doc/cvodes
make QUIET=-q purge
make QUIET=-q ug_pdf
make QUIET=-q ex_pdf
cd -

echo -e "   --- IDA documentation"
cd doc/ida
make QUIET=-q purge
make QUIET=-q ug_pdf
make QUIET=-q ex_pdf
cd -

echo -e "   --- KINSOL documentation"
cd doc/kinsol
make QUIET=-q purge
make QUIET=-q ug_pdf
make QUIET=-q ex_pdf
cd -

cd ..

#---------------------------
# Create tar files
#---------------------------

distrobase="tmp_dir"

# SUNDIALS

echo -e "\n--- Generate SUNDIALS tarball ---"

mv $distrobase sundials-$SUN_VER
distrobase="sundials-"$SUN_VER
filename="sundials-"$SUN_VER

tarfile=$filename".tar"
$scriptdir/shared $tarfile $distrobase
$scriptdir/cvode $tarfile $distrobase
$scriptdir/cvodes $tarfile $distrobase
$scriptdir/ida $tarfile $distrobase
$scriptdir/kinsol $tarfile $distrobase
$scriptdir/stb $tarfile $distrobase
gzip $tarfile
mv $filename".tar.gz" $filename".tar.gz"

# CVODE

echo -e "\n--- Generate CVODE tarball ---"

mv $distrobase cvode-$CV_VER
distrobase="cvode-"$CV_VER
filename="cvode-"$CV_VER

tarfile=$filename".tar"
$scriptdir/shared $tarfile $distrobase
$scriptdir/cvode $tarfile $distrobase
gzip $tarfile
mv $filename".tar.gz" $filename".tar.gz"

# CVODES

echo -e "\n--- Generate CVODES tarball ---"

mv $distrobase cvodes-$CVS_VER
distrobase="cvodes-"$CVS_VER
filename="cvodes-"$CVS_VER

tarfile=$filename".tar"
$scriptdir/shared $tarfile $distrobase
$scriptdir/cvodes $tarfile $distrobase
gzip $tarfile
mv $filename".tar.gz" $filename".tar.gz"

# IDA

echo -e "\n--- Generate IDA tarball ---"

mv $distrobase ida-$IDA_VER
distrobase="ida-"$IDA_VER
filename="ida-"$IDA_VER

tarfile=$filename".tar"
$scriptdir/shared $tarfile $distrobase
$scriptdir/ida $tarfile $distrobase
gzip $tarfile
mv $filename".tar.gz" $filename".tar.gz"

# KINSOL

echo -e "\n--- Generate KINSOL tarball ---"

mv $distrobase kinsol-$KIN_VER
distrobase="kinsol-"$KIN_VER
filename="kinsol-"$KIN_VER

tarfile=$filename".tar"
$scriptdir/shared $tarfile $distrobase
$scriptdir/kinsol $tarfile $distrobase
gzip $tarfile
mv $filename".tar.gz" $filename".tar.gz"

# CPODES

echo -e "\n--- Generate CPODES tarball ---"

mv $distrobase cpodes-$CPS_VER
distrobase="cpodes-"$CPS_VER
filename="cpodes-"$CPS_VER

tarfile=$filename".tar"
$scriptdir/shared $tarfile $distrobase
$scriptdir/cpodes $tarfile $distrobase
gzip $tarfile
mv $filename".tar.gz" $filename".tar.gz"

#---------------------------
# Remove temporary directory
#---------------------------

rm -rf $distrobase

du -h *.tar.gz

exit 1

# That's all folks...
