spack:
  packages:
    all:
      providers:
        target: [x86_64]
        blas:
        - openblas
        mpi:
        - openmpi
      compiler:
      - gcc@9.4.0
  specs:
  - cmake arch=x86_64 %gcc@9.4.0
  - hypre~int64~internal-superlu arch=x86_64 %gcc@9.4.0
  - petsc+double~int64~superlu-dist arch=x86_64 %gcc@9.4.0
  - openmpi arch=x86_64 %gcc@9.4.0
  - openblas~ilp64 arch=x86_64 %gcc@9.4.0
  - suite-sparse arch=x86_64 %gcc@9.4.0
  - superlu-mt~int64~blas arch=x86_64 %gcc@9.4.0
  - superlu-dist~int64 ^parmetis~int64 arch=x86_64 %gcc@9.4.0
  - trilinos+tpetra gotype=int arch=x86_64 %gcc@9.4.0
  - xbraid arch=x86_64 %gcc@9.4.0
  config:
    install_tree: /opt/software
  mirrors:
    local: /var/cache/spack-mirror
    E4S: https://cache.e4s.io
  repos: []
  upstreams: {}
  concretization: together
  view:
    default:
      root: /opt/view
      projections:
        superlu-mt: '{name}'
        superlu-dist: '{name}'
