#!/bin/sh
#
# File tarscript: Script to build sundialsTB tar-files.
# Author: Radu Serban @ LLNL
# Version of 09 May 2005
#


distrodir=`echo $PWD | sed -e 's/scripts//'`
distrobase=`basename $distrodir`

tarfile=${distrodir}sundialsTB.tar

cd ../..

pwd
echo $tarfile
echo $distrobase


# README file, documentation

tar cf $tarfile $distrobase/README
tar cf $tarfile $distrobase/LICENSE
tar uf $tarfile $distrobase/doc/sundialsTB.pdf
tar uf $tarfile $distrobase/doc/sundialsTB.ps

# startup_STB and install_STB

tar uf $tarfile $distrobase/install_STB.m
tar uf $tarfile $distrobase/startup_STB.m

# MEX source files

tar uf $tarfile $distrobase/src/sundials_config.h

tar uf $tarfile $distrobase/src/cvm/cvm.h
tar uf $tarfile $distrobase/src/cvm/cvm.c
tar uf $tarfile $distrobase/src/cvm/cvmOpts.c
tar uf $tarfile $distrobase/src/cvm/cvmWrap.c

tar uf $tarfile $distrobase/src/kim/kim.h
tar uf $tarfile $distrobase/src/kim/kim.c
tar uf $tarfile $distrobase/src/kim/kimOpts.c
tar uf $tarfile $distrobase/src/kim/kimWrap.c

tar uf $tarfile $distrobase/src/nvm/nvm.h
tar uf $tarfile $distrobase/src/nvm/nvm_ops.c
tar uf $tarfile $distrobase/src/nvm/nvm_parallel.c
tar uf $tarfile $distrobase/src/nvm/nvm_serial.c


# CVODES files

tar uf $tarfile $distrobase/cvodes/Contents.m
tar uf $tarfile $distrobase/cvodes/CVadjMalloc.m
tar uf $tarfile $distrobase/cvodes/CVBandJacFn.m
tar uf $tarfile $distrobase/cvodes/CVDenseJacFn.m
tar uf $tarfile $distrobase/cvodes/CVGcommFn.m
tar uf $tarfile $distrobase/cvodes/CVGlocalFn.m
tar uf $tarfile $distrobase/cvodes/CVJacTimesVecFn.m
tar uf $tarfile $distrobase/cvodes/CVMonitorFn.m
tar uf $tarfile $distrobase/cvodes/CVodeB.m
tar uf $tarfile $distrobase/cvodes/CVodeFree.m
tar uf $tarfile $distrobase/cvodes/CVodeGet.m
tar uf $tarfile $distrobase/cvodes/CVodeGetStatsB.m
tar uf $tarfile $distrobase/cvodes/CVodeGetStats.m
tar uf $tarfile $distrobase/cvodes/CVode.m
tar uf $tarfile $distrobase/cvodes/CVodeMallocB.m
tar uf $tarfile $distrobase/cvodes/CVodeMalloc.m
tar uf $tarfile $distrobase/cvodes/CVodeMonitor.m
tar uf $tarfile $distrobase/cvodes/CVodeSensMalloc.m
tar uf $tarfile $distrobase/cvodes/CVodeSetFSAOptions.m
tar uf $tarfile $distrobase/cvodes/CVodeSetOptions.m
tar uf $tarfile $distrobase/cvodes/CVPrecSetupFn.m
tar uf $tarfile $distrobase/cvodes/CVPrecSolveFn.m
tar uf $tarfile $distrobase/cvodes/CVQuadRhsFn.m
tar uf $tarfile $distrobase/cvodes/CVRhsFn.m
tar uf $tarfile $distrobase/cvodes/CVRootFn.m
tar uf $tarfile $distrobase/cvodes/CVSensRhsFn.m

tar uf $tarfile $distrobase/cvodes/cvm/Contents.m
tar uf $tarfile $distrobase/cvodes/cvm/cvm_bjac.m
tar uf $tarfile $distrobase/cvodes/cvm/cvm_djac.m
tar uf $tarfile $distrobase/cvodes/cvm/cvm_gcom.m
tar uf $tarfile $distrobase/cvodes/cvm/cvm_gloc.m
tar uf $tarfile $distrobase/cvodes/cvm/cvm_jtv.m
tar uf $tarfile $distrobase/cvodes/cvm/cvm_monitor.m
tar uf $tarfile $distrobase/cvodes/cvm/cvm_pset.m
tar uf $tarfile $distrobase/cvodes/cvm/cvm_psol.m
tar uf $tarfile $distrobase/cvodes/cvm/cvm_rhs.m
tar uf $tarfile $distrobase/cvodes/cvm/cvm_rhsQ.m
tar uf $tarfile $distrobase/cvodes/cvm/cvm_rhsS.m
tar uf $tarfile $distrobase/cvodes/cvm/cvm_root.m

tar uf $tarfile $distrobase/cvodes/examples_ser/cvadx.m
tar uf $tarfile $distrobase/cvodes/examples_ser/cvbx_f.m
tar uf $tarfile $distrobase/cvodes/examples_ser/cvbx_J.m
tar uf $tarfile $distrobase/cvodes/examples_ser/cvbx.m
tar uf $tarfile $distrobase/cvodes/examples_ser/cvbx_q.m
tar uf $tarfile $distrobase/cvodes/examples_ser/cvdx_fB.m
tar uf $tarfile $distrobase/cvodes/examples_ser/cvdx_f.m
tar uf $tarfile $distrobase/cvodes/examples_ser/cvdx_fS.m
tar uf $tarfile $distrobase/cvodes/examples_ser/cvdx_g.m
tar uf $tarfile $distrobase/cvodes/examples_ser/cvdx_JB.m
tar uf $tarfile $distrobase/cvodes/examples_ser/cvdx_J.m
tar uf $tarfile $distrobase/cvodes/examples_ser/cvdx.m
tar uf $tarfile $distrobase/cvodes/examples_ser/cvdx_qB.m
tar uf $tarfile $distrobase/cvodes/examples_ser/cvdx_q.m
tar uf $tarfile $distrobase/cvodes/examples_ser/cvfdx.m
tar uf $tarfile $distrobase/cvodes/examples_ser/cvkxb.m
tar uf $tarfile $distrobase/cvodes/examples_ser/cvkx_f.m
tar uf $tarfile $distrobase/cvodes/examples_ser/cvkx.m
tar uf $tarfile $distrobase/cvodes/examples_ser/cvkx_pset.m
tar uf $tarfile $distrobase/cvodes/examples_ser/cvkx_psol.m
tar uf $tarfile $distrobase/cvodes/examples_ser/pleiades_f.m
tar uf $tarfile $distrobase/cvodes/examples_ser/pleiades_J.m
tar uf $tarfile $distrobase/cvodes/examples_ser/pleiades.m
tar uf $tarfile $distrobase/cvodes/examples_ser/vdp_f.m
tar uf $tarfile $distrobase/cvodes/examples_ser/vdp_J.m
tar uf $tarfile $distrobase/cvodes/examples_ser/vdp.m

tar uf $tarfile $distrobase/cvodes/examples_par/pvfnx_f.m
tar uf $tarfile $distrobase/cvodes/examples_par/pvfnx.m
tar uf $tarfile $distrobase/cvodes/examples_par/pvkx_fl.m
tar uf $tarfile $distrobase/cvodes/examples_par/pvkx_f.m
tar uf $tarfile $distrobase/cvodes/examples_par/pvkx.m
tar uf $tarfile $distrobase/cvodes/examples_par/pvnx_f.m
tar uf $tarfile $distrobase/cvodes/examples_par/pvnx.m

# KINSOL files

tar uf $tarfile $distrobase/kinsol/Contents.m
tar uf $tarfile $distrobase/kinsol/KINBandJacFn.m
tar uf $tarfile $distrobase/kinsol/KINDenseJacFn.m
tar uf $tarfile $distrobase/kinsol/KINFree.m
tar uf $tarfile $distrobase/kinsol/KINGcommFn.m
tar uf $tarfile $distrobase/kinsol/KINGetStats.m
tar uf $tarfile $distrobase/kinsol/KINGlocalFn.m
tar uf $tarfile $distrobase/kinsol/KINJacTimesVecFn.m
tar uf $tarfile $distrobase/kinsol/KINMalloc.m
tar uf $tarfile $distrobase/kinsol/KINPrecSetupFn.m
tar uf $tarfile $distrobase/kinsol/KINPrecSolveFn.m
tar uf $tarfile $distrobase/kinsol/KINSetOptions.m
tar uf $tarfile $distrobase/kinsol/KINSol.m
tar uf $tarfile $distrobase/kinsol/KINSysFn.m

tar uf $tarfile $distrobase/kinsol/kim/Contents.m
tar uf $tarfile $distrobase/kinsol/kim/kim_djac.m
tar uf $tarfile $distrobase/kinsol/kim/kim_bjac.m
tar uf $tarfile $distrobase/kinsol/kim/kim_gcom.m
tar uf $tarfile $distrobase/kinsol/kim/kim_gloc.m
tar uf $tarfile $distrobase/kinsol/kim/kim_info.m
tar uf $tarfile $distrobase/kinsol/kim/kim_jtv.m
tar uf $tarfile $distrobase/kinsol/kim/kim_pset.m
tar uf $tarfile $distrobase/kinsol/kim/kim_psol.m
tar uf $tarfile $distrobase/kinsol/kim/kim_sys.m

tar uf $tarfile $distrobase/kinsol/examples_ser/kindiag.m
tar uf $tarfile $distrobase/kinsol/examples_ser/kindiag_pset.m
tar uf $tarfile $distrobase/kinsol/examples_ser/kindiag_psol.m
tar uf $tarfile $distrobase/kinsol/examples_ser/kindiag_sys.m
tar uf $tarfile $distrobase/kinsol/examples_ser/kindx.m
tar uf $tarfile $distrobase/kinsol/examples_ser/kindx_sys.m

tar uf $tarfile $distrobase/kinsol/examples_par/kindiagp.m
tar uf $tarfile $distrobase/kinsol/examples_par/kindiagp_pset.m
tar uf $tarfile $distrobase/kinsol/examples_par/kindiagp_psol.m
tar uf $tarfile $distrobase/kinsol/examples_par/kindiagp_sys.m

# NVECTOR files

tar uf $tarfile $distrobase/nvector/Contents.m
tar uf $tarfile $distrobase/nvector/N_VDotProd.m
tar uf $tarfile $distrobase/nvector/N_VL1Norm.m
tar uf $tarfile $distrobase/nvector/N_VMax.m
tar uf $tarfile $distrobase/nvector/N_VMaxNorm.m
tar uf $tarfile $distrobase/nvector/N_VMin.m
tar uf $tarfile $distrobase/nvector/N_VWL2Norm.m
tar uf $tarfile $distrobase/nvector/N_VWrmsNorm.m

# PUTILS files

tar uf $tarfile $distrobase/putils/Contents.m
tar uf $tarfile $distrobase/putils/mpistart.m
tar uf $tarfile $distrobase/putils/mpirun.m
tar uf $tarfile $distrobase/putils/mpiruns.m


# That's all folks...
