# -----------------------------------------------------------------
# $Revision:  $
# $Date:  $
# -----------------------------------------------------------------
# Programmer(s): Slaven Peles @ LLNL
# -----------------------------------------------------------------
# LLNS Copyright Start
# Copyright (c) 2014, Lawrence Livermore National Security
# This work was performed under the auspices of the U.S. Department 
# of Energy by Lawrence Livermore National Laboratory in part under 
# Contract W-7405-Eng-48 and in part under Contract DE-AC52-07NA27344.
# Produced at the Lawrence Livermore National Laboratory.
# All rights reserved.
# For details, see the LICENSE file.
# LLNS Copyright End
# -----------------------------------------------------------------
# Sources for IDA documents
# -----------------------------------------------------------------


USER_GUIDE = ida_guide
EXAMPLES   = ida_examples

UG_FILES = \
${USER_GUIDE}.tex \
ida_intro.tex \
ida_install.tex \
ida_math.tex \
ida_usage.tex \
ida_fcmix.tex \
ida_nvec.tex \
ida_org.tex \
ida_newlinsolv.tex \
ida_constants.tex
#ida_linsolv.tex \

EX_FILES = \
${EXAMPLES}.tex     \
ida_ex_intro.tex    \
ida_ex_serial.tex   \
ida_ex_parallel.tex \
ida_ex_petsc.tex    \
ida_ex_fortran.tex  \
ida_ex_codes.tex

include ../Makefile.in

