# -----------------------------------------------------------------
# Programmer(s): Slaven Peles, Cody Balos @ LLNL
# -----------------------------------------------------------------
# SUNDIALS Copyright Start
# Copyright (c) 2002-2020, Lawrence Livermore National Security
# and Southern Methodist University.
# All rights reserved.
#
# See the top-level LICENSE and NOTICE files for details.
#
# SPDX-License-Identifier: BSD-3-Clause
# SUNDIALS Copyright End
# -----------------------------------------------------------------
# Makefile for IDA documentation
# -----------------------------------------------------------------

USER_GUIDE = ida_guide
EXAMPLES   = ida_examples

# names of guide files
UG_FILES = \
${USER_GUIDE}.tex \
ida_intro.tex \
ida_install.tex \
ida_math.tex \
ida_usage.tex \
ida_fcmix.tex \
ida_nvec.tex \
ida_org.tex \
ida_newlinsolv.tex \
ida_sunlinsol.tex \
ida_sunmat.tex \
ida_sunnonlinsol.tex \
ida_constants.tex

EX_FILES = \
${EXAMPLES}.tex     \
ida_ex_intro.tex    \
ida_ex_serial.tex   \
ida_ex_parallel.tex \
ida_ex_petsc.tex    \
ida_ex_trilinos.tex    \
ida_ex_fortran.tex  \
ida_ex_codes.tex

include ../Makefile.in
