name: Containers - spack@latest

on:
  #push: # testing
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build_ci_containers:
    runs-on: ubuntu-latest
    steps:
      - name: VM Hardware Info
        run: |
          cat /proc/cpuinfo
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          context: "./docker/sundials-ci/spack-latest"
          build-args: spack_yaml=./spack.yaml
          push: true
          tags: ghcr.io/llnl/sundials-ci-spack-latest:spack-latest
