name: Containers - spack@e4s

on:
  push: # testing
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build_e4s_base:
    runs-on: ubuntu-latest
    steps:
      - name: VM Hardware Info
        run: |
          cat /proc/cpuinfo
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          context: "./docker/sundials-ci/e4s-base"
          build-args: e4s_version=22.05
          push: true
          tags: ghcr.io/llnl/sundials-ci-spack-e4s-base:latest, ghcr.io/llnl/sundials-ci-spack-e4s-base:e4s-22.05
  build_ci_containers:
    runs-on: ubuntu-latest
    needs: build_e4s_base
    steps:
      - name: VM Hardware Info
        run: |
          cat /proc/cpuinfo
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          context: "./docker/sundials-ci/e4s-quarterly"
          build-args: spack_yaml=./spack.yaml
          push: true
          tags: ghcr.io/llnl/sundials-ci-spack-e4s:latest, ghcr.io/llnl/sundials-ci-spack-e4s:e4s-22.05
