#
name: Full Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: centos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run test_driver.sh
      run: ${{github.workspace}}/test/test_driver.sh --branchname ${GITHUB_REF_NAME} --changebranch ${GITHUB_HEAD_REF}