name: Docs - PDFs

on:
  push:
    branches:
      - main
      - develop
      - ci/pdf-docs
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  docs_user_guide_pdf:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      matrix:
        package: [arkode, cvode, cvodes, ida, idas, kinsol]

    steps:
      - name: Install latex
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            fonts-texgyre \
            latexmk \
            tex-gyre \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-plain-generic

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install sphinx
        run: |
          pip install -r doc/requirements.txt

      - name: Build docs
        run: cd doc/${{matrix.package}}/guide && make latexpdf

      - name: Archive files from failed build
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: latex_build_files
          path: |
            ${{ github.workspace }}/doc/${{matrix.package}}/guide/build/latex
