#
name: extended precision build and test with GCC+TPLs (no GPUs)

on:
  push:
  pull_request:

jobs:
  run_int32_extended:
    runs-on: ubuntu-latest
    container:
      image: balos1/sundials-ci-int32-extended:latest
      options: --user root --privileged --ulimit core=-1 --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Spack find
        run: |
          eval `/opt/spack/bin/spack env activate --sh /opt/spack-environment`
          /opt/spack/bin/spack find -v
      - name: Run test_driver.sh
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          cd test
          ./test_driver.sh --testtype CUSTOM --env env/docker.sh --tpls --realtype extended --indexsize 32
      - name: Archive files from failed build
        uses: actions/upload-artifact@v2.2.4
        if: failure()
        with:
          name: build_files
          path: |
            ${{ github.workspace }}/test/build_*
  run_int64_extended:
    runs-on: ubuntu-latest
    container:
      image: balos1/sundials-ci-int64-extended:latest
      options: --user root --privileged --ulimit core=-1 --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Spack find
        run: |
          eval `/opt/spack/bin/spack env activate --sh /opt/spack-environment`
          /opt/spack/bin/spack find -v
      - name: Run test_driver.sh
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          cd test
          ./test_driver.sh --testtype CUSTOM --env env/docker.sh --tpls --realtype extended --indexsize 64
      - name: Archive files from failed build
        uses: actions/upload-artifact@v2.2.4
        if: failure()
        with:
          name: build_files
          path: |
            ${{ github.workspace }}/test/build_*
