#
name: Extended Build and Test with GCC+TPLs (no GPUs)

on: [push, pull_request] # temporarily on push too for testing
jobs:
  run_int32_extended:
    runs-on: ubuntu-latest
    container:
      image: balos1/sundials-ci:int32-extended-latest
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run test_driver.sh
        run: |
          git config --global --add safe.directory /__w/sundials/sundials
          cd test
          ./test_driver.sh --testtype CUSTOM --env env/docker.sh --realtype extended --indexsize 32
      - name: Archive CMake logs from failed build
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cmake-logs
          path: |
            ${{ github.workspace }}/test/build_*
  run_int64_extended:
    runs-on: ubuntu-latest
    container:
      image: balos1/sundials-ci:int64-extended-latest
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run test_driver.sh
        run: |
          git config --global --add safe.directory /__w/sundials/sundials
          cd test
          ./test_driver.sh --testtype CUSTOM --env env/docker.sh --realtype extended --indexsize 64
      - name: Archive CMake logs from failed build
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cmake-logs
          path: |
            ${{ github.workspace }}/test/build_*
