#
name: Build and Test - Ubuntu/gcc extended precision (TPLs, no GPUs)

on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/llnl/sundials-ci-int${{ matrix.indexsize }}-${{ matrix.precision }}:latest
      options: --user root
    strategy:
      matrix:
        indexsize: [32, 64]
        precision: ['extended']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Run test_driver.sh
        uses: ./.github/actions/test-driver
        with:
          indexsize: ${{ matrix.indexsize }}
          precision: ${{ matrix.precision }}
      - name: Archive build files from failed build
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: build_files
          path: |
            ${{ github.workspace }}/test/build_*
            !${{ github.workspace }}/test/build_*/Testing/output
      - name: Archive output files from failed build
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: output_files
          path: |
            ${{ github.workspace }}/test/build_*/Testing/
            