#
name: Full Test

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/ci-docker

    - name: Run test_driver.sh
      working-directory: ${{github.workspace}}/test
      run: docker exec ./test_driver.sh --branchname ${GITHUB_REF_NAME}