name: Build - Ubuntu/dpcpp

on:
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  LINUX_DPCPP_COMPONENTS_WEB: intel.oneapi.lin.dpcpp-cpp-compiler
  CACHE_NUMBER: 5

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        LINUX_BASEKIT_URL: [
          'https://registrationcenter-download.intel.com/akdlm/IRC_NAS/e6ff8e9c-ee28-47fb-abd7-5c524c983e1c/l_BaseKit_p_2024.2.1.100_offline.sh',
          'https://registrationcenter-download.intel.com/akdlm/IRC_NAS/96aa5993-5b22-4a9b-91ab-da679f422594/intel-oneapi-base-toolkit-2025.0.0.885_offline.sh'
        ]

    steps:
    - uses: actions/checkout@v4

    - name: cache install oneAPI
      id: cache-install
      uses: actions/cache@v3
      with:
        path: |
          /opt/intel/oneapi/compiler
          /opt/intel/oneapi/tbb
        key: install-${{ env.CACHE_NUMBER }}-${{ matrix.LINUX_BASEKIT_URL }}-${{ env.LINUX_DPCPP_COMPONENTS_WEB }}-compiler-tbb-${{ hashFiles('**/.github/actions/install-oneapi/cache_exclude_linux.sh') }}

    - name: install oneAPI
      if: steps.cache-install.outputs.cache-hit != 'true'
      run: ./.github/actions/install-oneapi/install_linux.sh ${{ matrix.LINUX_BASEKIT_URL }} ${{ env.LINUX_DPCPP_COMPONENTS_WEB }}

    - name: exclude unused files from oneAPI cache
      if: steps.cache-install.outputs.cache-hit != 'true'
      run: ./.github/actions/install-oneapi/cache_exclude_linux.sh

    - name: Configure CMake
      run: |
        cmake \
        -B ${{github.workspace}}/build \
        -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
        -D CMAKE_C_COMPILER=$(which icx) \
        -D CMAKE_CXX_COMPILER=$(which icpx) \
        -D SUNDIALS_BUILD_WITH_PROFILING=ON \
        -D ENABLE_ALL_WARNINGS=ON \
        -D ENABLE_WARNINGS_AS_ERRORS=ON \
        -D ENABLE_SYCL=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
