/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* qualifier for exported *const* global data variables*/
#ifndef SWIGEXTERN
# ifdef __cplusplus
#   define SWIGEXTERN extern
# else
#   define SWIGEXTERN
# endif
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

/*  Errors in SWIG */
#define  SWIG_UnknownError    	   -1
#define  SWIG_IOError        	   -2
#define  SWIG_RuntimeError   	   -3
#define  SWIG_IndexError     	   -4
#define  SWIG_TypeError      	   -5
#define  SWIG_DivisionByZero 	   -6
#define  SWIG_OverflowError  	   -7
#define  SWIG_SyntaxError    	   -8
#define  SWIG_ValueError     	   -9
#define  SWIG_SystemError    	   -10
#define  SWIG_AttributeError 	   -11
#define  SWIG_MemoryError    	   -12
#define  SWIG_NullReferenceError   -13




#include <assert.h>
#define SWIG_exception_impl(DECL, CODE, MSG, RETURNNULL) \
 { printf("In " DECL ": " MSG); assert(0); RETURNNULL; }


enum {
    SWIG_MEM_OWN = 0x01,
    SWIG_MEM_RVALUE = 0x02,
    SWIG_MEM_CONST = 0x04
};


#define SWIG_check_mutable(SWIG_CLASS_WRAPPER, TYPENAME, FNAME, FUNCNAME, RETURNNULL) \
    if ((SWIG_CLASS_WRAPPER).cmemflags & SWIG_MEM_CONST) { \
        SWIG_exception_impl(FUNCNAME, SWIG_TypeError, \
            "Cannot pass const " TYPENAME " (class " FNAME ") " \
            "as a mutable reference", \
            RETURNNULL); \
    }


#define SWIG_check_nonnull(SWIG_CLASS_WRAPPER, TYPENAME, FNAME, FUNCNAME, RETURNNULL) \
  if (!(SWIG_CLASS_WRAPPER).cptr) { \
    SWIG_exception_impl(FUNCNAME, SWIG_TypeError, \
                        "Cannot pass null " TYPENAME " (class " FNAME ") " \
                        "as a reference", RETURNNULL); \
  }


#define SWIG_check_mutable_nonnull(SWIG_CLASS_WRAPPER, TYPENAME, FNAME, FUNCNAME, RETURNNULL) \
    SWIG_check_nonnull(SWIG_CLASS_WRAPPER, TYPENAME, FNAME, FUNCNAME, RETURNNULL); \
    SWIG_check_mutable(SWIG_CLASS_WRAPPER, TYPENAME, FNAME, FUNCNAME, RETURNNULL);


#include <stdio.h>
#if defined(_MSC_VER) || defined(__BORLANDC__) || defined(_WATCOM)
# ifndef snprintf
#  define snprintf _snprintf
# endif
#endif


/* Support for the `contract` feature.
 *
 * Note that RETURNNULL is first because it's inserted via a 'Replaceall' in
 * the fortran.cxx file.
 */
#define SWIG_contract_assert(RETURNNULL, EXPR, MSG) \
 if (!(EXPR)) { SWIG_exception_impl("$decl", SWIG_ValueError, MSG, RETURNNULL); } 


#define SWIGVERSION 0x040000 
#define SWIG_VERSION SWIGVERSION


#define SWIG_as_voidptr(a) (void *)((const void *)(a)) 
#define SWIG_as_voidptrptr(a) ((void)SWIG_as_voidptr(*a),(void**)(a)) 


#include "sundials/sundials_heuristics.h"


typedef struct {
    void* cptr;
    int cmemflags;
} SwigClassWrapper;


SWIGINTERN SwigClassWrapper SwigClassWrapper_uninitialized() {
    SwigClassWrapper result;
    result.cptr = NULL;
    result.cmemflags = 0;
    return result;
}


#include <stdlib.h>
#ifdef _MSC_VER
# ifndef strtoull
#  define strtoull _strtoui64
# endif
# ifndef strtoll
#  define strtoll _strtoi64
# endif
#endif


#include <string.h>


SWIGINTERN void SWIG_assign(SwigClassWrapper* self, SwigClassWrapper other) {
  if (self->cptr == NULL) {
    /* LHS is unassigned */
    if (other.cmemflags & SWIG_MEM_RVALUE) {
      /* Capture pointer from RHS, clear 'moving' flag */
      self->cptr = other.cptr;
      self->cmemflags = other.cmemflags & (~SWIG_MEM_RVALUE);
    } else {
      /* Become a reference to the other object */
      self->cptr = other.cptr;
      self->cmemflags = other.cmemflags & (~SWIG_MEM_OWN);
    }
  } else if (other.cptr == NULL) {
    /* Replace LHS with a null pointer */
    free(self->cptr);
    *self = SwigClassWrapper_uninitialized();
  } else {
    if (self->cmemflags & SWIG_MEM_OWN) {
      free(self->cptr);
    }
    self->cptr = other.cptr;
    if (other.cmemflags & SWIG_MEM_RVALUE) {
      /* Capture RHS */
      self->cmemflags = other.cmemflags & ~SWIG_MEM_RVALUE;
    } else {
      /* Point to RHS */
      self->cmemflags = other.cmemflags & ~SWIG_MEM_OWN;
    }
  }
}

SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_getid_set(SwigClassWrapper const *farg1, SUNHeuristics_ID (*farg2)(SUNHeuristics)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  SUNHeuristics_ID (*arg2)(SUNHeuristics) = (SUNHeuristics_ID (*)(SUNHeuristics)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::getid", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (SUNHeuristics_ID (*)(SUNHeuristics))(farg2);
  if (arg1) (arg1)->getid = arg2;
}


typedef SUNHeuristics_ID (*_generic_SUNHeuristics_Ops_getid_get_swigrtype)(SUNHeuristics);
SWIGEXPORT _generic_SUNHeuristics_Ops_getid_get_swigrtype _wrap__generic_SUNHeuristics_Ops_getid_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_getid_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  SUNHeuristics_ID (*result)(SUNHeuristics) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::getid", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (SUNHeuristics_ID (*)(SUNHeuristics)) ((arg1)->getid);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_destroy_set(SwigClassWrapper const *farg1, void (*farg2)(SUNHeuristics)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  void (*arg2)(SUNHeuristics) = (void (*)(SUNHeuristics)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::destroy", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (void (*)(SUNHeuristics))(farg2);
  if (arg1) (arg1)->destroy = arg2;
}


typedef void (*_generic_SUNHeuristics_Ops_destroy_get_swigrtype)(SUNHeuristics);
SWIGEXPORT _generic_SUNHeuristics_Ops_destroy_get_swigrtype _wrap__generic_SUNHeuristics_Ops_destroy_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_destroy_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  void (*result)(SUNHeuristics) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::destroy", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (void (*)(SUNHeuristics)) ((arg1)->destroy);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_constrainstep_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics,realtype,realtype,realtype *)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics,realtype,realtype,realtype *) = (int (*)(SUNHeuristics,realtype,realtype,realtype *)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::constrainstep", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics,realtype,realtype,realtype *))(farg2);
  if (arg1) (arg1)->constrainstep = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_constrainstep_get_swigrtype)(SUNHeuristics,realtype,realtype,realtype *);
SWIGEXPORT _generic_SUNHeuristics_Ops_constrainstep_get_swigrtype _wrap__generic_SUNHeuristics_Ops_constrainstep_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_constrainstep_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics,realtype,realtype,realtype *) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::constrainstep", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics,realtype,realtype,realtype *)) ((arg1)->constrainstep);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_etestfail_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics,realtype,realtype,int,realtype *)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics,realtype,realtype,int,realtype *) = (int (*)(SUNHeuristics,realtype,realtype,int,realtype *)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::etestfail", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics,realtype,realtype,int,realtype *))(farg2);
  if (arg1) (arg1)->etestfail = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_etestfail_get_swigrtype)(SUNHeuristics,realtype,realtype,int,realtype *);
SWIGEXPORT _generic_SUNHeuristics_Ops_etestfail_get_swigrtype _wrap__generic_SUNHeuristics_Ops_etestfail_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_etestfail_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics,realtype,realtype,int,realtype *) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::etestfail", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics,realtype,realtype,int,realtype *)) ((arg1)->etestfail);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_convfail_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics,realtype,realtype *)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics,realtype,realtype *) = (int (*)(SUNHeuristics,realtype,realtype *)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::convfail", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics,realtype,realtype *))(farg2);
  if (arg1) (arg1)->convfail = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_convfail_get_swigrtype)(SUNHeuristics,realtype,realtype *);
SWIGEXPORT _generic_SUNHeuristics_Ops_convfail_get_swigrtype _wrap__generic_SUNHeuristics_Ops_convfail_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_convfail_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics,realtype,realtype *) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::convfail", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics,realtype,realtype *)) ((arg1)->convfail);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_boundreduction_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics,realtype,realtype,realtype *)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics,realtype,realtype,realtype *) = (int (*)(SUNHeuristics,realtype,realtype,realtype *)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::boundreduction", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics,realtype,realtype,realtype *))(farg2);
  if (arg1) (arg1)->boundreduction = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_boundreduction_get_swigrtype)(SUNHeuristics,realtype,realtype,realtype *);
SWIGEXPORT _generic_SUNHeuristics_Ops_boundreduction_get_swigrtype _wrap__generic_SUNHeuristics_Ops_boundreduction_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_boundreduction_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics,realtype,realtype,realtype *) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::boundreduction", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics,realtype,realtype,realtype *)) ((arg1)->boundreduction);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_boundfirststep_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics,realtype,realtype *)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics,realtype,realtype *) = (int (*)(SUNHeuristics,realtype,realtype *)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::boundfirststep", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics,realtype,realtype *))(farg2);
  if (arg1) (arg1)->boundfirststep = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_boundfirststep_get_swigrtype)(SUNHeuristics,realtype,realtype *);
SWIGEXPORT _generic_SUNHeuristics_Ops_boundfirststep_get_swigrtype _wrap__generic_SUNHeuristics_Ops_boundfirststep_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_boundfirststep_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics,realtype,realtype *) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::boundfirststep", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics,realtype,realtype *)) ((arg1)->boundfirststep);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_reset_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics) = (int (*)(SUNHeuristics)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::reset", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics))(farg2);
  if (arg1) (arg1)->reset = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_reset_get_swigrtype)(SUNHeuristics);
SWIGEXPORT _generic_SUNHeuristics_Ops_reset_get_swigrtype _wrap__generic_SUNHeuristics_Ops_reset_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_reset_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::reset", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics)) ((arg1)->reset);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_update_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics) = (int (*)(SUNHeuristics)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::update", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics))(farg2);
  if (arg1) (arg1)->update = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_update_get_swigrtype)(SUNHeuristics);
SWIGEXPORT _generic_SUNHeuristics_Ops_update_get_swigrtype _wrap__generic_SUNHeuristics_Ops_update_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_update_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::update", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics)) ((arg1)->update);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_setdefaults_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics) = (int (*)(SUNHeuristics)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setdefaults", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics))(farg2);
  if (arg1) (arg1)->setdefaults = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_setdefaults_get_swigrtype)(SUNHeuristics);
SWIGEXPORT _generic_SUNHeuristics_Ops_setdefaults_get_swigrtype _wrap__generic_SUNHeuristics_Ops_setdefaults_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_setdefaults_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setdefaults", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics)) ((arg1)->setdefaults);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_write_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics,FILE *)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics,FILE *) = (int (*)(SUNHeuristics,FILE *)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::write", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics,FILE *))(farg2);
  if (arg1) (arg1)->write = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_write_get_swigrtype)(SUNHeuristics,FILE *);
SWIGEXPORT _generic_SUNHeuristics_Ops_write_get_swigrtype _wrap__generic_SUNHeuristics_Ops_write_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_write_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics,FILE *) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::write", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics,FILE *)) ((arg1)->write);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_setmaxstep_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics,realtype)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics,realtype) = (int (*)(SUNHeuristics,realtype)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setmaxstep", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics,realtype))(farg2);
  if (arg1) (arg1)->setmaxstep = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_setmaxstep_get_swigrtype)(SUNHeuristics,realtype);
SWIGEXPORT _generic_SUNHeuristics_Ops_setmaxstep_get_swigrtype _wrap__generic_SUNHeuristics_Ops_setmaxstep_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_setmaxstep_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics,realtype) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setmaxstep", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics,realtype)) ((arg1)->setmaxstep);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_setminstep_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics,realtype)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics,realtype) = (int (*)(SUNHeuristics,realtype)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setminstep", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics,realtype))(farg2);
  if (arg1) (arg1)->setminstep = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_setminstep_get_swigrtype)(SUNHeuristics,realtype);
SWIGEXPORT _generic_SUNHeuristics_Ops_setminstep_get_swigrtype _wrap__generic_SUNHeuristics_Ops_setminstep_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_setminstep_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics,realtype) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setminstep", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics,realtype)) ((arg1)->setminstep);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_setexpstabfn_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics,SUNExpStabFn,void *)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics,SUNExpStabFn,void *) = (int (*)(SUNHeuristics,SUNExpStabFn,void *)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setexpstabfn", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics,SUNExpStabFn,void *))(farg2);
  if (arg1) (arg1)->setexpstabfn = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_setexpstabfn_get_swigrtype)(SUNHeuristics,SUNExpStabFn,void *);
SWIGEXPORT _generic_SUNHeuristics_Ops_setexpstabfn_get_swigrtype _wrap__generic_SUNHeuristics_Ops_setexpstabfn_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_setexpstabfn_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics,SUNExpStabFn,void *) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setexpstabfn", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics,SUNExpStabFn,void *)) ((arg1)->setexpstabfn);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_setcflfraction_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics,realtype)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics,realtype) = (int (*)(SUNHeuristics,realtype)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setcflfraction", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics,realtype))(farg2);
  if (arg1) (arg1)->setcflfraction = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_setcflfraction_get_swigrtype)(SUNHeuristics,realtype);
SWIGEXPORT _generic_SUNHeuristics_Ops_setcflfraction_get_swigrtype _wrap__generic_SUNHeuristics_Ops_setcflfraction_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_setcflfraction_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics,realtype) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setcflfraction", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics,realtype)) ((arg1)->setcflfraction);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_setsafetyfactor_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics,realtype)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics,realtype) = (int (*)(SUNHeuristics,realtype)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setsafetyfactor", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics,realtype))(farg2);
  if (arg1) (arg1)->setsafetyfactor = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_setsafetyfactor_get_swigrtype)(SUNHeuristics,realtype);
SWIGEXPORT _generic_SUNHeuristics_Ops_setsafetyfactor_get_swigrtype _wrap__generic_SUNHeuristics_Ops_setsafetyfactor_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_setsafetyfactor_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics,realtype) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setsafetyfactor", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics,realtype)) ((arg1)->setsafetyfactor);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_setmaxgrowth_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics,realtype)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics,realtype) = (int (*)(SUNHeuristics,realtype)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setmaxgrowth", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics,realtype))(farg2);
  if (arg1) (arg1)->setmaxgrowth = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_setmaxgrowth_get_swigrtype)(SUNHeuristics,realtype);
SWIGEXPORT _generic_SUNHeuristics_Ops_setmaxgrowth_get_swigrtype _wrap__generic_SUNHeuristics_Ops_setmaxgrowth_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_setmaxgrowth_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics,realtype) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setmaxgrowth", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics,realtype)) ((arg1)->setmaxgrowth);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_setminreduction_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics,realtype)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics,realtype) = (int (*)(SUNHeuristics,realtype)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setminreduction", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics,realtype))(farg2);
  if (arg1) (arg1)->setminreduction = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_setminreduction_get_swigrtype)(SUNHeuristics,realtype);
SWIGEXPORT _generic_SUNHeuristics_Ops_setminreduction_get_swigrtype _wrap__generic_SUNHeuristics_Ops_setminreduction_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_setminreduction_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics,realtype) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setminreduction", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics,realtype)) ((arg1)->setminreduction);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_setfixedstepbounds_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics,realtype,realtype)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics,realtype,realtype) = (int (*)(SUNHeuristics,realtype,realtype)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setfixedstepbounds", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics,realtype,realtype))(farg2);
  if (arg1) (arg1)->setfixedstepbounds = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_setfixedstepbounds_get_swigrtype)(SUNHeuristics,realtype,realtype);
SWIGEXPORT _generic_SUNHeuristics_Ops_setfixedstepbounds_get_swigrtype _wrap__generic_SUNHeuristics_Ops_setfixedstepbounds_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_setfixedstepbounds_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics,realtype,realtype) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setfixedstepbounds", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics,realtype,realtype)) ((arg1)->setfixedstepbounds);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_setmaxfirstgrowth_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics,realtype)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics,realtype) = (int (*)(SUNHeuristics,realtype)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setmaxfirstgrowth", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics,realtype))(farg2);
  if (arg1) (arg1)->setmaxfirstgrowth = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_setmaxfirstgrowth_get_swigrtype)(SUNHeuristics,realtype);
SWIGEXPORT _generic_SUNHeuristics_Ops_setmaxfirstgrowth_get_swigrtype _wrap__generic_SUNHeuristics_Ops_setmaxfirstgrowth_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_setmaxfirstgrowth_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics,realtype) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setmaxfirstgrowth", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics,realtype)) ((arg1)->setmaxfirstgrowth);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_setmaxefailgrowth_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics,realtype)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics,realtype) = (int (*)(SUNHeuristics,realtype)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setmaxefailgrowth", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics,realtype))(farg2);
  if (arg1) (arg1)->setmaxefailgrowth = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_setmaxefailgrowth_get_swigrtype)(SUNHeuristics,realtype);
SWIGEXPORT _generic_SUNHeuristics_Ops_setmaxefailgrowth_get_swigrtype _wrap__generic_SUNHeuristics_Ops_setmaxefailgrowth_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_setmaxefailgrowth_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics,realtype) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setmaxefailgrowth", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics,realtype)) ((arg1)->setmaxefailgrowth);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_setsmallnumefails_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics,int)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics,int) = (int (*)(SUNHeuristics,int)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setsmallnumefails", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics,int))(farg2);
  if (arg1) (arg1)->setsmallnumefails = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_setsmallnumefails_get_swigrtype)(SUNHeuristics,int);
SWIGEXPORT _generic_SUNHeuristics_Ops_setsmallnumefails_get_swigrtype _wrap__generic_SUNHeuristics_Ops_setsmallnumefails_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_setsmallnumefails_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics,int) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setsmallnumefails", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics,int)) ((arg1)->setsmallnumefails);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_setmaxcfailgrowth_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics,realtype)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics,realtype) = (int (*)(SUNHeuristics,realtype)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setmaxcfailgrowth", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics,realtype))(farg2);
  if (arg1) (arg1)->setmaxcfailgrowth = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_setmaxcfailgrowth_get_swigrtype)(SUNHeuristics,realtype);
SWIGEXPORT _generic_SUNHeuristics_Ops_setmaxcfailgrowth_get_swigrtype _wrap__generic_SUNHeuristics_Ops_setmaxcfailgrowth_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_setmaxcfailgrowth_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics,realtype) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::setmaxcfailgrowth", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics,realtype)) ((arg1)->setmaxcfailgrowth);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_getnumexpsteps_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics,long *)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics,long *) = (int (*)(SUNHeuristics,long *)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::getnumexpsteps", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics,long *))(farg2);
  if (arg1) (arg1)->getnumexpsteps = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_getnumexpsteps_get_swigrtype)(SUNHeuristics,long *);
SWIGEXPORT _generic_SUNHeuristics_Ops_getnumexpsteps_get_swigrtype _wrap__generic_SUNHeuristics_Ops_getnumexpsteps_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_getnumexpsteps_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics,long *) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::getnumexpsteps", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics,long *)) ((arg1)->getnumexpsteps);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_getnumaccsteps_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics,long *)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics,long *) = (int (*)(SUNHeuristics,long *)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::getnumaccsteps", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics,long *))(farg2);
  if (arg1) (arg1)->getnumaccsteps = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_getnumaccsteps_get_swigrtype)(SUNHeuristics,long *);
SWIGEXPORT _generic_SUNHeuristics_Ops_getnumaccsteps_get_swigrtype _wrap__generic_SUNHeuristics_Ops_getnumaccsteps_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_getnumaccsteps_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics,long *) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::getnumaccsteps", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics,long *)) ((arg1)->getnumaccsteps);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_space_set(SwigClassWrapper const *farg1, int (*farg2)(SUNHeuristics,long *,long *)) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*arg2)(SUNHeuristics,long *,long *) = (int (*)(SUNHeuristics,long *,long *)) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::space", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  arg2 = (int (*)(SUNHeuristics,long *,long *))(farg2);
  if (arg1) (arg1)->space = arg2;
}


typedef int (*_generic_SUNHeuristics_Ops_space_get_swigrtype)(SUNHeuristics,long *,long *);
SWIGEXPORT _generic_SUNHeuristics_Ops_space_get_swigrtype _wrap__generic_SUNHeuristics_Ops_space_get(SwigClassWrapper const *farg1) {
  _generic_SUNHeuristics_Ops_space_get_swigrtype fresult ;
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  int (*result)(SUNHeuristics,long *,long *) = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::space", return 0);
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  result = (int (*)(SUNHeuristics,long *,long *)) ((arg1)->space);
  fresult = result;
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new__generic_SUNHeuristics_Ops() {
  SwigClassWrapper fresult ;
  struct _generic_SUNHeuristics_Ops *result = 0 ;
  
  result = (struct _generic_SUNHeuristics_Ops *)calloc(1, sizeof(struct _generic_SUNHeuristics_Ops));
  fresult.cptr = result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete__generic_SUNHeuristics_Ops(SwigClassWrapper *farg1) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  
  SWIG_check_mutable(*farg1, "struct _generic_SUNHeuristics_Ops *", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics_Ops::~_generic_SUNHeuristics_Ops()", return );
  arg1 = (struct _generic_SUNHeuristics_Ops *)(farg1->cptr);
  free((char *) arg1);
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_Ops_op_assign__(SwigClassWrapper *farg1, SwigClassWrapper const *farg2) {
  struct _generic_SUNHeuristics_Ops *arg1 = (struct _generic_SUNHeuristics_Ops *) 0 ;
  struct _generic_SUNHeuristics_Ops *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_content_set(SwigClassWrapper const *farg1, void *farg2) {
  struct _generic_SUNHeuristics *arg1 = (struct _generic_SUNHeuristics *) 0 ;
  void *arg2 = (void *) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics *", "generic_SUNHeuristics_", "_generic_SUNHeuristics::content", return );
  arg1 = (struct _generic_SUNHeuristics *)(farg1->cptr);
  arg2 = (void *)(farg2);
  if (arg1) (arg1)->content = arg2;
}


SWIGEXPORT void * _wrap__generic_SUNHeuristics_content_get(SwigClassWrapper const *farg1) {
  void * fresult ;
  struct _generic_SUNHeuristics *arg1 = (struct _generic_SUNHeuristics *) 0 ;
  void *result = 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics *", "generic_SUNHeuristics_", "_generic_SUNHeuristics::content", return 0);
  arg1 = (struct _generic_SUNHeuristics *)(farg1->cptr);
  result = (void *) ((arg1)->content);
  fresult = result;
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_ops_set(SwigClassWrapper const *farg1, SwigClassWrapper const *farg2) {
  struct _generic_SUNHeuristics *arg1 = (struct _generic_SUNHeuristics *) 0 ;
  SUNHeuristics_Ops arg2 = (SUNHeuristics_Ops) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics *", "generic_SUNHeuristics_", "_generic_SUNHeuristics::ops", return );
  arg1 = (struct _generic_SUNHeuristics *)(farg1->cptr);
  SWIG_check_mutable(*farg2, "SUNHeuristics_Ops", "generic_SUNHeuristics_Ops_", "_generic_SUNHeuristics::ops", return );
  arg2 = (SUNHeuristics_Ops)(farg2->cptr);
  if (arg1) (arg1)->ops = arg2;
}


SWIGEXPORT SwigClassWrapper _wrap__generic_SUNHeuristics_ops_get(SwigClassWrapper const *farg1) {
  SwigClassWrapper fresult ;
  struct _generic_SUNHeuristics *arg1 = (struct _generic_SUNHeuristics *) 0 ;
  SUNHeuristics_Ops result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics *", "generic_SUNHeuristics_", "_generic_SUNHeuristics::ops", return SwigClassWrapper_uninitialized());
  arg1 = (struct _generic_SUNHeuristics *)(farg1->cptr);
  result = (SUNHeuristics_Ops) ((arg1)->ops);
  fresult.cptr = result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_sunctx_set(SwigClassWrapper const *farg1, void *farg2) {
  struct _generic_SUNHeuristics *arg1 = (struct _generic_SUNHeuristics *) 0 ;
  SUNContext arg2 = (SUNContext) 0 ;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics *", "generic_SUNHeuristics_", "_generic_SUNHeuristics::sunctx", return );
  arg1 = (struct _generic_SUNHeuristics *)(farg1->cptr);
  arg2 = (SUNContext)(farg2);
  if (arg1) (arg1)->sunctx = arg2;
}


SWIGEXPORT void * _wrap__generic_SUNHeuristics_sunctx_get(SwigClassWrapper const *farg1) {
  void * fresult ;
  struct _generic_SUNHeuristics *arg1 = (struct _generic_SUNHeuristics *) 0 ;
  SUNContext result;
  
  SWIG_check_mutable_nonnull(*farg1, "struct _generic_SUNHeuristics *", "generic_SUNHeuristics_", "_generic_SUNHeuristics::sunctx", return 0);
  arg1 = (struct _generic_SUNHeuristics *)(farg1->cptr);
  result = (SUNContext) ((arg1)->sunctx);
  fresult = result;
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new__generic_SUNHeuristics() {
  SwigClassWrapper fresult ;
  struct _generic_SUNHeuristics *result = 0 ;
  
  result = (struct _generic_SUNHeuristics *)calloc(1, sizeof(struct _generic_SUNHeuristics));
  fresult.cptr = result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete__generic_SUNHeuristics(SwigClassWrapper *farg1) {
  struct _generic_SUNHeuristics *arg1 = (struct _generic_SUNHeuristics *) 0 ;
  
  SWIG_check_mutable(*farg1, "struct _generic_SUNHeuristics *", "generic_SUNHeuristics_", "_generic_SUNHeuristics::~_generic_SUNHeuristics()", return );
  arg1 = (struct _generic_SUNHeuristics *)(farg1->cptr);
  free((char *) arg1);
}


SWIGEXPORT void _wrap__generic_SUNHeuristics_op_assign__(SwigClassWrapper *farg1, SwigClassWrapper const *farg2) {
  struct _generic_SUNHeuristics *arg1 = (struct _generic_SUNHeuristics *) 0 ;
  struct _generic_SUNHeuristics *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}


SWIGEXPORT SwigClassWrapper _wrap_FSUNHeuristicsNewEmpty(void *farg1) {
  SwigClassWrapper fresult ;
  SUNContext arg1 = (SUNContext) 0 ;
  SUNHeuristics result;
  
  arg1 = (SUNContext)(farg1);
  result = (SUNHeuristics)SUNHeuristicsNewEmpty(arg1);
  fresult.cptr = result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsGetID(SwigClassWrapper const *farg1) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  SUNHeuristics_ID result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsGetID(SUNHeuristics)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  result = (SUNHeuristics_ID)SUNHeuristicsGetID(arg1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT void _wrap_FSUNHeuristicsDestroy(SwigClassWrapper const *farg1) {
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsDestroy(SUNHeuristics)", return );
  arg1 = (SUNHeuristics)(farg1->cptr);
  SUNHeuristicsDestroy(arg1);
}


SWIGEXPORT int _wrap_FSUNHeuristicsConstrainStep(SwigClassWrapper const *farg1, double const *farg2, double const *farg3, double *farg4) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  realtype arg2 ;
  realtype arg3 ;
  realtype *arg4 = (realtype *) 0 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsConstrainStep(SUNHeuristics,realtype,realtype,realtype *)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  arg2 = (realtype)(*farg2);
  arg3 = (realtype)(*farg3);
  arg4 = (realtype *)(farg4);
  result = (int)SUNHeuristicsConstrainStep(arg1,arg2,arg3,arg4);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsETestFail(SwigClassWrapper const *farg1, double const *farg2, double const *farg3, int const *farg4, double *farg5) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  realtype arg2 ;
  realtype arg3 ;
  int arg4 ;
  realtype *arg5 = (realtype *) 0 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsETestFail(SUNHeuristics,realtype,realtype,int,realtype *)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  arg2 = (realtype)(*farg2);
  arg3 = (realtype)(*farg3);
  arg4 = (int)(*farg4);
  arg5 = (realtype *)(farg5);
  result = (int)SUNHeuristicsETestFail(arg1,arg2,arg3,arg4,arg5);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsBoundReduction(SwigClassWrapper const *farg1, double const *farg2, double const *farg3, double *farg4) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  realtype arg2 ;
  realtype arg3 ;
  realtype *arg4 = (realtype *) 0 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsBoundReduction(SUNHeuristics,realtype,realtype,realtype *)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  arg2 = (realtype)(*farg2);
  arg3 = (realtype)(*farg3);
  arg4 = (realtype *)(farg4);
  result = (int)SUNHeuristicsBoundReduction(arg1,arg2,arg3,arg4);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsBoundFirstStep(SwigClassWrapper const *farg1, double const *farg2, double *farg3) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  realtype arg2 ;
  realtype *arg3 = (realtype *) 0 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsBoundFirstStep(SUNHeuristics,realtype,realtype *)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  arg2 = (realtype)(*farg2);
  arg3 = (realtype *)(farg3);
  result = (int)SUNHeuristicsBoundFirstStep(arg1,arg2,arg3);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsConvFail(SwigClassWrapper const *farg1, double const *farg2, double *farg3) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  realtype arg2 ;
  realtype *arg3 = (realtype *) 0 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsConvFail(SUNHeuristics,realtype,realtype *)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  arg2 = (realtype)(*farg2);
  arg3 = (realtype *)(farg3);
  result = (int)SUNHeuristicsConvFail(arg1,arg2,arg3);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsReset(SwigClassWrapper const *farg1) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsReset(SUNHeuristics)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  result = (int)SUNHeuristicsReset(arg1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsUpdate(SwigClassWrapper const *farg1) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsUpdate(SUNHeuristics)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  result = (int)SUNHeuristicsUpdate(arg1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsSetDefaults(SwigClassWrapper const *farg1) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsSetDefaults(SUNHeuristics)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  result = (int)SUNHeuristicsSetDefaults(arg1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsWrite(SwigClassWrapper const *farg1, void *farg2) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  FILE *arg2 = (FILE *) 0 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsWrite(SUNHeuristics,FILE *)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  arg2 = (FILE *)(farg2);
  result = (int)SUNHeuristicsWrite(arg1,arg2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsSetMaxStep(SwigClassWrapper const *farg1, double const *farg2) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  realtype arg2 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsSetMaxStep(SUNHeuristics,realtype)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  arg2 = (realtype)(*farg2);
  result = (int)SUNHeuristicsSetMaxStep(arg1,arg2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsSetMinStep(SwigClassWrapper const *farg1, double const *farg2) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  realtype arg2 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsSetMinStep(SUNHeuristics,realtype)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  arg2 = (realtype)(*farg2);
  result = (int)SUNHeuristicsSetMinStep(arg1,arg2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsSetExpStabFn(SwigClassWrapper const *farg1, SUNExpStabFn farg2, void *farg3) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  SUNExpStabFn arg2 = (SUNExpStabFn) 0 ;
  void *arg3 = (void *) 0 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsSetExpStabFn(SUNHeuristics,SUNExpStabFn,void *)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  arg2 = (SUNExpStabFn)(farg2);
  arg3 = (void *)(farg3);
  result = (int)SUNHeuristicsSetExpStabFn(arg1,arg2,arg3);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsSetCFLFraction(SwigClassWrapper const *farg1, double const *farg2) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  realtype arg2 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsSetCFLFraction(SUNHeuristics,realtype)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  arg2 = (realtype)(*farg2);
  result = (int)SUNHeuristicsSetCFLFraction(arg1,arg2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsSetSafetyFactor(SwigClassWrapper const *farg1, double const *farg2) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  realtype arg2 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsSetSafetyFactor(SUNHeuristics,realtype)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  arg2 = (realtype)(*farg2);
  result = (int)SUNHeuristicsSetSafetyFactor(arg1,arg2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsSetMaxGrowth(SwigClassWrapper const *farg1, double const *farg2) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  realtype arg2 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsSetMaxGrowth(SUNHeuristics,realtype)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  arg2 = (realtype)(*farg2);
  result = (int)SUNHeuristicsSetMaxGrowth(arg1,arg2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsSetMaxFirstGrowth(SwigClassWrapper const *farg1, double const *farg2) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  realtype arg2 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsSetMaxFirstGrowth(SUNHeuristics,realtype)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  arg2 = (realtype)(*farg2);
  result = (int)SUNHeuristicsSetMaxFirstGrowth(arg1,arg2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsSetFixedStepBounds(SwigClassWrapper const *farg1, double const *farg2, double const *farg3) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  realtype arg2 ;
  realtype arg3 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsSetFixedStepBounds(SUNHeuristics,realtype,realtype)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  arg2 = (realtype)(*farg2);
  arg3 = (realtype)(*farg3);
  result = (int)SUNHeuristicsSetFixedStepBounds(arg1,arg2,arg3);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsSetMinReduction(SwigClassWrapper const *farg1, double const *farg2) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  realtype arg2 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsSetMinReduction(SUNHeuristics,realtype)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  arg2 = (realtype)(*farg2);
  result = (int)SUNHeuristicsSetMinReduction(arg1,arg2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsSetMaxEFailGrowth(SwigClassWrapper const *farg1, double const *farg2) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  realtype arg2 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsSetMaxEFailGrowth(SUNHeuristics,realtype)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  arg2 = (realtype)(*farg2);
  result = (int)SUNHeuristicsSetMaxEFailGrowth(arg1,arg2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsSetSmallNumEFails(SwigClassWrapper const *farg1, int const *farg2) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  int arg2 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsSetSmallNumEFails(SUNHeuristics,int)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  arg2 = (int)(*farg2);
  result = (int)SUNHeuristicsSetSmallNumEFails(arg1,arg2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsSetMaxCFailGrowth(SwigClassWrapper const *farg1, double const *farg2) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  realtype arg2 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsSetMaxCFailGrowth(SUNHeuristics,realtype)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  arg2 = (realtype)(*farg2);
  result = (int)SUNHeuristicsSetMaxCFailGrowth(arg1,arg2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsGetNumExpSteps(SwigClassWrapper const *farg1, long *farg2) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  long *arg2 = (long *) 0 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsGetNumExpSteps(SUNHeuristics,long *)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  arg2 = (long *)(farg2);
  result = (int)SUNHeuristicsGetNumExpSteps(arg1,arg2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsGetNumAccSteps(SwigClassWrapper const *farg1, long *farg2) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  long *arg2 = (long *) 0 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsGetNumAccSteps(SUNHeuristics,long *)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  arg2 = (long *)(farg2);
  result = (int)SUNHeuristicsGetNumAccSteps(arg1,arg2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_FSUNHeuristicsSpace(SwigClassWrapper const *farg1, long *farg2, long *farg3) {
  int fresult ;
  SUNHeuristics arg1 = (SUNHeuristics) 0 ;
  long *arg2 = (long *) 0 ;
  long *arg3 = (long *) 0 ;
  int result;
  
  SWIG_check_mutable(*farg1, "SUNHeuristics", "generic_SUNHeuristics_", "SUNHeuristicsSpace(SUNHeuristics,long *,long *)", return 0);
  arg1 = (SUNHeuristics)(farg1->cptr);
  arg2 = (long *)(farg2);
  arg3 = (long *)(farg3);
  result = (int)SUNHeuristicsSpace(arg1,arg2,arg3);
  fresult = (int)(result);
  return fresult;
}



