! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! ---------------------------------------------------------------
! Programmer(s): Auto-generated by swig.
! ---------------------------------------------------------------
! SUNDIALS Copyright Start
! Copyright (c) 2002-2019, Lawrence Livermore National Security
! and Southern Methodist University.
! All rights reserved.
!
! See the top-level LICENSE and NOTICE files for details.
!
! SPDX-License-Identifier: BSD-3-Clause
! SUNDIALS Copyright End
! ---------------------------------------------------------------

module fsunmatrix_band_mod
 use, intrinsic :: ISO_C_BINDING
 use fsunmatrix_mod
 use fsundials_types
 implicit none
 private

 ! DECLARATION CONSTRUCTS

  public :: FSUNMatGetData_Band
  
 public :: FSUNBandMatrix
 public :: FSUNBandMatrixStorage
 public :: FSUNBandMatrix_Print
 public :: FSUNBandMatrix_Rows
 public :: FSUNBandMatrix_Columns
 public :: FSUNBandMatrix_LowerBandwidth
 public :: FSUNBandMatrix_UpperBandwidth
 public :: FSUNBandMatrix_StoredUpperBandwidth
 public :: FSUNBandMatrix_LDim
 public :: FSUNBandMatrix_Data
 public :: FSUNBandMatrix_Cols
 public :: FSUNBandMatrix_Column
 public :: FSUNMatGetID_Band
 public :: FSUNMatClone_Band
 public :: FSUNMatDestroy_Band
 public :: FSUNMatZero_Band
 public :: FSUNMatCopy_Band
 public :: FSUNMatScaleAdd_Band
 public :: FSUNMatScaleAddI_Band
 public :: FSUNMatMatvec_Band
 public :: FSUNMatSpace_Band

! WRAPPER DECLARATIONS
interface
function FSUNBandMatrix(n, mu, ml) &
bind(C, name="SUNBandMatrix") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T), value :: n
integer(C_INT64_T), value :: mu
integer(C_INT64_T), value :: ml
type(C_PTR) :: fresult
end function

function FSUNBandMatrixStorage(n, mu, ml, smu) &
bind(C, name="SUNBandMatrixStorage") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T), value :: n
integer(C_INT64_T), value :: mu
integer(C_INT64_T), value :: ml
integer(C_INT64_T), value :: smu
type(C_PTR) :: fresult
end function

subroutine FSUNBandMatrix_Print(a, outfile) &
bind(C, name="SUNBandMatrix_Print")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: a
type(C_PTR), value :: outfile
end subroutine

function FSUNBandMatrix_Rows(a) &
bind(C, name="SUNBandMatrix_Rows") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: a
integer(C_INT64_T) :: fresult
end function

function FSUNBandMatrix_Columns(a) &
bind(C, name="SUNBandMatrix_Columns") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: a
integer(C_INT64_T) :: fresult
end function

function FSUNBandMatrix_LowerBandwidth(a) &
bind(C, name="SUNBandMatrix_LowerBandwidth") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: a
integer(C_INT64_T) :: fresult
end function

function FSUNBandMatrix_UpperBandwidth(a) &
bind(C, name="SUNBandMatrix_UpperBandwidth") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: a
integer(C_INT64_T) :: fresult
end function

function FSUNBandMatrix_StoredUpperBandwidth(a) &
bind(C, name="SUNBandMatrix_StoredUpperBandwidth") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: a
integer(C_INT64_T) :: fresult
end function

function FSUNBandMatrix_LDim(a) &
bind(C, name="SUNBandMatrix_LDim") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: a
integer(C_INT64_T) :: fresult
end function

function FSUNBandMatrix_Data(a) &
bind(C, name="SUNBandMatrix_Data") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: a
type(C_PTR) :: fresult
end function

function FSUNBandMatrix_Cols(a) &
bind(C, name="SUNBandMatrix_Cols") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: a
type(C_PTR) :: fresult
end function

function FSUNBandMatrix_Column(a, j) &
bind(C, name="SUNBandMatrix_Column") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: a
integer(C_INT64_T), value :: j
type(C_PTR) :: fresult
end function

function FSUNMatGetID_Band(a) &
bind(C, name="SUNMatGetID_Band") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: a
integer(C_INT) :: fresult
end function

function FSUNMatClone_Band(a) &
bind(C, name="SUNMatClone_Band") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: a
type(C_PTR) :: fresult
end function

subroutine FSUNMatDestroy_Band(a) &
bind(C, name="SUNMatDestroy_Band")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: a
end subroutine

function FSUNMatZero_Band(a) &
bind(C, name="SUNMatZero_Band") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: a
integer(C_INT) :: fresult
end function

function FSUNMatCopy_Band(a, b) &
bind(C, name="SUNMatCopy_Band") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: a
type(C_PTR), value :: b
integer(C_INT) :: fresult
end function

function FSUNMatScaleAdd_Band(c, a, b) &
bind(C, name="SUNMatScaleAdd_Band") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), value :: c
type(C_PTR), value :: a
type(C_PTR), value :: b
integer(C_INT) :: fresult
end function

function FSUNMatScaleAddI_Band(c, a) &
bind(C, name="SUNMatScaleAddI_Band") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), value :: c
type(C_PTR), value :: a
integer(C_INT) :: fresult
end function

function FSUNMatMatvec_Band(a, x, y) &
bind(C, name="SUNMatMatvec_Band") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: a
type(C_PTR), value :: x
type(C_PTR), value :: y
integer(C_INT) :: fresult
end function

function FSUNMatSpace_Band(a, lenrw, leniw) &
bind(C, name="SUNMatSpace_Band") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: a
integer(C_LONG) :: lenrw
integer(C_LONG) :: leniw
integer(C_INT) :: fresult
end function

end interface


contains
 ! MODULE SUBPROGRAMS

  subroutine FSUNMatGetData_Band(mat, mdata)

      use, intrinsic :: iso_c_binding
      implicit none

      type(C_PTR)        :: mat
      integer(C_INT64_T) :: M, N
      type(C_PTR)        :: cptr
      real(C_DOUBLE), dimension(:,:), pointer :: mdata

      M = FSUNBandMatrix_Rows(mat)
      N = FSUNBandMatrix_Columns(mat)
      cptr = FSUNBandMatrix_Data(mat)

      call c_f_pointer(cptr, mdata, (/M,N/))

  end subroutine FSUNMatGetData_Band
  

end module
